409H/EtherAddressLookup

- css/app.css
- js/DomManipulator.js
- js/addLinkToEtherAddress.js
- js/options.js
- js/toggleMatchHighlight.js
- manifest.json
- options.html
* Added the ability to toggle the highlight option.
https://twitter.com/sniko_/status/876907128157548545
> [ FEATURE ] Toggle Highlight {release}

- js/DomManipulator.js
- js/app/toggleBlacklistDomains.js
- js/options.js
- manifest.json
- options.html
* Added `blacklists/domains.json` to hold a dump of blacklisted domains. If you are directed to a blacklisted domain, then you will be greeted with a warning saying that the extension has prevented you from interacting with it.
> [ FEATURE ] Blacklisted domain warning {release}

- blacklists/domains.json
- js/DomManipulator.js
- manifest.json
Fixed a bug that caused the blacklisting to not work in all scenarios.
> [ RELEASE ] v1.3.1 {master}

- blacklists/domains.json
https://www.reddit.com/r/ethtrader/comments/6m17id/watch_out_for_phishing_attempts_on_the_slack/
> Update blacklisted domains.json

- blacklists/domains.json
Suspected stealing private keys.
> Update domains.json - coin-wallet.info

- js/DomManipulator.js
I added the [levenshtein check](https://github.com/409H/EtherAddressLookup/issues/17) to catch similar words. I also created a passthrough specifically for myetherwallet. 
I did a small analysis on the blacklist and came up with the following results. The code for the analysis is [here](https://gist.github.com/sogoiii/aee03338132012245b888baddc8dff18)
```javascirpt
{
"score": {
"min": 1,
"max": 27,
"mean": 7.221316614420063,
"median": 7,
"std": 3.639774978064392
}
}
```
If you look at the code, I have the limit set to `7 + 3.639774978064392`. This may be aggressive, and can always lowered.
> Issue #17 - Levenshtein check

- README.md
- js/DomManipulator.js
- js/options.js
- manifest.json
* Added Firefox support.
* If phishing domain is detected, it will redirect you to another domain completely, instead of wiping the DOM.
> Issue #26 - Added logic to enable Firefox support

- blacklists/domains.json
newly registered, not pointing to anything yet, looks phishy
> New domains

- blacklists/domains.json
compare to digitaldevelopersfund.com
> scam ico site

- blacklists/domains.json
Saw it on a slack channel. They're trying to imitate etherdelta.
> Add etherdelta phishing link

- blacklists/domains.json
They're attempting to phish/scam via slackbot reminder. Screenshot taken on slack mobile:
https://s11.postimg.org/t4sql3mur/Screenshot_2017-07-27-00-32-56-215_com.Slack.png
> Add etherswap.org

- blacklists/domains.json
Spotted in the MetaMask slack.
> Add mvetherwallet to blacklist

- blacklists/domains.json
another phishing attempt. myelherwallel.com
> myelherwallel: new phishing site

- whitelists/domains.json
Its my webapp to provide Ethereum popularisation.
> etherecho.com automaticaly blacklisted by algo

- js/DomainBlacklist.js
- manifest.json
Adds the domain to the query string so you can see which domain is blacklisted.
> Issue #75 - Adds the domain you were redirected from to the query string

- js/DomManipulator.js
- manifest.json
Also added small to the whitelisted tags to iterate through to match strings (fixes the myetherwallet donation link that was annoying me :P)
> Issue #49 - Makes the 0x mandatory for matching the hex string

- blacklists/domains.json
Fake airdrop, asking for private key
https://etherscamdb.info/scam/2144/
> Update domains.json - status-token.com

- blacklists/domains.json
Fake airdrop, asks for private key
> Update domains.json - omise-omg.com

- blacklists/domains.json
Fake airdrop, asks for private key
> Update domains.json - tenxpay.io

- blacklists/domains.json
See:
https://etherscamdb.info/scam/2182/
https://myetherwallet.slack.com/archives/C69936HAP/p1504742923000116
> iconexus.social & omise-go.org

- blacklists/domains.json
See:
https://github.com/MrLuit/EtherScamDB/commit/c2587ca545ffd508d9a524e0a9287fb5b18e8a20
https://github.com/MrLuit/EtherScamDB/commit/52971473b03cf93cc6ea272fb5b85183fa88fe44
https://github.com/MrLuit/EtherScamDB/commit/f4ed9455c09f7a8a894a46b0c6f93b9ad7ef0327
> coindash.su, myethwallet.co.uk, myelherwatlet.com, myethereumwallet.uk

- blacklists/domains.json
See https://github.com/MrLuit/EtherScamDB/commit/e13794a6d801a802ddffff7f868062e58e5d4fc1
https://etherscamdb.info/scam/2199/
https://etherscamdb.info/scam/2200/
https://etherscamdb.info/scam/2201/
> iconexu.social, wanchain.co, enigrna.co

- blacklists/domains.json
Addded 3 new myethereumwallet.com urls
> Update list of scammers

- blacklists/domains.json
See https://github.com/MrLuit/EtherScamDB/commit/9cb58fd0a65527240f8bd8f5d11c03124a801150
> tokensale-kyber.network

- blacklists/domains.json
Per report on MetaMask support center.
> Add kyberr.network

- js/DomainBlacklist.js
- manifest.json
Removes the common `www.` subdomain so we don't have to blacklist everything 👍
> Removes the www. common subdomain from the hostname

- whitelists/domains.json
https://canya.io ICO
Twitter: https://twitter.com/canya_io
Reddit: https://www.reddit.com/user/canya-io
Email:  support@canya.io
Telegram: https://t.me/joinchat/HBzcbUP42NwHZKBwnEIkkw
> CanYa whitelist

- blacklists/domains.json
real one is https://request.network/
You can verify with the blog links
Thanks !
> blacklist www-request.network (phishing)

- blacklists/domains.json
Real one is request.network
Thank you for the time you spend protecting all users
> Phishing website during our crowdsale

- blacklists/domains.json
> Add myethervvaiiet.com

- blacklists/domains.json
…m-lists/pull/214
"xn--mytherwalet-cbb87i.com",
"xn--myethrwallet-ivb.co",
"xn--myeterwallet-f1b.com",
> xn--mytherwalet-cbb87i.com xn--myethrwallet-ivb.co xn--myeterwallet-f1b.com

- blacklists/domains.json
added stormxtoken.com to blacklist.
> stormxtoken.com

- blacklists/domains.json
see https://github.com/MyEtherWallet/ethereum-lists/pull/216/
> myetherwalletverify.info

- blacklists/domains.json
added privatix.pro and privatex.io
> Update domains list with privatix impersonations

- blacklists/domains.json
Impersonating to privatix.io
https://urlscan.io/result/844b1f8f-fb0f-4220-baa8-0692823c7fad#summary 
4th attack on them in the last couple of days
> Adding privatix.top

- options.html
Hey,
Just added the ethergraphs.com domain to the dropdown list of blockchain readers.
Ben
> added ethergraphs.com to the dropdown of blockchain visualisers

- blacklists/domains.json
https://etherscan.io/address/0x22374A2E9E19bcea56E64F9De3329670CD1a458c#comments
> Adding senstoken.com to blacklist.

- blacklists/domains.json
https://urlscan.io/result/415ec966-3199-4955-9dab-d3878b0cdc42#summary
The second one is currently just redirecting the original site
> Adding 2 spoofed MyEtherWallet addresses

- blacklists/domains.json
https://urlscan.io/result/a97d9177-8a36-4b77-bd82-b6842aaf2950#summary
> ṃyetheṛwallet.com

- blacklists/domains.json
https://etherscan.io/address/0xA35e3534917E471540345733B8f23e7bAd54681b#comments
> dentacoin.in

- blacklists/domains.json
https://etherscan.io/address/0x0d3c6F157fc40eDe8Fc2E80a2d03b961853cC243#comments
https://etherscan.io/address/0x584Bf23bEd32C531be9B1974e160a3387B7c30A5#comments
https://etherscan.io/address/0xFE3b256cBDFdB65B7d7fAbf8E5f9f918e47f6DB6#comments
https://etherscan.io/address/0x5813eed7adb205f28dd9a6fdccfafc6fbd7b14bf#comments
https://etherscan.io/address/0x99723bc6EF51644B0Ba52F31aD905a1b3b170d94#comments
https://etherscan.io/address/0xb9088c74b4B7D70A181f2f3a8E1964fb1F6a111c#comments
> Adding datumn.org, daturm.org, datum.org.vc, icodatum.pw, datum.ws to blacklist

- blacklists/domains.json
https://urlscan.io/result/664b3f27-773c-40ef-88cf-872a5551a44b#summary
> Adding another spoofed MEW address

- blacklists/domains.json
Adding wancha.in to blacklist. See https://t.me/WanchainANN
Screenshot: https://imgur.com/a/UCfUO
> Adding wancha.in to blacklist.

- whitelists/domains.json
More information here: https://github.com/409H/EtherAddressLookup/issues/158
Website tree published here: https://github.com/etherball/Etherball/tree/master/website
> Added etherball.net to whitelist

- blacklists/domains.json
https://urlscan.io/result/1898564b-8417-4f51-91a1-98cbd3315c7f#summary
https://urlscan.io/result/1d73dd3c-60a5-4034-bf5c-ce20a81ed0d5#summary
> Adding a few blockchain.info spoofed addresses

- blacklists/domains.json
https://urlscan.io/result/314a4c9b-36b5-47fc-b065-cc11e7158271#summary
> Adding spectre-ai.org (impersonating spectre.ai)

- blacklists/domains.json
https://urlscan.io/result/969adab2-f805-4ab6-b33d-f8e2e3cd65cc#summary
> adding tzero.pw

- blacklists/domains.json
https://urlscan.io/result/70b00db7-8b75-4b50-81b9-cc4c5daf72c6#summary
> adding spectre-ai.net

- blacklists/domains.json
https://urlscan.io/result/3928e538-2061-429a-8111-e59a86975ab1#summary
> adding spectre.site

- blacklists/domains.json
https://urlscan.io/result/acb85963-c149-479a-98f0-340837635646#summary
> adding ico-tzero.com

- blacklists/domains.json
https://urlscan.io/result/0e7e5cb4-03f8-4289-a72e-a271612f29ba#summary
> adding tzero.website

- blacklists/domains.json
https://urlscan.io/result/69bb3460-11f1-4ffc-b7e3-22c190521527#summary
> adding tzero.su

- blacklists/domains.json
https://urlscan.io/result/ac406c92-fbdd-4b01-9063-790f44f76b5e#summary
> adding tzero-ico.com

- blacklists/domains.json
https://urlscan.io/result/fd49ea31-eee5-4691-a553-a0431499d2c2#summary
> adding xn--metherwalet-ns8ez1g.com

- blacklists/domains.json
Illicit site that tries to convince people to deposit bitcoin that it then steals.
> adding bitcoin2x.site

- blacklists/domains.json
https://urlscan.io/result/b8bd6876-a85b-4c98-bed5-f0438d276e87#summary
> addint t0-ico.com

- blacklists/domains.json
https://urlscan.io/result/e5830d20-a33b-464d-b946-2168a7f21170#summary
> adding sirinlabs.website

- blacklists/domains.json
https://urlscan.io/result/0d5493a0-dae4-41f5-91d3-40cc5ed80244#summary
> adding gladius.im (impersonating to gladius.io)

- blacklists/domains.json
https://urlscan.io/result/29662e7b-696c-4e60-8758-ee00116c9e38#summary
> adding t0zero.com

- blacklists/domains.json
https://urlscan.io/result/67aa729b-10fe-4810-b12c-27e44b034943#summary
> adding bitclaive.com

- blacklists/domains.json
https://urlscan.io/result/1198af56-b7b9-47d1-bbcc-4fa0cfb522ce#summary
> add envlon.org

- blacklists/domains.json
https://urlscan.io/result/99ab2aef-e4d8-4934-a576-98438b864c42#summary
> add xn--envon-1sa.org

- js/DomainBlacklist.js
- manifest.json
* Fixes issue that caused myetherwallet.com to be blacklisted due to a race condition when fetching blacklists
> Blacklisting race condition issue

- blacklists/domains.json
https://urlscan.io/result/67b537f3-19c7-405a-84e1-406135d84baa#summary
> Add sirinslabs[.]com

- blacklists/domains.json
as reported by mark / DomainSure Support Team
> add myatherwallet.info

- blacklists/domains.json
as reported by mark / domainsure support team
> add myetharwallet.info

- manifest.json
- options.html
Fixes https://github.com/409H/EtherAddressLookup/issues/225
You can now select testnet explorers for linkified addresses to use.
> Support testnet explorers

- blacklists/domains.json
> add ethclassicwallet.info

- blacklists/domains.json
> Adding ethersecret.com to blacklist. See screenshot.

- blacklists/domains.json
https://urlscan.io/result/3eb0084e-1c8a-4223-8818-8173ee876366#summary
> add envione[.]org

- blacklists/domains.json
> added myetherwallet-kr.com

- blacklists/domains.json
Most of these are dormant, but could be harnessed for an attack. Better to be safe than sorry.
xn--polniex-ex4c.com
IDN homograph attack on poloniex exchange
https://urlscan.io/result/0371ab6b-32ac-47df-abab-21b00af7aec6/#summary
xn--polniex-s1a.com
IDN homograph attack on poloniex exchange
https://urlscan.io/result/b3928990-c29a-428a-93d6-b589759975c1#summary
xn--polonex-ieb.com
IDN homograph attack on poloniex exchange
https://urlscan.io/result/b0b7b657-1412-454e-9af7-3d199997298d#summary
xn--polonex-sza.com
IDN homograph attack on poloniex exchange
https://urlscan.io/result/13d49057-e2c4-419f-b7cc-a040d92f44f8#summary
xn--polonex-zw4c.com
IDN homograph attack on poloniex exchange
https://urlscan.io/result/ef8f2739-f0d1-4d30-ada9-af7c72a127a5#summary
xn--polonix-ws4c.com
IDN homograph …
> Poloniex IDNs

- whitelists/domains.json
Fixes https://github.com/409H/EtherAddressLookup/issues/268
https://urlscan.io/result/5b9f80eb-07db-4335-a764-af837217b020/#summary
> myether.life

- whitelists/domains.json
> Add PolySwarm

- blacklists/domains.json
https://urlscan.io/result/22f09d44-4bb0-47ef-8bda-d5abca427567#summary
https://urlscan.io/result/dd9c3f49-8c46-47e9-9672-b2d733ef1f5b#summary
```
  | <!DOCTYPE html>
-- | --
  | <html >
  | <head>
  | 
  | <meta charset="UTF-8">
  | <meta http-equiv="X-UA-Compatible" content="IE=edge">
  | <meta name="generator" content="Mobirise v4.5.4, mobirise.com">
  | <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
  | <link rel="shortcut icon" href="assets/images/icons8-telegram-app-50-50x50.png" type="image/x-icon">
  | <meta name="description" content="Telegram Open Network PRE-ICO ">
  | <title>Telegram Open Network</title>
  | <link rel="stylesheet" href="assets/web/assets/mobirise-icons/mobirise-icons.css">
  | <link …
```
> token-gram.org

- blacklists/domains.json
I looked into this website and it does not appear to be a real store. They only accept cryptocurrency, do not reply to emails, and their physical location appears to be fake. I have been to this location in Vancouver and have not seen this business.
> add antminers.ca

- blacklists/domains.json
https://urlscan.io/result/07f43b75-6ed6-4c08-a772-857d5698dd37#summary
> Blacklist republicprotocol.eu

- blacklists/domains.json
sent via twitter. URL with dot below m, r, and t
> add "xn--yethewalle-to2exkhi.com",

- blacklists/domains.json
See below links,
https://urlscan.io/result/d7eeb556-5857-4788-b5b3-a49eade03d38#summary
https://imgur.com/a/FPHVb
https://urlscan.io/result/e7059871-8358-4e49-88b6-4a44b3141d93#summary
https://imgur.com/a/KW4YO
> Add dock.so, dock.promo into blacklist

- blacklists/domains.json
See link, https://urlscan.io/result/6b5a0eea-85a2-42b9-8fd7-dd5ad17db618#summary & https://uploads.disquscdn.com/images/65909e243c6e4a224943aa2668bce4b8a22dc7ecbb5b5b245eacc8c90f749499.png
Actual link, https://www.bitcoinsuisse.ch/rightmesh/
> Adding icotoken-current.top into blacklist

- blacklists/domains.json
dock.so
https://urlscan.io/result/76707794-4c54-489d-8a66-0de4f2b8de3c#summary 0x9546748F47a77408dfBFF0DC22505B2e9a75FdA4
dock-ico.site
https://urlscan.io/result/f31bbf71-3b19-4193-844e-7ac5fa73ddc2#summary
https://urlscan.io/result/674abcce-c971-4768-9978-426086de2298#summary
0x0AF16719353EddC122eAf834638406c499197860
tokensale-dock.io
https://urlscan.io/result/b6194fc2-c393-41a1-a6b1-4db57fb54935#summary
https://urlscan.io/result/ab2d1769-013a-47af-b054-d908f02a7741#summary
0x9CdfC5b0ACA4527a0916412E9dbD6AD85556A494
dock.promo
https://urlscan.io/result/25db3dbb-abe5-4d87-a542-b8c68d51119e#summary
https://urlscan.io/result/98f00e98-bea6-40e7-86e0-390d97ad0359#summary
0x0AF16719353EddC122eAf834638406c499197860
dock.su
https://urlscan.io/result/230081ed-1662-4ffb-ad3e-89a19dbdb8d5#summary …
> fake dock crowdsale sites

- blacklists/domains.json
Fake Eos airdrop site - idn homograph attack - links to xn--myetherallt-pl9elw.com
https://urlscan.io/result/e0013795-54cd-4c54-a69c-09666b9ebfd0/#summary
https://urlscan.io/result/03a41315-680a-48f0-9661-4171faf1125e/#summary
> xn--es-8bb.com xn--myetherallt-pl9elw.com + more

- blacklists/domains.json
Fake fintrux crowdsale site
https://urlscan.io/result/10d2302c-037b-438f-b62a-35797537b605/#summary
address 0xcCdf72DE615b5158BB37931BbCE645aa69221520
> fin-trux.com + more

- blacklists/domains.json
Fake Seele crowdsale site
https://urlscan.io/result/66544dbf-abb6-4c99-89d0-cdb9da26329a#summary
https://urlscan.io/result/572b8434-ee3e-4df9-90e0-1ccf172125e3/#summary
address: 0x4bb1c210E3921E0F051ed00e898B9605c902114e
> seele.promo seele-ico.eu seele.ico.pro

- blacklists/domains.json
Fake forkdelta
https://urlscan.io/result/08f0bc02-b72d-4b58-ad9e-1773c1d0fba6#summary
> forkdeita.github.io

- blacklists/domains.json
> polyswarm.in

- blacklists/domains.json
https://urlscan.io/result/0adf53a2-3173-49af-86b2-c5e07b614a9e
> ico-telegram.me + more

- blacklists/domains.json
so many scammers :(
thanks for all the help!
> more PolySwarm scam domains

- blacklists/domains.json
Added mywalletether.com to blacklist.
> Added mywalletether.com to blacklist

- blacklists/domains.json
Potentially fake tefood crowdsale domain
https://urlscan.io/result/7d1d78cb-f911-4039-96a8-9e24dff11194#summary
> ico.tefood.me + more

- blacklists/domains.json
Fake MEW
https://urlscan.io/result/05aedda9-7f73-474e-95b1-a12e3acbd073#summary
> myetherwallet.usermd.net + more

- blacklists/domains.json
Fake tomo crowdsale site
https://urlscan.io/result/fb0aedfd-7ce2-4548-a08b-82adb1b49224#summary
https://urlscan.io/result/c970fc6a-ab2f-4fa8-8bfa-4702998d1993#summary
address: 0x878cce43a3b9d8A872a33d2d6CCD561E033707f4
> tomo-coin.io + more

- blacklists/domains.json
Poloniex idn homograph attack domain
https://urlscan.io/result/d1adb71a-4775-402d-81bc-df500edb424a#summary
> xn--plniex-bxab.com + more exchange idn homograph attack domains

- blacklists/domains.json
See link, https://urlscan.io/result/68e2e839-0cd6-4d93-8e4b-e64ccdefc470#summary
> Adding masanchez.usermd.net into blacklist

- blacklists/domains.json
https://urlscan.io/result/b53655c1-17a4-4bef-a624-dec2e5f7425b#summary
> callisto-airdrop.com + xn--thabyss-u8a.com

- blacklists/domains.json
See link, https://urlscan.io/result/15a326ce-7583-4f5c-a2de-9c42e650c104#summary
> Adding changlley.org into blacklist

- blacklists/domains.json
Fake policypal network crowdsale site (currently suspended)
https://urlscan.io/result/2fab4de0-80ca-4563-8d32-79b29b0af6c7#summary
suspected addres: 0x2b3F15a55a68C4C81ae8331C2FE8E90008993f51
> policypal.info + more

- blacklists/domains.json
Hosting a trust-trading scam
https://urlscan.io/result/e436ea08-a502-46da-93fa-a6d531082c70#summary
address: 0xb82bFd79d5A8C0cc0d4C045633288b48A2beDdcB
> eth.secure-transactionssecure.com + more

- blacklists/domains.json
https://urlscan.io/result/fde0796f-d022-42ed-b242-5cfbcf2f6875#summary
https://urlscan.io/result/952b9cfc-437d-4ed4-9019-3eb91b31f113#summary
https://urlscan.io/result/6fca8b34-b7fd-4cd1-8db7-b34a555a4612#summary
> data-token.org + more

- blacklists/domains.json
Fake Telegram ICO site
https://urlscan.io/result/2d149af8-a46e-4eb2-90c2-b31d42daf17f#summary
https://urlscan.io/result/f3f4f8f1-94ce-4672-a323-4382fe2c5229/#summary
> telegram.auction + more

- blacklists/domains.json
https://urlscan.io/result/5cf69c58-25f9-4eff-b63b-067e141ba8aa#summary
address:  0xD43F2111e4055120196285eC094aA6e96998668b
> binance.bitballoon.com + more

- blacklists/domains.json
https://urlscan.io/result/054bf78d-9896-4be1-b698-485e17901ef5#summary
https://urlscan.io/result/241fee89-267c-4bc1-8158-813d635604ec#summary
suspected address: 0xfe821f5509fdea3f72362d001697ad8c11f0c111
> gram.vc + more

- blacklists/domains.json
Fake COSS site
https://urlscan.io/result/1f62246a-77eb-4a64-9db6-65480f615381#summary
> cosss.io + more

- blacklists/domains.json
Trust trading site
https://urlscan.io/result/96b871fd-ff91-49ee-9270-3546b7fe03eb#summary
address: 0x5F58fE612DB5B3E97FAf4A2E8f38B4AE295288Aa
> telegra.ph + more

- blacklists/domains.json
Coinbase IDN homograph attack
https://urlscan.io/result/7657eb26-9f9e-45ea-958c-2e0b8f9bd8e6#summary
> xn--coindes-jhb.com + more

- blacklists/domains.json
Communicating private keys to a remote server
https://urlscan.io/result/cea0dc1a-2d75-4993-af39-56fe4629b610#summary
> tokensale.syncfab.eu

- blacklists/domains.json
https://urlscan.io/result/ee62040a-cb06-4d67-a485-fd5f4b45d9fc#summary
address:  0xD33441A44Da0c1DCEE596aBB7ebDCdBa77c7DDBd
> eth-giveaway.info + more

- blacklists/domains.json
See link, https://urlscan.io/result/6731a5d1-581e-4647-9fcd-82a1846804e7#summary
> Adding etherscanio.github.io into blacklist

- blacklists/domains.json
See link, https://urlscan.io/result/b57fddc7-4d7f-42ed-84e8-c376239e9aa0#summary
> Add ethfreecandy.bitballoon.com into blacklist

- blacklists/domains.json
See link, https://urlscan.io/result/8837fa9b-5b9a-4f8a-bff3-559df76ac131#summary.
> Adding otoeveryday.info into blacklist

- blacklists/domains.json
https://urlscan.io/result/f6214510-389b-4c77-898b-bc376452c2b9#summary
address: 0x6067A95E7Bb071A5b73741628A0A5Cb5cC164203
> eth-transaction.secure.kissr.com + more

- blacklists/domains.json
Fake Celsius network crowdsale site
https://urlscan.io/result/aa804db3-af08-4bb8-97b9-ad5722b2cdfb#summary
> celsiuss.network + ethereumtrans.com

- blacklists/domains.json
https://urlscan.io/result/f84a57ba-66ab-4060-bcdc-157915f4e2c8#summary
address: 0x47fEa7bB88BECA144E82Ce96A20A25A0974BA6Ba
> ethfreeget.com + more

- blacklists/domains.json
https://urlscan.io/result/df098457-a0e8-40c5-a77f-21916546c2f2#summary
address; 0xfF2f6c6fbd71a078f1C1781855467D30897b5a33
> eth.hn + more

- blacklists/uri.json
Another google form collecting email addresses and promising free tokens.
> Salt Lending Airdrop Phishing Page

- blacklists/domains.json
https://urlscan.io/result/72e56803-8480-4fb3-8255-24d92efc504d#summary
address: 0xd11d565Ba23b523ef7737AA24BdbB75a06521d87
> ethgive.github.io + more

- blacklists/domains.json
https://urlscan.io/result/4bd6b891-35da-465a-8543-196d15ccc626#summary
address: 0x303345349Da72a28D12d5515F145dD77cB84BACC
> etherfreegive.com

- blacklists/domains.json
https://urlscan.io/result/592848b4-8b04-46cf-bc51-8c97e14832f5#summary
address: 0x14258A5ddCad7001e8ac89B539df7E0f08A34500
> eth-promo.com

- blacklists/domains.json
https://urlscan.io/result/f5df1ffa-90b7-4602-875b-d9c862950dd9#summary
address; 0xe00e1f7117a69c34694ac1815177c93491fc448f
> eth-giveaway-vote.bitballoon.com + more

- blacklists/domains.json
Another Salt phishing page with fake desktop app download. Confirmed as malware: https://www.virustotal.com/#/file/a5637f7df2bf64a99998feb7ec28cc9c165c5677332ca7e056718a507e2f118c/detection
> top-mining.pro

- blacklists/domains.json
https://urlscan.io/result/64af7fed-9e65-4b45-a15c-857f627b87d3#summary
address: 0xBa25FEffe57126B503C2A313D928ee99E25884b6
> eth.altervista.org

- blacklists/domains.json
Fake Galaxy Esolutions crowdsale site
https://urlscan.io/result/fe543f0d-add1-44a7-b45b-60fd7fa9967d#summary
address: 0x687aE5Cc3978BC07dB0B7f4D76FbAde966cf4Ba8
> galaxy-es0lutions.com + more

- blacklists/domains.json
See: https://urlscan.io/result/7205ad8f-8e61-4fd2-bc29-1d12a38d3724#summary
> Add geth.cc into blacklist

- blacklists/domains.json
Fake coti crowdsale site
https://urlscan.io/result/8ac90292-fbdc-46b2-9f46-a2aed1ef1dca#summary
https://urlscan.io/result/3526ca43-aa5e-4177-b508-29f5b84229b1#summary
> coti.cf + more

- blacklists/domains.json
See link, http://telegra.ph/VTSR-is-giving-away-5000-Ethereum-ETH-03-13-4 & https://urlscan.io/result/26a6b4db-ccfe-4bcd-8621-c65b594f2893#summary.
> Adding html.house into blacklist

- blacklists/domains.json
https://urlscan.io/result/435dcc1a-235f-4d60-802b-577060b60a08#summary
address: 0x3219eBDcBC9F79f59c8C53105f3E74E0289F3Ea9
> coin-promos.com + ethpayment.bitballoon.com

- blacklists/domains.json
Fake Metronome crowdsale site
https://urlscan.io/result/57828914-dc4b-4e6f-b661-49f10429a055#summary
address: 0x092A334eA43C0512560f6acF301FA97805cab392
> metronome-token.io + i-myetherwalnet.com

- blacklists/domains.json
https://urlscan.io/result/31ac05e3-44d4-4ee4-9e21-8ad4425f6d24#summary
address: 0x62c71581708dD73b10e7aa2249778AEe016eBF0e
> ethpayd.com + more

- blacklists/domains.json
Fake Binance
https://urlscan.io/result/f0af9ec0-c836-4082-a5db-9e106a64ec9f#summary
> binancce.ml + more

- blacklists/domains.json
Scam claiming 10x returns on eth deposits, currently using twitter and facebook to promote by impersonating various companies.
> eth-transaction.site44.com

- blacklists/domains.json
Fake MEW
https://urlscan.io/result/8f9e2bdb-698a-4314-b2b7-cd1f4c74f48e/#summary
Fixes https://github.com/409H/EtherAddressLookup/issues/396
> nnyiictehervvailiatt.com + more

- blacklists/domains.json
Gas phishing site - "generates" coins but asking for gas money
https://urlscan.io/result/8d094bfd-6583-4336-85df-1a2d4f4baf7b#summary
https://urlscan.io/result/623e3078-402d-4684-a544-d21f7ddb995c#summary
https://urlscan.io/result/c2fe4ad5-f038-41f8-b03e-8c014b6b5700#summary
address: 
0xaAc6020b6216BE72Af7B3c322dd27cea257276b3
0x94D50168D9Bc80cc39AFFbcBA8232AcD89F117A3
0xaAc6020b6216BE72Af7B3c322dd27cea257276b3
0x94D50168D9Bc80cc39AFFbcBA8232AcD89F117A3
0xf3A6F2796d5B16F658431bD7A19087A37eA9fAfb
0x94D50168D9Bc80cc39AFFbcBA8232AcD89F117A3
0x94D50168D9Bc80cc39AFFbcBA8232AcD89F117A3
0xf3A6F2796d5B16F658431bD7A19087A37eA9fAfb
0xf3A6F2796d5B16F658431bD7A19087A37eA9fAfb
0xf3A6F2796d5B16F658431bD7A19087A37eA9fAfb
0x94D50168D9Bc80cc39AFFbcBA8232AcD89F117A3
> coinmakerbot.com

- blacklists/domains.json
Fake Auctus site
https://urlscan.io/result/34f3983d-a4b4-4639-93de-bf803d4ea541#summary
https://urlscan.io/result/5983c240-240e-4dc6-b0e0-54178ce38102#summary
https://urlscan.io/result/3bdf9c50-1194-45d3-8ef3-8f4b3630ad91#summary
address: 0x8E3e1e3894CD4e79f46f80d4807b597876435978
> xn--aucts-1gb.org + more

- blacklists/domains.json
https://urlscan.io/result/f62c67f1-31b6-4c64-9105-932e32d963fa#summary
address: 0x474057ADF42f9F955e86aa1142740f9d7763e41E
> tronfoundation.me + more

- blacklists/domains.json
Fake MEW
https://urlscan.io/result/475842ba-d15c-4de7-a40a-40b9b7f5ff97#summary
> nnyiicteherwailiatt.com + nnyecthenwellat.com

- blacklists/domains.json
https://urlscan.io/result/b6789a6b-acb2-4cd8-bf5f-649b15af8e75#summary
address:  0x679C34C26E7841b9Fc0ce0ff40579219EE3a1ED6
> ethr.cc + more

- blacklists/domains.json
https://urlscan.io/result/dca8e52f-b6cc-4cfe-9f79-92b6f4c9eeca#summary
address: 0x5dfAE1C25EC5232F1D725d5265ceDDD7102BE5B4
> ethgiveaway.club + more

- blacklists/domains.json
https://urlscan.io/result/2bc3d357-ad2c-4577-b06e-7c8348f5daf3#summary
https://urlscan.io/result/dd01b145-5b97-428f-9c11-ba741fa37595#summary
https://urlscan.io/result/9704ce2b-25d7-4430-a337-51fcd449d8f5#summary
> kinecosystem.net + more

- blacklists/domains.json
Fake MEW
https://urlscan.io/result/97ec356d-e13d-4590-bf78-cb2fa7d0d7d5/#summary
> myetnarvellat.com + more

- blacklists/domains.json
https://urlscan.io/result/7502848b-37ca-4f4c-9747-e068e48dbf50#summary
https://urlscan.io/result/13f82373-e265-41fc-813f-3712c9b744e3#summary
address: 0x049b01966f721db6EC76097043e9D6ecCaF719B6
> cz-binance.com

- blacklists/domains.json
See link, https://urlscan.io/result/f7d51dfc-6faa-4672-8aef-d33c5c451ff5#summary.
> Add get-eth.pl into blacklist

- blacklists/domains.json
See link, https://urlscan.io/result/98942cde-5c32-4521-a2f8-21bad9781230#summary.
> Adding myetḣerẇallet.com into blacklist

- blacklists/domains.json
See link, https://urlscan.io/result/e12a5154-34a4-49f2-a1d4-8692aa071caf#summary.
> Adding eth.vu into blacklist

- blacklists/domains.json
See link, https://urlscan.io/result/e706e8a0-f0ad-48b4-9d6c-0e37c08fd04e#summary and https://urlscan.io/result/18130772-aae7-4f83-8a88-16f6c92d51fd#summary
> Adding safely-transfer.com into blacklist

- blacklists/domains.json
https://urlscan.io/result/bc1a39c6-b716-4e8c-b0cf-f9063ac08bb6#summary
> airdrop-bluzelle.com + more

- blacklists/domains.json
https://urlscan.io/result/bf7ca916-fdfd-418c-b5f7-f5492aac0321#summary
address: 0x8A04B6a0223aF79e4aCC0a55c7B166Fe0794269a
> payforfees.online

- blacklists/domains.json
Fake dfinity crowdsale site
https://urlscan.io/result/14a14d73-abda-4b6a-b581-fe126f7163e0#summary
https://urlscan.io/result/4558ccba-b754-46d7-8c64-2c2ee4db552e#summary
address:  0xA95391C51788f884BECA472bf71Cdb000a2eEd65
> dfinity.org.in

- blacklists/domains.json
Fake MEW
https://urlscan.io/result/dfafd569-2283-4f8c-8d03-65a5f89de92a#summary
> myegethercowwallet.com + more

- blacklists/domains.json
See link, https://urlscan.io/result/0ae33a05-602f-4da4-af04-16f0377767b0#summary & https://drive.google.com/file/d/1pWl2Avd7izdnloInPRBOBYvhmL8kJpAh/view.
> Adding etherpromo.online into blacklist

- blacklists/domains.json
Fake Dfinity crowdsale site
https://urlscan.io/result/a702a5d8-5c24-4904-8b5d-84592936bc3c#summary
https://urlscan.io/result/6508df53-ca90-443d-a02b-7a92d39de2b9#summary
address: 0x79aA79116c24A715b5eb1287AF8A16201450C895
> tokenpublicsale.com + more

- blacklists/domains.json
https://urlscan.io/result/970dbe89-c27e-4b8d-96b7-d1df54782dff#summary
address: 0x83ec306df6BEe5320cF6a57A52ff732791c65B47
> ethereum-promo2018.bitballoon.com

- blacklists/domains.json
https://urlscan.io/result/fcdabb83-829c-4423-9a8d-f27d65f5b8d6#summary
address: 0x83ec306df6BEe5320cF6a57A52ff732791c65B47
> ethereums-promo.bitballoon.com

- blacklists/domains.json
Fake Telegram ICO
https://urlscan.io/result/e313730b-056e-4f57-81b6-4632ba21d891#summary
address: 0xdDb690eF629a2e9277808c25EB5f9259d939Da
> gramtokenico.com

- blacklists/domains.json
Fake CTR refund page 
https://urlscan.io/result/b7d81b16-b2e3-45ec-b521-e7fef6ce0dc0#summary
https://urlscan.io/result/e4ba38c3-b4cf-4dc7-8b1f-3eb42087c391#summary
address: 0x87b4eed5a781d8b847645082410070f002b41e13
> centratoken.site

- blacklists/uri.json
See link, https://urlscan.io/result/d45d092f-7e1c-4362-8108-55748d115a9e#summary
> Adding telegra.ph/Coinbase-1000-ETH-Giveaway-03-25 into blaclist

- blacklists/domains.json
See link, https://urlscan.io/result/af43a0b4-5c05-4774-9017-5fbc9546a42f#summary.
> Adding check-ethpayments.kissr.com into blacklist

- blacklists/domains.json
Twitter phishing claiming 10x returns when sending to address, copy of etherscan site.
> etherscan.online

- blacklists/domains.json
https://urlscan.io/result/3ec2f1bb-009d-49ff-b889-e6f2785962ed#summary
address; 0x474057ADF42f9F955e86aa1142740f9d7763e41E
> tronfoundation.us + more

- blacklists/domains.json
Twitter phishing, claiming ether giveaway.
> free-5000eth.com

- blacklists/domains.json
https://urlscan.io/result/02367f87-57e6-47fe-b7b9-4a62f76b8bf5#summary
https://urlscan.io/result/37cf1270-8cae-4b38-85cd-3f3dca2435c2#summary
address: 0x319Ce3233D17b45d49AAa9414F154832d0F9Aa61
> ethhit.com + ethereumpromo.info

- blacklists/domains.json
Hosting fake ICO sites as subdomains
https://urlscan.io/result/8f171e6b-7227-43ed-bbfc-820b6dc67ced#summary
> tokencrowdsale.info + hederahashgraph.tokencrowdsale.info

- blacklists/domains.json
https://urlscan.io/result/726b3b82-649e-4d00-bf95-05ac0917abae#summary
address: 0xe00e1f7117a69C34694ac1815177C93491fC448f
> eth-give-away.webz.cz + more

- blacklists/domains.json
https://urlscan.io/result/41f7b19b-20f7-4474-9293-fcfa4c8f5da1#summary
https://urlscan.io/result/7eae2ecb-148a-4273-978f-0d3fb8f70015#summary
address; 0x8c155c3F4c79485DBB0eEF5b4076FD426b3f8c65
> eth-giveaway.trade

- blacklists/domains.json
Article and links pushed via a fake BBC news article and site.
https://urlscan.io/result/a27f3efe-5ce6-4fd9-a66a-61799eaa3cbd#summary
https://urlscan.io/result/7c058395-c892-4f7f-9e39-3d47e3ac284d#summary
https://twitter.com/sniko_/status/984030320642154497
> smartolinks.com livivid.com clickmoneysystem1.com + more

- blacklists/domains.json
> neonexchange fake tokensale

- blacklists/domains.json
See link, https://urlscan.io/result/b9d3fd76-444c-4ffd-8d2b-2c972103a10c and https://twitter.com/dafdith/with_replies.
> Adding givingawayeth.com into blacklist

- blacklists/domains.json
https://urlscan.io/result/ab3d5a44-8da6-42d1-9f70-5b4565b5ff5c
address: 0x0E0bA79CB92E07555eF7A3fe9e18BA33dd0b6D29
> ethereums-2018-give-away.bitballoon.com + more

- blacklists/domains.json
> ethereum-giveaway.tekcities.com

- blacklists/domains.json
https://urlscan.io/result/70fdd179-ba44-40cb-82d5-48268eaf7009
address: 0xEB85b4777698c0f41168087cD8d43A2FdEF37BdB
> gether.fund + more

- blacklists/domains.json
Fake coinbase phishing for login details
https://urlscan.io/result/b385775f-1b25-4183-8e02-141d1a6dcd2c
> xn--conbas-gva1a.com

- blacklists/domains.json
https://urlscan.io/result/12871b50-11a7-43ab-9242-0a797f34182b
Address: 0xf605c1C8c1CD6Bc3AA6f7383b86226c583Ab2775
> eth-giving.com + more

- blacklists/domains.json
Fake MEW
https://urlscan.io/result/aaaf119f-625c-4e1e-adb8-09bf366e9b7a
> myetherwatllet.com

- blacklists/domains.json
https://urlscan.io/result/34241a15-4f42-486f-8089-6103a789c63b
address: 0x713a6f26525B24581Cbe20679811af8680abdddd
> btc-gifts.info + eth-promotion.getforge.io

- blacklists/domains.json
https://urlscan.io/result/8fca9e93-8b55-4b0e-8ba3-c98d3a3216c8
https://urlscan.io/result/4bdbd16e-32d5-418f-8034-9259fb28910d
address: 0x6c20ef21e604028c649247c581e8e49fda6191ca
> tokentelegram.net

- blacklists/domains.json
https://urlscan.io/result/7aa2c4eb-6389-478c-9c8a-d10bb2b072bd
Address:  0xa4Fe2874A4aD464A50CB72a8C0b1a6ab221A7C17
> ethtotrade.com + more

- blacklists/domains.json
Fake Etherscan
https://urlscan.io/result/5db6c3c6-10d3-4fa5-aede-2ab8ac9819a5
> etherscan.tech

- blacklists/domains.json
https://urlscan.io/result/0107c444-3c6b-47fc-b6bd-bb2b9c519036/
> neonexchange.website

- blacklists/domains.json
myetherwalletru.com
https://urlscan.io/result/3c1f52ac-3538-44e1-ade2-d357d9c8e4f5/
i-myetherwallet.com
https://urlscan.io/result/67f1e3f3-6092-48ec-8e06-c216fae8f7aa/
> Fake MyEtherWallets

- blacklists/domains.json
Fake MEW - IDN homograph attack
https://urlscan.io/result/a51ae0a7-a97b-4ea0-b239-a5330acad9b2
> xn--myethewllet-w48ep6a.com

- blacklists/domains.json
https://urlscan.io/result/0b3eeb18-4cf4-412c-abba-d3aa4dbf235f/#summary
address: 0xEF35af4A5037a1E416514f1F016550cf7c865ffc
> ethhit.org + more

- blacklists/domains.json
Fake Dfinity crowdsale site
https://urlscan.io/result/eb2f363b-3f69-4939-97cf-34db99928305/
> dfnity.org + aelftoken.com

- blacklists/domains.json
https://urlscan.io/result/9c539445-345d-4ff6-b709-dd382def0928
address: 0xceEbB2D0cDC85E9774A232Bab74C45Fc883C15e4
> give5000-eth.com + more

- blacklists/domains.json
Fake MyCrypto - IDN homograph attack
https://urlscan.io/result/9cab0725-3aa6-4e95-9673-002607195d8d
> xn--mcrypto-rpd.com + more

- blacklists/domains.json
https://urlscan.io/result/1b37831a-6968-4c4c-8a7c-9f6a63f22b63
address: 0x9C3C750372e2DBC2f8f2E6C58EdFA6E1d7e463Fd
> ethereumpomo.online

- blacklists/domains.json
https://urlscan.io/result/53891b6d-3d13-4416-82c2-cf52cc768908
address: 0x2e462fDeF8cde7DB82Aa3f7C627731BE94f7C9C4
> ethforeth.com + more

- blacklists/domains.json
Fake MEW
https://urlscan.io/result/7a97cc3e-b644-4fed-8b13-8235957f092b
> nmyetlerwaliet.com + more

- blacklists/domains.json
https://urlscan.io/result/e077a146-2adc-4695-95fd-f13c02edb396
address: 0xEbD411aA59B4456f45529A7Cc203F87c0e104947
> gether-gift.com

- blacklists/domains.json
https://urlscan.io/result/8b94ca02-1b2b-4162-95d3-8fd881b1fa51
address: 0xf033f0d9c1bf050babe586fddd94d8928f02ac50
> ethpromoverge.com

- blacklists/domains.json
Fake Shapeshift site, iframe 188.227.75.205
https://urlscan.io/result/74abc7cf-fed6-4d4b-9a4f-e99989660a22/
> shapeskift.io + shapeslhift.io

- blacklists/domains.json
https://urlscan.io/result/8897f2d0-9c98-4dff-80df-51f11f21c281
address: 0x61Cf3335eef3bD86Ae617cd2eA248494Da8B83ca
> 5000eth-giveaway.getforge.io + get5000eth.com

- blacklists/domains.json
https://urlscan.io/result/bac7ede1-59e0-4084-af0f-2bc5084d961d
address: 0x88bDEB65eD500794118D0E5FDf5808d23Bb74E73
> ethgiveaway.org + more

- blacklists/domains.json
https://urlscan.io/result/fd28d261-f517-42b3-a574-6ccec34f40cb
address: 0x91459992BcbF089851abFfa033559C2eEf120469
> getyoureth.com

- blacklists/domains.json
Fake MEW
https://urlscan.io/result/a873a53d-1acb-41a1-9c49-68dca02bd848
> nmyetlerwaiiet.com + more

- blacklists/domains.json
https://urlscan.io/result/b4fe2b60-87b2-45e5-9ca5-db11bda9a1dc
address: 0xF939D9285fFb6FC05780E9549b161d9e9fac6F7d
> get-ethereum.cc + freecoiners.com

- blacklists/domains.json
Fake MEW serving under a Google ad
https://urlscan.io/result/5aff89d6-024c-4b3b-a1dc-6b12d8509e5d
> myehterwallet-ht.com + more

- blacklists/domains.json
Some of the same team as goldexapp.com - reported as a fake by that team
https://urlscan.io/result/163ef675-ce62-47a6-9b80-dc9a5de67c9c/
https://urlscan.io/result/135f73de-7e9d-4d97-8b53-300fb46e192f
> goldexchanges.io + more

- blacklists/domains.json
https://urlscan.io/result/9230e776-3afa-4a5f-99c4-de50eef43b4d
address: 0xB5eb9d18C0413535bAf1fA8Bd8BF8F6Ea7fEa47A
> gift-5000eth.com + more

- blacklists/domains.json
Fake LocalEthereum phishing for logins
https://urlscan.io/result/257a1f59-38be-498f-9876-4efc6692ea74
> localetherieum.com

- blacklists/domains.json
See link, https://urlscan.io/result/33b1d6eb-49ec-4361-874d-a812d58eb584.
> Adding polymath-network.com into blacklist

- blacklists/domains.json
See link, https://urlscan.io/result/a2bf6eb3-1a12-4ceb-a8d9-9896a0a000c7
> Adding eth.mom into blacklist

- blacklists/domains.json
https://urlscan.io/result/ea6098ae-8619-43d3-bf50-7085c355fe28
address: 0xf7355cb5278fc4be2f53ce373f7cd9b543d042a1
> 5000eth-giveaway.com + ethereum-give.czweb.org

- blacklists/domains.json
https://urlscan.io/result/7fc9102d-ef47-42f1-9796-96a109a128e3
address: 0x018f2f4b3C9e38607aa7AB4DEA23E9d663e3e050
> 5000eth-gift.com + letherwindows.com

- blacklists/domains.json
https://urlscan.io/result/bf95bc60-1729-4808-aecd-18cc982eaad2
https://urlscan.io/result/976b36c1-9d33-4d41-b855-0142242b7de7
address: 0x6c20ef21e604028c649247c581e8e49fda6191ca
> tokentelegram.info + more

- blacklists/domains.json
https://urlscan.io/result/1953bc55-95c5-4d9c-a03a-74c99eb7b035
address: 0x085f9b53aCBff0E4683463FEf1A583d299bd4e25
> ethereums.cloud + more

- blacklists/domains.json
https://urlscan.io/result/77e475da-90a3-4c30-8feb-146c4000a53a
https://urlscan.io/result/fe48c28d-56cb-4f3f-ab6c-dbdb428c9642
address: 0x6D09D33C424932f59Ce9aa777aDf131FB3adbf3E
> quarkchain-tokensale.io

- blacklists/domains.json
Fake MyMonero site
https://urlscan.io/result/fafaadb2-fcad-45ef-9b6e-024c1cf957c9
> mvmonero.co + 5000ethgift.com 

- blacklists/domains.json
https://urlscan.io/result/03faa644-1189-44a5-9059-480f0b18bef7/
Suspected address: 0x7d66c5111f9369B1b7Ecc2B80E97Dc98585344bd
> gram-token-sale.com + more

- blacklists/domains.json
https://urlscan.io/result/59c81f8c-8521-4509-a12a-5b4e1240c9a9
address: 0x418Cb18A725A8B1043D2fB402bb71CC29E42e2E9
> collecteth.com + more

- blacklists/domains.json
https://urlscan.io/result/a53d0192-8688-4536-b2e1-21d903a6e651
https://urlscan.io/result/7dfcefc4-26d4-455b-8277-5ca0aa3d7459
address: 0xa0C7d4F3FC7f8A46FB58990228d0B82A0354F371
> ethereumdrop.batcave.net + etherdrops.co

- blacklists/domains.json
https://urlscan.io/result/520a3200-2683-446d-a3b6-0766704f57e2
address: 0x4FbC4C6C416a84e04B2239202396f378d7Af51ee
> geteths.live + more

- blacklists/domains.json
https://urlscan.io/result/bec556da-d5b2-47dc-9847-40039be26449
address: 0x95C5dB5bD9A0260Fc457Af4F6fc6dE7819D9B1a6
> ethgiveaways.net + more

- blacklists/domains.json
https://urlscan.io/result/c53888fe-ee0e-4d14-9a57-7b56c9384625/
> meythcrrwallet.ru.com + more

- blacklists/domains.json
Fake Tron airdrop phishing for private keys
https://urlscan.io/result/47ba4f04-4a91-481a-9cdb-c4c2b45349a0
https://urlscan.io/result/ffca6bfe-603b-4968-8cc8-b3a20f891134
https://urlscan.io/result/db2de8e4-a1f6-49e0-b3ca-3bba2085bc03
> tronlabsnetwork.com + more

- blacklists/domains.json
Fake Hederahashgraph crowdsale site
https://urlscan.io/result/d1a301f1-57c0-466e-83a7-0149b7f32aa9
https://urlscan.io/result/baab3ea5-9c08-4a7b-80a0-8caf226c3c90
address: 0x2d301d74a8d303da6408Cc2dFDA319BbEb48c125
> hederahashgraph.store + more

- blacklists/domains.json
payments.payeths.com
https://urlscan.io/result/4031a1cf-1233-4e2b-aa8d-f6f3e2f3329f/
address: 0xb48c99C37b7cf4AC0A1c2dcA518782C1FEB4f066
> payments.payeths.com

- blacklists/domains.json
quarkchain.website
https://urlscan.io/result/5216d67c-bba3-46b3-835b-7e86e60307fc/
https://urlscan.io/result/904435a0-bbb9-4a1b-a296-5d39c48024fb/
address:  0xB9Ee29FF43D319c126ED2Dbdd74d49a2659EDe56
quarkchaln.io
Suspicious quarkchain crowdsale domain
https://urlscan.io/result/e470a4c6-ac47-4aec-acaa-14330637e7d9/
quarkchain.org
Suspicious quarkchain crowdsale domain
https://urlscan.io/result/cb7b3e7c-3aff-4808-a497-459ce6654b66/
quark-chain.io
https://urlscan.io/result/473cb4d9-849e-4eff-83a9-c64cc66fcd03/
https://urlscan.io/result/ef143090-8f61-4b5f-98c8-8d681972938c/
address:  0xbEaaD836E717Dd22f59752d60223971db197EF4E
> quarkchain.website + more

- blacklists/domains.json
kinecosystem.io
Fake Kin airdrop phishing for private keys
https://urlscan.io/result/07096412-56d6-45dd-a90c-4928c19be3ce/
https://urlscan.io/result/15b872c4-a369-4954-ba33-5a3f661030ba/
https://urlscan.io/result/27b35185-63dc-43a6-95a6-2f3dda5d610d/
https://urlscan.io/result/765af8ce-e1c3-4a85-bb80-d6c5a949a5dd/
> kinecosystem.io

- blacklists/domains.json
collect.ethforyou.com
https://urlscan.io/result/42cae236-4989-4519-a379-5c5352e4c75c
https://urlscan.io/result/c16c7de9-8124-46e3-962f-e70a82772da9
address: 0x3EadB407F81d62D27F63a8881805B1735F70E692
getmyetho.paperplane.io
https://urlscan.io/result/c49b6a1b-d1a8-4d69-9b31-da5341bb3a0c
address: 0x35919ff0a88A0bDFd1b0EF3be574bcF6C1e90e01
brickblockio.info
Fake Brickblock crowdsale site
https://urlscan.io/result/dcfa27a5-4da8-4df7-a648-19339aa8489e/
address: 0xe949A4c861089fBdE6eF1175C23E1485D5970567
> collect.ethforyou.com + more

- blacklists/domains.json
xn--mytherwallet-5vb.net
https://urlscan.io/result/438ede62-8084-45ae-8ba0-f7a903b064a1
i-dexmarket.com
Fake IdexMarket site stealing keys with POST save.php
https://urlscan.io/result/4931c135-5f4c-4fd8-b605-87e7ea86075f
bi-ttrex.com
Fake Bittrex
https://urlscan.io/result/c9a1ded3-a566-4446-b5f7-0fe293bbed0f
www-bittrex.com
Fake Bittrex
https://urlscan.io/result/c2ea4b8a-e18a-496c-b5a5-6c794eb68c57
https://urlscan.io/result/a7649a0d-0b90-47b8-ac1a-df40f72b6f24
> xn--mytherwallet-5vb.net + more

- blacklists/domains.json
quarkchain.live
https://urlscan.io/result/56a45362-3fe9-4d1c-8445-ba9184aa8890/
https://urlscan.io/result/25b5d373-a6e6-4d8d-a6b8-902a12908b12/
address: 0x0a888f0F0b772e17a2ADFd62D3f15CeC72c8D42f
> quarkchain.live

- blacklists/domains.json
See link, https://urlscan.io/result/be714fe2-34d1-4d0e-b38c-bd05ac7865d8.
> Adding omisegowallet.network into blacklist

- blacklists/domains.json
See link, https://urlscan.io/result/2dbe2ff6-c75c-46c4-953a-8b7f19443a9f.
> Adding musk.vu into blacklist

- blacklists/domains.json
See link, https://urlscan.io/result/62ccdbe4-08f5-43c8-98f7-016bc538bc27.
> Adding ethairdrop.live into blacklist

- blacklists/domains.json
See link, https://urlscan.io/result/79c08d3a-8a47-49ae-bb4a-738cfb9b3b87.
> Adding ethsgive.com into blacklist

- blacklists/domains.json
ethersforme.net
Hosting trust-trading scam sites
https://urlscan.io/result/036cff71-ddd1-4ba5-8ee9-e8268da2f624/
giftethers.com
Hosting trust-trading scam sites
https://urlscan.io/result/7737e929-ae2f-41f2-ae68-90fd59a54387/
m342edium.ethersforme.net
https://urlscan.io/result/c87f1e4e-857d-4dfa-a720-7e17e1c12ee1/
address: 0x40949225c4a1745a9946F6AAf763241c082cb9ac
10000-eth.com
https://urlscan.io/result/7923173e-0dba-4da1-a991-d8eaea193c81/
address: 0x24F7ea54D9CDb021C0788Caab3c1796Aa8b2C161
icostarex.mipropia.com
Trust-trading scam site (btc) - address: 19zfbrhYeFVDcCrDsdpKj3WGCD6KvJbzt7
https://urlscan.io/result/0e615e1d-2b7e-44ee-8e59-ad1998d2eeb2
ethsgive.com …
> ethersforme.net + more

- blacklists/domains.json
promo-eths.com
https://urlscan.io/result/895064e4-f592-4699-b014-a2ae51e8ced1
address:  0x24F7ea54D9CDb021C0788Caab3c1796Aa8b2C161
nathanielpopper.promo-eths.com
https://urlscan.io/result/d80f52a8-c689-4e8a-ac30-541d686a74a0
address:  0x24F7ea54D9CDb021C0788Caab3c1796Aa8b2C161
> nathanielpopper.promo-eths.com + promo-eths.com

- blacklists/domains.json
walleteos.org
Fake web wallet phishing for keys (sending to POST test.php)
https://urlscan.io/result/9e7c9e56-7075-4f9f-9c81-9b0965e41439
> walleteos.org

- blacklists/domains.json
biitbay.com
Fake BitBay phishing for logins
https://urlscan.io/result/3ec3a21c-2cba-4f5f-b958-993a57f2f92f/
https://urlscan.io/result/41d9ef68-c211-46dc-bb09-17b3573dcfef/
kcucoin.com
Fake Kucoin phishing for logins
https://urlscan.io/result/115e223c-93dc-4b3f-a100-1b62432c0e15/
https://urlscan.io/result/47115a44-ddca-4c30-b823-c5b48d2f9303/
vvallbtc.com
Fake Wallbtc site phishing for logins
https://urlscan.io/result/46ab3f47-41a9-4771-a781-ee13cc29625b/
> biitbay.com + more

- blacklists/domains.json
bittrex-login.com
Fake Bittrex site phishing for logins
https://urlscan.io/result/09b21ddd-892c-4adc-a564-b5ea281e6631/
https://urlscan.io/result/dd130cbe-bb5c-410e-9442-d1726d81a9a9/
bittrexr.com
Suspect Bittrex domain - could be phishing
https://urlscan.io/result/13f9bdaa-82be-459b-9cac-5ba59bc09877/
bittrexa.com
Fake Bittrex site phishing for logins
https://urlscan.io/result/560071bb-dc9e-4464-b5ff-11864b09011e/
https://urlscan.io/result/d6f36ac1-1c28-4d43-9fb8-6aa3da7e6b3a/
xn--bttrx-7ra5a.com
Fake Bittrex site phishing for logins
https://urlscan.io/result/ed359b37-8460-440c-b9b9-9c5a26cb4d4d/
https://urlscan.io/result/9e2ebb66-d6b1-4695-b37b-29b82ecf6c43/
bittrex-account-verification.com
Suspicious bittrex domain
https://urlscan.io/result/e93b0a03-7022-4427-9d7a-aec9831efb5d/ …
> bittrex-login.com + more

- blacklists/domains.json
5000eth-promo.com
https://urlscan.io/result/c631b00d-73c7-4959-9442-09a1b130488a
address: 0xa61344257ed7c98b4690572e63797d75b0753f96
myetherofficial.com
Suspect MyEtherWallet domain
https://urlscan.io/result/c18ba254-84b7-49c7-aa3b-26cb26746d1d/
myetherwallat.online
https://urlscan.io/result/1e906a91-0193-4d24-99bd-667487401039/
myetherwalletw.org
Suspect MyEtherWallet domain
https://urlscan.io/result/c337da42-b750-445a-bf9b-b7789b667e68/
myetherwallte.net
Suspect MyEtherWallet domain
https://urlscan.io/result/e6d8432b-5e10-4101-a03e-b086d1acd7ed/
myetherwalret.ru
Fake MyEtherWallet (loading assets from myetlherwallet.pro)
https://urlscan.io/result/85273460-9cb0-4af6-8b3b-991fb88e346b/
login-myetherwallets.com …
> myetherofficial.com + more

- blacklists/domains.json
ethconfirm.info
https://urlscan.io/result/82012737-52af-4be3-9a0c-aea2b0856601/
address: 0x92FA227D01DedeDAE2a50B9Da02413C48a872424
offer.ethsn.com
https://urlscan.io/result/23ad8b13-e953-4feb-8b63-0fb4af476fa8
address: 0xe597880Cb0591c6fc09E1B2778c26CAD34922B82
ethsn.com
https://urlscan.io/result/84912892-f8b7-48a8-ae37-9b5366bbd068
address: 0xe597880Cb0591c6fc09E1B2778c26CAD34922B82
> ethconfirm.info + more

- blacklists/domains.json
get.ico-eth.org
https://urlscan.io/result/4c6e8458-e31b-4284-ab10-cfeeb781b292
address: 0x1901D590f5dDBE8d58c69B324c13F884ca1d0B31
ico-eth.org
https://etherscan.io/address/0x1901D590f5dDBE8d58c69B324c13F884ca1d0B31#comments
address: 0x1901D590f5dDBE8d58c69B324c13F884ca1d0B31
payment-ethereum.online
https://urlscan.io/result/e76b5bfd-efe6-407b-a31a-992128067410/
address: 0xDC3896Be3EB4bB3B3eb2f936348E942796078920
tron-block.info
Fake Tron web wallet
https://urlscan.io/result/ff050d91-d9fa-4ebc-9f5a-56733d5887c0/
address: 0xdd1db171b110fb857311fde3236217894e7e9ab8
neo-online.info
Fake Neo web wallet
https://urlscan.io/result/d206ce53-d9bd-46c4-acc0-fed87b206bad/
> get.ico-eth.org + more

- blacklists/domains.json
eth4everyone.com
https://urlscan.io/result/195115dd-6b79-46bf-a4c2-3868e387441e
address: 0x86A120236c1f595ea53a93736b2E397C27aF802e
ethtransaction.ezyro.com
https://urlscan.io/result/7b821f66-6a4a-419d-beb5-3a3549c4f15c
address: 0xf39f8505c37080998a58bc9bdd946b81d4949004
> eth4everyone.com

- blacklists/domains.json
brm.10000eth-gift.com
https://urlscan.io/result/1896bdfa-0856-4436-9f89-dad49bf313c9/
addresss: 0x8858297c69ed011c48feAa96F0c89349Ef389B67
ethsecure.info
https://urlscan.io/result/9fba6899-498b-4fa5-90ac-89103d99a55a/
address: 0x60e6a89060B325148FE247e9E1C0d090e2764ec2
get.ico-eth.net
https://urlscan.io/result/13d338f1-1511-4016-b43d-a1723fe646ad/
address: 0x821Efcb121B9c646dc8D5FB61E9c8ee9C30BA9e4
ico-eth.net
https://urlscan.io/result/13d338f1-1511-4016-b43d-a1723fe646ad/
address: 0x821Efcb121B9c646dc8D5FB61E9c8ee9C30BA9e4
collectmyethers.org
https://urlscan.io/result/7fb3e928-8c60-459a-9498-eed1a6008588/
address: 0xf9f876a42FCB0d40759790781FDc886449f54008
> brm.10000eth-gift.com + more

- blacklists/domains.json
wallets-ether.com
Hosting a fake MyEtherWallet and being promoted by a fake MyEtherWallet account on Etherscan DISQUS channel
https://urlscan.io/result/1af2b467-495d-402e-b7d5-51b26fe0e621
> wallets-ether.com

- blacklists/domains.json
secure375446884521.safeethpay.com
https://urlscan.io/result/bc664136-1940-4072-9186-72472d25905c/
address: 0xF36b756013f80B162e8713fb37dF7dDA0Cd7F143
safeethpay.com
https://urlscan.io/result/a63ba90a-3e4b-453e-9965-13a06540c314/
address: 0xF36b756013f80B162e8713fb37dF7dDA0Cd7F143
xn--myethrwllet-pjb5u.com
Fake MyEtherWallet - IDN homograph attack domain - suspected address: 0x3a878eddb991ebcbc7c8052055b2e5ed5d0d1ba4
https://urlscan.io/result/94054a20-8453-4235-9863-f999b720d974/
https://urlscan.io/result/7065f90d-a3bf-43b5-9d21-0484cf2bd9ea/
quarkchain.in
https://urlscan.io/result/d414bcf8-63a2-4845-a12b-eb62f2bf78d6/
https://urlscan.io/result/1e282255-b773-43a1-b3cb-2f33dd50be48/
address: …
> secure375446884521.safeethpay.com + more

- blacklists/domains.json
claim-eth.com
https://urlscan.io/result/80abf5d0-c83b-4d74-9cc1-009bbe8b5b00/
address:  0x91e35d6c5B7323647e0cc1d274A072AC5CBB4340
send.ethergot.com
https://urlscan.io/result/e4a8052c-e5cf-4830-b13a-d7918c831f91/
https://urlscan.io/result/46877af3-b4c1-47f4-a10d-fd158a8f23e3/
address:  0xeae0B6B040bf8Adc143382d166cc008D8c317b23
ethergot.com
https://urlscan.io/result/a7caa56f-1e41-48e9-9d41-43462a981299/
address:  0xeae0B6B040bf8Adc143382d166cc008D8c317b23
securepay-eth.org
https://urlscan.io/result/4b2c3a06-51e4-43e5-a233-fd2f58b61b1a/
https://urlscan.io/result/8de33899-5a8b-4744-b278-746dba37037b/
address:  0xCdE79393C6F0dEB9B7b51579a386c853fEb8E104
gift-10000eth.com …
> claim-eth.com + more

- blacklists/domains.json
quarkchain.pub
https://urlscan.io/result/d6742e8b-8d03-469b-ae25-6fa235e0c4db/
https://urlscan.io/result/46cc2a3c-1e97-454f-b21d-6a2fd9e8ab06/
address: 0x118db57c34621ACd0A91F02C8c18cD1a3AD7C213
> quarkchain.pub

- blacklists/domains.json
myerherwallet.tk
Suspect MyEtherWallet Domain
https://urlscan.io/result/5f3bb1d7-2047-42fe-997f-834c43aa9664/
myetherwallet.news
https://urlscan.io/result/5b82e270-7518-41a8-8571-48641116a7e9/
myetherwalletz.org
Suspect MyEtherWallet Domain
https://urlscan.io/result/b18b78b5-f226-4dbb-ba74-3dd5a87ee09b/
myethrwallet.org
https://urlscan.io/result/fe2e89d1-3b7b-485e-815f-8e114df0a2cf/
myrvnwallet.com
Suspect domain for MyEtherWallet
https://urlscan.io/result/17202503-543a-49c7-b706-2f7560fb5c81/
xn--myetherwllt-s8a7g.com
https://urlscan.io/result/6a9aa7fc-641b-452b-b599-2d682d14d844/
myetherwanllet.com 
Suspect domain for MyEtherWallet
https://urlscan.io/result/5af1b129-2e53-4481-8da7-ea19e3da5e01/ …
> myerherwallet.tk + more

- blacklists/domains.json
mycrypto.promo
Fake MyCrypto
https://urlscan.io/result/004ec0c1-e7d3-47a1-ba21-060152b79f5e/
mycrypto.company
Fake MyCrypto
https://urlscan.io/result/da74e8ec-90fa-4adf-ab93-6c83cbfd6d0c/
mycrypto.group
Fake MyCrypto
https://urlscan.io/result/d04105c1-9407-4825-b441-4645e57f2669/
mycryrpto.com
Fake MyCrypto
https://urlscan.io/result/e7b68d98-9dc2-4c81-9427-160820267c21/
mrycrypto.com
Fake MyCrypto
https://urlscan.io/result/03cf9bf6-fbda-4e1e-925b-68b074a78829/
myerypto.com
Fake MyCrypto
https://urlscan.io/result/ebe35ee8-82ab-4e91-8041-cda001cb8cd7/
myrcrypto.com
Fake MyCrypto
https://urlscan.io/result/6cf2b7ae-fdfa-4c8c-9b30-2622b6ec0460/
nnycrypto.com
Fake MyCrypto
https://urlscan.io/result/8417f932-da41-435c-a6ba-3a15bbb19989/
xn--mcrypto-rpd.com
Fake MyCrypto - IDN homograph attack …
> mycrypto.promo + more

- blacklists/domains.json
coinbase.pro-fork.com
Phishing Coinbase users
https://urlscan.io/result/b60c8734-ef98-4f85-a557-0226586b33c0
https://urlscan.io/result/4f2dd8db-2667-45f4-974e-5b6f6b4c42f9
> coinbase.pro-fork.com

- blacklists/domains.json
10000eth.net
https://urlscan.io/result/697341bd-582b-4071-9dd8-de97a20058a1
address:  0x135a24A24E524DE187efab379FC655061A67cBD5
> 10000eth.net

- blacklists/domains.json
ether-giveaway.net 
https://urlscan.io/result/67bfacba-df9e-48db-8762-6466f6c68013/
address: 0x29Aaa966321F7d82E119BBc965a58CB62d703445
output.jsbin.com/ciqukak
https://urlscan.io/result/55f15485-82c3-43ed-8e10-25c3b18abd7c/
address: 0x3389a9CacB4A3FdbE43DB14D132b3F1e215A835d
ethget.me
https://urlscan.io/result/4aa0ab16-ff6f-41cc-84e7-cea8a46840e3/
address: 0x425E0406395243F087100C8F7b67C02217974123
ethbonus.org
https://urlscan.io/result/252f8ba4-770b-4669-aa5b-0d648a9bdaa1/
address: 0xEDfE1d963b32a89E05Dd0Bc0E8F595b4B9Afb544
eth-give.me
https://urlscan.io/result/fef1fdcb-708e-40e8-ac97-9c7d15e11413/
address: 0x7b433D46E875FE540b1eA2D3011113F1B400D3d5
getethnow.com
Trust …
> ether-giveaway.net  + more

- blacklists/domains.json
coinbaseverifier.com
Fake Coinbase phishing for logins and 2fa codes
https://urlscan.io/result/d0fe7e51-605d-4f3a-89b3-9bff24670054
https://urlscan.io/result/e702afd3-75db-4707-bef1-2a614e392d7e
https://urlscan.io/result/d0d176c2-1325-4a1c-896b-3722a0c719bc
https://urlscan.io/result/b14c0553-ba07-4d42-8972-6e5a0130ab80
> coinbaseverifier.com

- blacklists/domains.json
xn--myetherwllt-f7a75e.com
https://urlscan.io/result/8d098940-7a44-4f2d-979e-62860d3e39a9/
https://urlscan.io/result/7e3a7ec8-8268-48e6-ae47-5fe72a65f909/
> xn--myetherwllt-f7a75e.com

- blacklists/domains.json
> bit-coins.cloud

- blacklists/domains.json
ethgw.info
https://urlscan.io/result/16b8a6c8-009c-4efb-a4e0-40e8ca5029fb
address: 0xB6ADacf355031C10b4FD70eE7FB4acA88A7C216d
ethbigpromo-com.1gb.ru
https://urlscan.io/result/2d53b056-bad2-475d-a409-95838688ba59
address: 0x2c1dF1D2B053E2BF89BB5251AF392bc962326e51
claimcrypto.org
https://urlscan.io/result/b6314c07-986c-4365-8a4f-d6c488311282
address: 0x839DB3994bef8842C0809AB84996bA839fCac11e
> ethgw.info + more

- blacklists/domains.json
idex-market.eu
https://urlscan.io/result/85459fee-49d3-45e1-aa66-953a64dfad5f/
idex-login.net
https://urlscan.io/result/c4515f76-046d-40a0-bccd-7bda2e606663/
index-macro.com
Fake Idex market phishing for keys - iframing 185.156.173.87
https://urlscan.io/result/89e6ea11-f3b0-4ebd-b1ec-5a9535579efb/
185.156.173.87
https://urlscan.io/result/a6b3aa90-655c-4739-bdcd-86f5e606655f/
eos-paperwallet.com
Fake EOS paperwallet generator
https://urlscan.io/result/b1f771e9-684d-413e-a260-f3193b60a902/
> idex-market.eu + more

- blacklists/domains.json
eth-get.com
https://urlscan.io/result/3625920c-652d-4e0f-bdf2-5bced94e57fd/
address: 0xf8abBDc8578B940b82906a2E8da893B164D4FA59
giveaway-ether.info
https://urlscan.io/result/e47f8558-80bc-49d7-a10f-b09c4a9484ed/
address: 0xa78959E1568448a3CF866968872431E710458552
ether-give.club
https://urlscan.io/result/a21636bf-face-4f76-a4b8-66f994d84a70/
address: 0x50a9a8c8ce2bb0ea10f4d4a586ac2d77257b8247
eth.promo-etherum.com
https://urlscan.io/result/8ed60ed2-dd11-44f3-9bf7-751f2ffd668b/
address: 0x2d19F9FEcE6DA18f2899944B0621C5eCeBAa249B
promo-etherum.com
https://urlscan.io/result/f8fde317-2a1d-4238-bf5d-40325eeca1f7/
address: 0x5526dc369bBE6B9B2c5e64BB368C1d3Ccfa58271 …
> eth-get.com + more

- blacklists/domains.json
idek.io
Fake Idex phishing for private keys
https://urlscan.io/result/aeeb5e0f-7581-441d-ac3a-1abb0ec12390/
idex24.io
Fake Idex phishing for private keys
https://urlscan.io/result/b7e9dd3a-0f2e-436f-97a7-4c427342c459/
> idek.io + more

- blacklists/domains.json
collect.bestethgift.com
https://urlscan.io/result/254ba5d8-2842-4d63-8867-ab3126294e2d/
address: 0x3E53A430c39896dAf1b241828e3b5E8D526503fA
bestethgift.com
https://urlscan.io/result/2c59a121-f267-421d-8bd8-b13bf1fb21e3/
address: 0x3E53A430c39896dAf1b241828e3b5E8D526503fA
> collect.bestethgift.com + bestethgift.com

- blacklists/domains.json
btcoin.vu
https://urlscan.io/result/faed9c9a-b3af-4291-b403-985fc6219621/
btc-giveaway.com
https://urlscan.io/result/518bc26e-4078-4946-a05a-2477a7cdc049/
btcofficial.info
https://urlscan.io/result/35a3211f-ad7a-4b71-9aa6-814efab12e87/
> btcoin.vu + more

- blacklists/domains.json
myiteher.com
https://urlscan.io/result/034d2101-0afe-4a50-b617-b56b920338e7/
musk-giveaway.com
https://urlscan.io/result/b66e97b1-8708-4209-b2d3-fda4cfdb8a07
address: 0x7C875Ee4D4a1B29B41eBb2678dF1F645F28d090B
get-ether.cash
https://urlscan.io/result/30b8bc99-858f-4faf-90ae-4d113d2d90ce/
address: 0x3d7A0fAE63809c4725b13bddDabBb718939AD10e
crypto-claims.org
https://urlscan.io/result/5ded4350-665e-4778-9bcb-5e1167c339d4
address: 0x839DB3994bef8842C0809AB84996bA839fCac11e
free-ethers.com
https://urlscan.io/result/e754bc6e-0f2b-4ce8-9efa-5c995b5c3c37/
address: 0xAa9455da13bA39f5d4E6275337C3D5600CB0f5B4
ethershares.blogspot.nl …
> myiteher.com + more

- blacklists/domains.json
fantoms.foundation
Fake Fantom crowdsale site
https://urlscan.io/result/2ae25deb-e191-4638-8f76-790258d653e8
address:  0x8d305Fd29aEbd6e0562dE9321d55E7f0E6fbaCaD
> fantoms.foundation

- blacklists/domains.json
etherepromo.win
https://urlscan.io/result/09d9765e-fa43-4ad6-8bc7-8299334918dd/
address: 0x13403162EF6cF6219441667Ae22892c997262611
ethtowallet.com
https://urlscan.io/result/0eb77abb-2088-42aa-9f8a-e5031ed08cc0/
address: 0xA6626a8a85f2032930A25D278aE149191E3ba247
ethsclaim.com
https://urlscan.io/result/c1087b2d-afb9-460c-a2f3-c9cdc0a8240c/
address: 0x4508B6691D8c938781F130519625B4CDD7B1f804
ethaward.com
https://urlscan.io/result/95665bc9-85b4-466b-8c81-c897dab1bb4d/
address: 0x5f38DcBc5a2DBE1e040a60153750feb7E1CfA570
airdrop24.com
Trust trading scam site - http://prntscr.com/jr816v
https://urlscan.io/result/67622e5c-364e-447e-926f-fac618df85ef/ …
> etherepromo.win + more

- blacklists/domains.json
zecblock.info
Fake ZCash web wallet
https://urlscan.io/result/d906bf97-f70b-4b33-af38-3378daa10371/
litecoin-chain.info
Fake Litecoin web wallet
https://urlscan.io/result/955ce8f8-14be-4332-bd16-767f137ac369/
ripple-chain.org
Fake Ripple web wallet
https://urlscan.io/result/8145246c-311d-4b9f-aef0-c88a73723ba2/
online-stellar.info
Fake Stellar web wallet
https://urlscan.io/result/3ee4cb65-2659-450d-9acf-15018e8abe96/
coin-monero.org
Fake Monero web wallet
https://urlscan.io/result/2757e869-c34d-4ebc-9d7e-4a7e05729b10/
> zecblock.info + more

- blacklists/domains.json
etheroll.io
Fake Etheroll
https://urlscan.io/result/10c2378c-fb28-4556-a97d-07f793f42586/
address:  0x521ff702e1eed9e48cbe17e2dae6efd77b9d6876
> etheroll.io

- blacklists/domains.json
see https://github.com/MetaMask/eth-phishing-detect/pull/1812
> remove btcmanager.com

- blacklists/domains.json
putty-portal.com
Fake EOS web wallet
https://urlscan.io/result/50fa705a-8770-4127-88c1-c88876de7238/
arweave.pw
Fake Arweave crowdsale site
https://urlscan.io/result/c9842ee7-35ff-4788-91b5-b0affdfe5e50/
https://urlscan.io/result/e50a784a-eec6-4199-a69e-6f3d87d7fb16/
address: 0x32F5891Eb94e7a1eBb06aDd32AcddAC95774316b
> putty-portal.com + arweave.pw

- blacklists/domains.json
bittrex-id.com
Fake Bittrex phishing for logins
https://urlscan.io/result/09b33e3d-968b-4362-98de-fb396a4804fc/
https://urlscan.io/result/7e400a30-007f-4850-b069-ee2985e1469b/
https://urlscan.io/result/8d7d0414-6f39-4d40-9e51-82b7ba7f95ec/
https://urlscan.io/result/ccd56adb-f65c-4a04-95fc-7e6bd38f93e9/
> bittrex-id.com

- blacklists/domains.json
idex-market.at
Fake idex market phishing for keys
https://urlscan.io/result/b8ff420b-5a25-4d76-853d-beed5b917545/
wallet-idex.net
Fake idex market phishing for keys
https://urlscan.io/result/57e1c18c-5307-4985-98d4-2e1ffc91710a/
> idex-market.at + wallet-idex.net

- blacklists/domains.json
myighther.net
https://urlscan.io/result/c6bb837d-afd6-4f1d-8989-77aa00b58e2f/
eteclum.org
Fake MyMoney login phishing for keys
https://urlscan.io/result/b643e6b0-549c-4f77-aa6f-e840076e9a8e/
https://urlscan.io/result/10ac8b04-50de-4cef-8c2c-0a3e818f34c9/
> eteclum.org + myighther.net

- js/DomManipulator.js
- js/SignatureInject.js
- js/app/signatureSelector.js
- js/options.js
- manifest.json
- settings.html
* Added logic to handle injecting a "signature" into the DOM so a webpage knows if EAL is installed, and if not, display a small notification to get them to install it - read: https://harrydenley.com/eal-install-notification/
> [FEATURE] EAL Installed Signature

- blacklists/domains.json
giveethers.info
https://urlscan.io/result/ff1da622-1372-47c5-8900-a47a00afc0b7
address: 0x77C955a2cb5BCCAf0654d78a3FFcD8bd6cB0c2B8
> giveethers.info

- blacklists/domains.json
idix-market.info
Suspicious Idex market domain
https://urlscan.io/result/15172255-6a7a-4834-97f7-c138b1d86cce
icon-block.org
Fake ICON web wallet
https://urlscan.io/result/57a52193-8c74-49a6-ab93-41b290aba7a4
> idix-market.info + icon-block.org

- blacklists/domains.json
welcome.promotionaleth.com
Trust trading scam site. Promoted with https://bitly.com/2HCBz5w+ and https://bitly.com/2JJQP5y+
https://urlscan.io/result/55ea6c95-e3e9-4cf8-b141-212bd3b9a58f/
address: 0x9951bE5ac7Daf77724A4f7443bef446F6184a377
promotionaleth.com
https://urlscan.io/result/b2dfb9ca-b3bc-4df1-b3cf-047c9c50ddea/
address: 0x9951bE5ac7Daf77724A4f7443bef446F6184a377
> welcome.promotionaleth.com

- blacklists/domains.json
hederahashgraph.tokenico.me
Fake HederaHashGraph crowdsale site
https://urlscan.io/result/48c7d465-45f3-47a8-a33b-b77eb644f42d/
address: 0xEDc702Ed96AccAE315A0F1E8Fa2d5a6bC4FeeA69
secure.ethxchanges.com
https://urlscan.io/result/887699fd-57d7-45d8-b291-c850743e40d7/
address: 0x9d032989F82c0e40202AE5Abd844Ff68181544D2
ethxchanges.com
https://urlscan.io/result/ba752127-9a1f-4822-aab2-cbc1647f6d73/
address: 0x9d032989F82c0e40202AE5Abd844Ff68181544D2
ethgift.io
https://urlscan.io/result/1cca3abe-3d05-43ee-80a2-85e5a6a821e3/
address: 0xcEe56C3d77d814d29b9410c0f74c12781fcE03ff
verify.officialeth.com
https://urlscan.io/result/701e75b3-8341-435f-90e3-3d853ad4697b/
address: …
> hederahashgraph.tokenico.me + more

- blacklists/domains.json
ploloneix.com
Fake Poloniex phishing for logins
https://urlscan.io/result/555d63a7-9b45-44b3-b253-1fc9cb2b3aef/
https://urlscan.io/result/fc7bb045-d480-4978-92a1-dc00abec5e4d/
porloneix1.domen-hosting.org
Fake Poloniex phishing for logins
https://urlscan.io/result/28ccee82-8ad6-48e6-8931-9cb264deb130/
https://urlscan.io/result/5ee727e7-58f6-4f16-a47a-7e84ea2d8fb9/
porloneix.com
Fake Poloniex phishing for logins
https://urlscan.io/result/af728fe0-02f5-4868-a00b-bd396ae62f39/
https://urlscan.io/result/8f1aa92f-d601-4a61-b01a-e344f9b05f05/
polroniex.com
Fake Poloniex phishing for logins
https://urlscan.io/result/3c979218-08ce-4183-a4d8-b6f24483c562/
porloniex.com
Fake Poloniex phishing for logins
https://urlscan.io/result/0751f587-0be9-4aa8-99ba-86e24b79002b/ …
> ploloneix.com + more

- blacklists/domains.json
etherbonus.win
https://urlscan.io/result/30bd9155-e362-4064-947c-7a244284695d/
address: 0x1AE807d7645da9F7F65A3c4A7A8DeaA08bf9EFa4
getethpro.com
https://urlscan.io/result/4e3b561b-3534-446d-961f-0ab907ce8189/
address: 0x701cB175E6cA0EE8DcB61B4598B5a08E2A60bc2A
about.me/vitalik.buterin
https://urlscan.io/result/10be364d-60b8-4c6b-9c25-ddcc072221fc
address: 0x7d5F788097E80D797064FdE23a62CaF8D18Ee5a6
event-ethereum.org.uk
https://urlscan.io/result/4d4ce7fc-420f-42ec-b8b6-1520b29a4147/
address: 0xE3400442Ed7754cB2a43beCB83f801Cce1055Db9
> etherbonus.win + more

- whitelists/domains.json
xn--1-ylb.net
https://urlscan.io/result/124d868a-f541-4d95-8181-b2ce9f4cfa55
Fixes https://github.com/409H/EtherAddressLookup/issues/715
> xn--1-ylb.net

- whitelists/domains.json
Removed famalk.net as its a dead site
> removed famalk.net from whitelist

- blacklists/domains.json
Trying to phish fantom.foundation ICO participants.
> added fantom-foundation.tech

- blacklists/domains.json
elon-shares.com
https://urlscan.io/result/0df96076-787b-4c6e-8057-ba50a91c249f/
https://urlscan.io/result/68c8544d-5214-44ef-8a20-2592fbef3558/
https://urlscan.io/result/c09c2d7c-01ca-408e-b996-85500f687386/
address:  0xa61a87497E6553e3b1CF66c8b02FA392A0eFF1E3
> elon-shares.com

- blacklists/domains.json
myeostrust.com
https://urlscan.io/result/da324895-cf75-4897-82f4-b0550061c2bd
eosdrop.xn--mythrwallt-c7a86c5a.com
https://urlscan.io/result/9f701baf-90d3-4cea-83d2-7db93d04230d
> Appending two black domains passing through metamask and EAL/ESL

- blacklists/domains.json
give-ethprize.com
https://urlscan.io/result/96353108-4f6c-48ff-9e84-df9d260e6f70
address: 0x257890939F7c0B758897F7Bd49A590B7190043e0
odyssey.center
https://urlscan.io/result/20382cc6-2d4a-4593-8535-72961957422c
https://urlscan.io/result/8e30cf3d-ac91-42d9-9bc2-5a88c91a73a9
world-market.online
https://urlscan.io/result/fd3faf2e-96fe-4fb7-8c6d-a82a2c770766
> give-ethprize.com + more

- blacklists/domains.json
ethe.mediumblog.top
https://urlscan.io/result/0e6e0201-890e-4492-918f-f6bfdf7c0483
https://urlscan.io/result/d70def23-866b-41c5-bcea-91ee0a758194
address:  0x336a3f0c4d40b1e39cee72e2e59330daf484848c
> ethe.mediumblog.top

- blacklists/domains.json
freeethpromo.com
https://urlscan.io/result/6517e1ad-50a0-45f7-bab3-9281aaf79281/
address:  0xcf1d62627BAf1a84BeD11E30cf6CDae0f1B5C296
> freeethpromo.com

- blacklists/domains.json
Giveaway SCAMs 
grab-eth.com  https://urlscan.io/result/6a5ad381-7615-4cef-9af5-9ab71260cfc1/
eth-verified.com  https://urlscan.io/result/a5ff0b0a-4485-4948-be46-7031ba5ba5f8/
ethereum-event.com   https://urlscan.io/result/aed91a11-7b06-4994-a463-0770e1ae9c78
musk-shares.com  https://urlscan.io/result/3038ba7e-3d9d-4a73-b549-f8878ad351fc
valideth.com   https://urlscan.io/result/3494cc40-dd97-4cf1-b01e-f1c55c154143
elon-giveaways.com   https://urlscan.io/result/b43e6c75-81a3-469d-93d3-fc184c6b66b1
elon-gifts.com  https://urlscan.io/result/b5b2e9de-28c9-48db-9784-4055166a5cb9
elon-gift.com   https://urlscan.io/result/ae342491-5337-43ea-a892-6e3dca4fdb4c
musk-shares.com  https://urlscan.io/result/8967d058-73fa-45dc-b33f-f9915a8af626
> Update domains.json for giveaway SCAMs

- blacklists/domains.json
Fake MyEtherWallet - IDN homograph attack
https://urlscan.io/result/7d48e392-32b0-46c4-aa30-f60d4fa95a51/
> xn--myetherwllt-f7a13e.com

- blacklists/domains.json
ethgift.net
https://urlscan.io/result/9b907bb0-5019-4e4f-a975-e31bf80341cb
address:  0x33e5d6C0447EA731Fe4e2502a881B90ee991CF3a
ethfortune.com
https://urlscan.io/result/e93fd184-d361-432f-a713-a42d67506895/
address:  0x37e30FEe740928E8Db15d3daFd544bAAB6B87051
> ethgift.net + ethfortune.com

- blacklists/domains.json
xn--eosauthorty-jzb.com
Fake EOS domain - IDN homograph attack domain - phishing for private keys
https://urlscan.io/result/ef5231fd-3992-4cfc-89b2-40f3779a2f38/
xn--eosuthority-m7a.com
Fake EOS domain - IDN homograph attack domain - phishing for private keys
https://urlscan.io/result/76f036bb-6425-4bd4-ae39-3ed83806a9bd/
xn--eosauthorty-kcb.com
Fake EOS domain - IDN homograph attack domain
https://urlscan.io/result/fe2a0744-20a7-486c-9e33-847ee5763660/
xn--eosauthorty-wcb.com
Fake EOS domain - IDN homograph attack domain - phishing for private keys
https://urlscan.io/result/d2f668a3-d806-4cd8-beb3-9edd0dc08aeb/
> xn--eosauthorty-jzb.com + more

- blacklists/domains.json
validbtc.com
https://urlscan.io/result/693d1d60-dff8-436f-acb5-5dcf46ea9502/
address: 0x973cC36EEF960389b1DdDCE82a9f0663Af61809B
ethcelebration.io
https://urlscan.io/result/7ae3bde5-2831-4feb-aa59-a2c4497e1b43/
address: 0x1F319dD5015b1068F102912F970D63B9947E4Cb0
crsafepay.com
https://urlscan.io/result/81fe7ce4-ca02-429f-bb6c-621121fe2037/
address: 0xa2280DdC79183A0dE9D3D90C63c0E7646874d9E0
verify.ethgoldmine.com
https://urlscan.io/result/425e38f8-dcf1-4a2a-8938-74a30eb02231/
address: 0x6C712Ae4986342773eDC37a9ff7fA90B1b52ca6e
ethgoldmine.com
https://urlscan.io/result/308f4d34-53b9-49fd-a313-8b3a2bc2e146/
address: 0x6C712Ae4986342773eDC37a9ff7fA90B1b52ca6e …
> validbtc.com + more

- blacklists/domains.json
myehferwallet.com
https://urlscan.io/result/a363a6b9-766f-4f00-85e5-25b2f7246670/
myetherwallet-signmgs.top
https://urlscan.io/result/da6cc64a-7fa6-434b-8c36-2c01c80c5a5e/
eosauthorithy.info
Fake EOS site phishing for keys with POST store.php
https://urlscan.io/result/44115236-4ad2-4aa0-8876-f81e43670ef0/
ankr-network.tech
Fake Ankr crowdsale site
https://urlscan.io/result/71cfa895-f615-4621-8fe5-16f68d42b16c/
address: 0xaAB92EAd3017703f7f9F3f7Ff71F623cd7a8D164
ankr-network.com.de
Fake Ankr crowdsale site
https://urlscan.io/result/cfa36c6f-fb9d-4e4f-ae06-2192bd9e1d18/
address: 0x3eD46342C7D8D29CA065E8EcA66BBf867A86E897
> myehferwallet.com + more

- blacklists/domains.json
Account has been suspended. Blocks twitter.com for Pi-hole users.
> Remove "twitter.com/EthexOfficial"

- whitelists/domains.json
xn--c1adicwtd2j.xn--c1avg
https://urlscan.io/result/c6f6d7b1-30eb-4fd7-8f29-248476416916/
Fixes https://github.com/409H/EtherAddressLookup/issues/777
> xn--c1adicwtd2j.xn--c1avg

- blacklists/domains.json
myetherwallet-singmgs.top
https://urlscan.io/result/fffa41d0-833a-4b9d-8463-201dddbf93a2/
safe.ethincrease.com
https://urlscan.io/result/7cc15dc4-e32b-4143-a99d-f22ebf2f18bf/
address: 0x484F46f9Dd32A0147126F07Da4be61efc26eF42A
ethincrease.com
https://urlscan.io/result/6b4ff7da-7eb4-473f-a65a-d73e412499c7/
address: 0x484F46f9Dd32A0147126F07Da4be61efc26eF42A
myetherwall-et.com 
Suspcious MyEtherWallet domain
https://urlscan.io/result/d81539d8-28d1-4b27-8aef-c596569ac631/
myethre-wallet.com
Suspcious MyEtherWallet domain
https://urlscan.io/result/d81539d8-28d1-4b27-8aef-c596569ac631/
myether-wallet.com
Suspcious MyEtherWallet domain
https://urlscan.io/result/80d0eb57-128d-4f73-8e3b-c69b027640db/ …
> myetherwallet-singmgs.top + more

- blacklists/domains.json
myethswallets.info
https://urlscan.io/result/69dfaad2-2c22-45bd-b459-c5ad7afe710a/
> myethswallets.info

- blacklists/domains.json
myethenrwallet.site
https://urlscan.io/result/ce36b542-4296-4dd1-b9dd-62bbb8b426d0/
myetherium.ru
https://urlscan.io/result/4625452b-d853-47bd-b922-392e8c00409e/
myetherwalleft.ru
https://urlscan.io/result/5930a584-25d2-4666-b7df-847fe67b30bc/
myethrewallets.com
https://urlscan.io/result/4d989e1c-bb15-4a61-92f9-bbc134953726/
myethrwalet.com
https://urlscan.io/result/341c51e1-6b08-4ff1-9d4d-e25226d9648b/
> myethenrwallet.site + more

- blacklists/domains.json
teslaforfree.wordpress.com
https://urlscan.io/result/2dfd48ca-aa79-4cc4-be87-b9d328a56b29/
address: 0x58049616f5cd4b2ccd3654d7015d271a985ff2e7
go.ethtake.com
https://urlscan.io/result/a63ba14d-4205-4a53-b302-e778189336e5/
address: 0x1EFD1B1Ee8174B5421786EF0127EA45076307D8d
ethtake.com
https://urlscan.io/result/0c6d10c7-bbdf-4653-87dd-d565d481333c/
address: 0x1EFD1B1Ee8174B5421786EF0127EA45076307D8d
instagram.com/vitalik_buterin_official/
Trust trading scam
https://urlscan.io/result/94a7c949-a807-4b4a-9780-8f8a1eaba616/
address: 0x4D021FB560fdC49250A23E4006b584058667BaF7
> teslaforfree.wordpress.com + more

- blacklists/domains.json
eth2018.net
https://urlscan.io/result/06422066-a354-40ae-913c-73556083e491/
0x4F3ca8C465170C0988295e22B5347eF8BB38F2B7 
ethtwitter.com
https://urlscan.io/result/709a689a-f658-4562-bf8a-b2f18ccd65dd
0xa49d41A87F33C1A7B6368c171298266bB193a08f 
0x0db49185AaE1f8F4b95EBD5323C1fa3822d4FDe8 
ethereumstash.org
https://urlscan.io/result/b30b52db-37f8-4c45-b429-ce2921a42cc5/
0xAF5bDa8f8b954b03474305FD148c8361CaD4D2cD
> Adding three blacks fresh

- blacklists/domains.json
xrp-address.org
Fake XRP web wallet
https://urlscan.io/result/73703ee7-63f0-44bd-9615-a6d69921ad24
> xrp-address.org

- blacklists/domains.json
myetherwalletverification.signmsg.work
https://urlscan.io/result/7a3ec100-59ab-4ab9-a0e2-c86c685621cb
> myetherwalletverification.signmsg.work

- blacklists/domains.json
node82.btc-giveaway.info
Trust trading scam site. Bitcoin address: 17ntyMTNJpM6JDdS9M5G2eKgKELuGfzZkr
https://urlscan.io/result/4d027946-90dd-482d-969d-ee96d0692ff3/
https://urlscan.io/result/68b1d00d-2a10-4cac-8c0c-a0fb50d0e079/
texacon-verify-547fcd.bitballoon.com
Hosting a fake airdrop directing users to a fake MyEtherWallet xn--myethrwalt-f7a07c4r.com/signmsg.html via bitly.com/2KNuPHT+
https://urlscan.io/result/9e802a50-5530-4f04-91e1-846b86647879/
https://urlscan.io/result/591989b3-c4f1-476a-87dd-2998867182ad/
kinetictokenforms.typeform.com
Hosting a fake airdrop directing users to a fake MyEtherWallet xn--myethrwalt-f7a07c4r.com/signmsg.html via bitly.com/2KNuPHT+
https://urlscan.io/result/9e802a50-5530-4f04-91e1-846b86647879/ …
> node82.btc-giveaway.info + more

- blacklists/domains.json
myeleherwaret.com
https://urlscan.io/result/26f09d36-9849-4c35-94c3-c03cd951a5e5/
meytherwellat.com
https://urlscan.io/result/dd0e5a19-5a9c-49aa-9c47-7e8a5e70ae46/
> myeleherwaret.com + meytherwellat.com

- blacklists/domains.json
eth.mediumblog.org
https://urlscan.io/result/f0e9b108-7087-4367-b58a-1810cc7826e1/
address: 0xebe808320931473e5ED488e582F93dEdf8369A77
ethe.mediumblog.top
https://urlscan.io/result/3aafdf23-31eb-469f-8c95-ee5b8b046d79/
address: 0x5208d7f63A089906889A5A9CAed81E9C889E64F8
claim.ether33.online
https://urlscan.io/result/a721f09b-cf23-4e0a-9874-319cf6d52e92/
address: 0x336a3f0c4d40b1e39cee72e2e59330daf484848c
mediumblog.org
https://urlscan.io/result/3aafdf23-31eb-469f-8c95-ee5b8b046d79/
address: 0x5208d7f63A089906889A5A9CAed81E9C889E64F8
swswd.ether33.online
https://urlscan.io/result/b721f5ac-5ee1-4d4c-8cb2-7ba13f1562fd/
address: 0x336a3f0c4d40b1e39cee72e2e59330daf484848c …
> eth.mediumblog.org + more

- blacklists/domains.json
myertnerwalletr.com
https://urlscan.io/result/42a90c86-3e5b-43de-9623-86ad5a740753/
myetherweallett.com
https://urlscan.io/result/63912e25-5290-43b6-91ac-3fc49bd946d8/
idex.su
Fake Idex
https://urlscan.io/result/0e31379b-0e73-4774-9b6e-6f71bc727775/
> myertnerwalletr.com + more

- blacklists/domains.json
buterineth.org
ethereum-promo.website
> Giveaway phishing scam campaings on twitter

- blacklists/domains.json
mmyetlherwallett.com
https://urlscan.io/result/10c4f408-500b-4e0b-98cf-1580db64f239/
> mmyetlherwallett.com

- blacklists/domains.json
meyetherwealletr.com
https://urlscan.io/result/3dfecfd3-c920-4e14-a62c-54bcfb604034/
myerhterwallett.com
https://urlscan.io/result/2d5ad89b-8b03-449e-b45d-34a6f890599f/
> meyetherwealletr.com + myerhterwallett.com

- blacklists/domains.json
https://plus.google.com/u/1/114056019931432957256/posts/Hk16DTRy8bB
Trust trading scam 
https://urlscan.io/result/68293072-2940-4aaf-a02d-117f38ba4f36/
address: 0x8a65C8565504a2BDe31F9c09125f5b9D53B2B07e
etherpromotion.org
https://urlscan.io/result/61da9abf-9d2b-4746-aae1-12087774bb68/
address: 0x9acBaFedd352644daCE6bC666dF884e69A8102Ee
ethpromo-giveaway.atspace.cc
https://urlscan.io/result/73702616-c615-401a-87e3-d7365285da70/
address: 0x3d6b1ce6bA915bF0001B4fC135E98474Ef6EEFFd
> etherpromotion.org + more

- blacklists/domains.json
bittrexl.com
Fake Bittrex login phishing for logins
https://urlscan.io/result/bdb5571d-e320-4d83-9a21-718c0b45cefa
https://urlscan.io/result/826e053b-78ec-4d5a-9d56-f5fce55372e9
> bittrexl.com

- blacklists/domains.json
hydrogen-raindrop.bitballoon.com
Fake KYC redirecting users to a fake MyEtherWallet https://myetherwallet.ethersignmsg.services/ via bit.ly/2ufxyjC+
https://urlscan.io/result/5459cc92-cabb-4fd2-b6e3-f899c3dbfedd/
airtoken.typeform.com
Fake KYC redirecting users to a fake MyEtherWallet https://myetherwallet.ethersignmsg.services/ via bit.ly/2ufxyjC+
https://urlscan.io/result/5c4cd5df-caa7-4be6-8a80-d437871e055e/
myetherwallet.ethersignmsg.services 
https://urlscan.io/result/9c5dbb81-de05-4a50-838a-b8f939cdb035/
> hydrogen-raindrop.bitballoon.com + more

- blacklists/domains.json
5000eth-giving.online
https://etherscan.io/address/0x4FAe1eAb137DaF99E12B5AA7fE963f7EC3Dcd40E
https://urlscan.io/result/8a7589ca-3796-4c7a-b617-daf1eca32b06/
> 5000eth-giving.online

- blacklists/domains.json
token-emrify.com
Fake MyEtherWallet stealing keys with POST demoj.php
https://urlscan.io/result/81532d4f-2451-4297-8418-8aaca3dddd3b/
https://urlscan.io/result/969ed47e-7703-45a7-b39b-5b670e1d978c/
myethwallofficiiall.com
https://urlscan.io/result/3ee4e618-9d17-4bff-88da-b449f203ff30/
myetherwallet-hydrogen.top
Fake MyEtherWallet. Reported address: 0x0591A42188996397FC7Cd6DB729045146c37696c
https://urlscan.io/result/453cc090-0916-4b9c-b13f-b02cc994b360/
myetherwallet.com.apisign.icu
https://urlscan.io/result/f3cf01c7-f857-4147-a031-2aa7cfadfdbe/
hydrogen-platform.com
Fake Hydrogen KYC form directing users to a fake MyEtherWallet myetherwallet.com.apisign.icu/signmsg.html via bit.ly/2zDHzfD+
https://urlscan.io/result/2e80ad5c-db74-473c-b697-36eb3d846cde …
> token-emrify.com + more

- blacklists/domains.json
neotracler.co
Fake Neotracker phishing for secrets
https://urlscan.io/result/422112c9-1a11-44b2-827f-2d01da212aad/
brimance.com
https://urlscan.io/result/1847fc7b-0492-476e-9214-a4495b3b0126/
https://urlscan.io/result/2f002043-d9b1-4f3e-9865-cc263700812e/
brilmance.com
https://urlscan.io/result/d185b549-63e2-4a9d-8cc7-9a99ac276306/
https://urlscan.io/result/8f88abd2-2dce-4021-b9f3-2e6bd4512af1/
blirmance.com
https://urlscan.io/result/0e28431c-30c6-41b2-9a83-68aaa7ef072e/
https://urlscan.io/result/8eb166ea-05b9-4dfc-a83b-08c9d4a55940/
brinonce.com
https://urlscan.io/result/42e2eaa8-8582-41dc-881f-d559f821115f/ …
> neotracler.co + more

- blacklists/domains.json
idixmarket.info
Fake Idex market phishing for private keys
https://urlscan.io/result/dc70e3c0-69c7-4f93-b61c-bf6a0846a3eb/
coinbaise.com
Fake Coinbase phishing for logins
https://urlscan.io/result/8ddefe71-b3f6-457c-a099-4ddfe0edd22b/
> idixmarket.info + coinbaise.com

- blacklists/domains.json
idexchange.pro
Fake Idex market phishing for keys with POST /save.php
https://urlscan.io/result/a9d53a62-db97-4d65-9b61-7d8b5f48d0a5/
etherdelta.com.ua
Fake EtherDelta phishing for keys with POST /admm/rdy.php
https://urlscan.io/result/eb4a17af-d881-4954-908a-55a027214585/
https://urlscan.io/result/9ba56114-afe2-4927-9858-155fc78f50a3/
> idexchange.pro

- blacklists/domains.json
ethzerdelta.com
Fake EtherDelta
https://urlscan.io/result/06c8bdf0-48f3-4fa2-a903-9f0b7f90e9cd/
forkdelta.su
Fake ForkDelta
https://urlscan.io/result/34423533-15a7-4e8c-bd97-6a96eddc3977/
forkdeltagithub.info
Fake ForkDelta 
https://urlscan.io/result/40ea39a4-6fd7-4813-ace3-66aad41ccc0a/
myethrewallett.com
https://urlscan.io/result/5171b40f-b679-4035-ab8e-001f5bc80bc9/
> ethzerdelta.com + more

- blacklists/domains.json
sociall.ooo
Fake Social.io crowdsale site - t.me/sociallairdropbot
https://urlscan.io/result/43e37009-9e35-4d36-b89b-5ac33b3b1453/
ether-gift.website
https://urlscan.io/result/8016c7ef-cc4f-4414-88b6-d155a2dfea1d/
address: 0x52b949fb4678c20873135ce6b3727949432af1d7
authorize-transfer.droppages.com
Trust trading scam site via bit.ly/2ELCNLl+
https://urlscan.io/result/79306081-e1d0-44ff-ae3f-ae1045c31749/
address: 0x5e3eC117baf30044A1b08267208a130E7D69704E
login-binance.com
Suspicious binance domain targetting login
https://urlscan.io/result/81b53d27-384f-406f-90e1-fa8512d8e205/
authhitbtc.com
Suspcious hitbtc domain targetting login
https://urlscan.io/result/1263ba89-6297-446c-8ddf-a0274cb8ef76/
hltbtc.cam
Fake Hitbtc phishing for logins …
> sociall.ooo + more

- blacklists/domains.json
stellar-w.com
Fake Stellar Web Wallet
https://urlscan.io/result/72c75eaf-6f1c-4979-b2eb-21fdf8ca7c52/
bitfinex.im
Fake Bitfinex phishing for logins
https://urlscan.io/result/8b8efb76-488d-413e-a4f0-a58980a6a819/
https://urlscan.io/result/a8c107ca-75dd-438e-9e41-491d10e83d18/
https://urlscan.io/result/0b1e4fdf-371d-4ba5-a3f4-85e1383fff4a/
https://urlscan.io/result/8353c837-48b1-4183-a241-29c27007026f/
> stellar-w.com + bitfinex.im

- blacklists/domains.json
xn--mycypto-xld.com
Suspicious Mycrypto domain - IDN homograph attack domain
https://urlscan.io/result/26d1fef7-070b-405a-8661-403735f400e3/
xn--mcrypto-rpd.com
Suspicious Mycrypto domain - IDN homograph attack domain
https://urlscan.io/result/3da0c170-9267-44cf-a8d9-e3461593119b/
xn--mycrpto-8i4c.com
Suspicious Mycrypto domain - IDN homograph attack domain
https://urlscan.io/result/567e762c-d65b-4cfc-842d-df4cc3f61aaf/
xn--mcrypto-5i4c.com
Suspicious Mycrypto domain - IDN homograph attack domain
https://urlscan.io/result/19728dac-c8ed-4ff1-bc95-5a8b787c216f/
xn--c1arhhdidc.com
Suspicious Mycrypto domain - IDN homograph attack domain
https://urlscan.io/result/7410490d-b3a5-4f46-bcb1-d046caa45be2/
xn--ycrypto-uz3c.com
Suspicious Mycrypto domain - IDN homograph attack domain …
> xn--mycypto-xld.com + more

- blacklists/domains.json
myetherwallet.com.api5.icu
https://urlscan.io/result/e423c6cb-d724-46bd-a0e3-2ace67036892/
nuetheriumllet.com
https://urlscan.io/result/820b403b-9721-4f97-9b76-0cc698185673/
myelhervvalet.com
https://urlscan.io/result/18939730-4948-4058-8b84-378b2bb170c9/
seositesworld.online
https://urlscan.io/result/7bf86e59-f033-4661-8af1-2d5ceca60d5d/
https://urlscan.io/result/049e0863-26db-4154-8449-eab144fa19d5/
> myetherwallet.com.api5.icu + more

- blacklists/domains.json
ethcryptocomp.cx
https://urlscan.io/result/511ccdbb-7838-4b78-9ab8-ee5d87d4b97d/
address: 0xBe3E5cBa8cb230678a7bF5ECdaE37783C8dF89bd
ethpromoui.com
https://urlscan.io/result/a40eeb63-d9c9-4a56-9681-70e09a2fc4cb/
address: 0xBe3E5cBa8cb230678a7bF5ECdaE37783C8dF89bd
ethpromonow.com
https://urlscan.io/result/88c0d14b-6c6c-43c1-a00c-45d4860e273b/
address: 0x8e8f4161c9c3D2D8857230A048DF1Fc6F4326948
eth-give-away-promo.com
https://urlscan.io/result/eb7cd6a8-9530-46e7-a58d-85246f0d0352/
address: 0x14B7716c688875Bcf54D5Ff47cAd4FcA6B3834fA
eth-promo-give-away.com
https://urlscan.io/result/5a1d2736-2b46-4465-9ed1-5aef0d3a3938/
address: 0x14B7716c688875Bcf54D5Ff47cAd4FcA6B3834fA …
> ethcryptocomp.cx + more

- blacklists/domains.json
my-crypto.com
Suspicious MyCrypto domain
https://urlscan.io/result/becbd84e-3666-48d5-9524-138fcb9add6d
my-cry-pto.com
Suspicious MyCrypto domain
https://urlscan.io/result/2f5b313f-f93f-43fc-867d-85c0dde9cf54
> my-crypto.com + my-cry-pto.com

- blacklists/domains.json
fantom-foundation.de
Fake MyEtherWallet stealing keys with POST /eth
https://urlscan.io/result/23259a32-eea6-46f2-b18c-8d5f5f3e02ab
bincomance.com
https://urlscan.io/result/afd6e5b5-217f-4b44-b5dd-5b3f425b0c53/
https://urlscan.io/result/d307b06f-f104-46b4-bcc8-3f2959b10962/
https://urlscan.io/result/6cb33362-e1ed-4874-a5a1-65d433355445/
kraken-authentication.com
Suspicious kraken domain
https://urlscan.io/result/e6a7aac5-e9fc-4466-956a-cc4568ed3c6d/
kraken-we.com
Fake Kraken phishing for logins
https://urlscan.io/result/7270f948-74cd-4e57-9feb-118efa79fb34/
kraken-ix.com
Suspcious kraken domain
https://urlscan.io/result/0c7452cf-e834-487d-b0f5-3a944c1bc94a/
kraken-on.com
Suspcious kraken domain
https://urlscan.io/result/c1143730-4d22-48fd-9898-8c325710bcd0/ …
> bincomance.com + more

- blacklists/domains.json
clubeth.live
https://urlscan.io/result/40fd1fdf-2d33-43a6-938f-cdd246654f13/
address: 0x420eDd527F217b56Ab9b0fdf7A6C553Fe78EB2aa
myethgift.com
https://urlscan.io/result/dfd17208-abdf-416a-8fba-ed2d2d463c09/
address: 0xCBA1E79e47DD511B87Dcc69B279953543d453fC5
clubbtc.live
Trust trading scam site. Bitcoin address: 18dCxtGHAzWbrGBxPQyW4WqSV7N94HQuHt
https://urlscan.io/result/21ec73f2-2634-49a5-9fe9-af1fa93f2c4b/
binance-official.com
https://urlscan.io/result/78dffe72-0356-4e06-a79f-1111f28ecbd6/
https://urlscan.io/result/c42435a3-915b-46f9-a338-15d2cdb5fbaf/
shapeshift-exchange.io
Suspicious Shapeshift domain
https://urlscan.io/result/e19c587c-2f17-44f3-a5e0-c704beacbfd9/
view-wallel.info
Fake EtherDelta …
> clubeth.live + more

- blacklists/domains.json
kraken-ixz.com
Fake Kraken phishing for logins
https://urlscan.io/result/f3e9370a-661c-40c7-9a19-56ddbe04befa/
kraken-check.com
Fake Kraken phishing for logins
https://urlscan.io/result/1c0a2bae-af8b-4c4f-b78b-1b97cd80e2e0/
airdrops.delivery
https://urlscan.io/result/3ebe277c-a5b0-42db-bb96-4d709709be0c/
address: 0xCe9e24Dffdb3DC08EFe33AD3DB858576C3f27D5d
> kraken-ixz.com + more

- blacklists/domains.json
bliovnarnce.com
https://urlscan.io/result/fa4e4f05-fdd5-4c3e-ab30-0b5f837f12e6/
https://urlscan.io/result/10e2733f-5ea1-4c48-83b1-00e8531deabb
meyhferwallet.com
https://urlscan.io/result/db9d7b0c-1295-44f8-b78f-0afb8878d005/
> bliovnarnce.com + more

- blacklists/domains.json
kralkem.com
Fake Kraken exchange phishing for logins
https://urlscan.io/result/419b2765-0235-4b23-bf5f-23e9e7e664e0/
blockchalim.info
Fake Blockchain phishing for logins
https://urlscan.io/result/68f0288a-a08f-418b-8097-fd35eade647e/
neo-tracler.co
Fake Neo wallet phishing for keys
https://urlscan.io/result/02795a3c-b069-40d8-b129-85c65a766e07/
https://urlscan.io/result/d2988f88-6f65-4b95-80d1-322d8878ae8c/
app-bittrex.com
Fake Bittrex exchange phishing for logins
https://urlscan.io/result/672f5a63-bd95-4bb3-9431-a124924f0198/
> kralkem.com + more

- blacklists/domains.json
myehtervvalliet.com
https://urlscan.io/result/998852a6-9c20-4404-8c6f-9e8aaf153364/
myethervvallet.net
https://urlscan.io/result/d2fedfd2-d580-473c-a42a-2180f8598e7f/
myetherwellet.org
https://urlscan.io/result/27fbf4df-2071-4aa3-8574-03f19d2e97da/
kraken-tr.com
Suspicious Kraken domain
https://urlscan.io/result/93c9b890-f942-48d6-9185-e6fc81497f80/
kraken-logn.com
Suspicious Kraken domain
https://urlscan.io/result/9089fdf1-9a2b-49ba-89f4-4517b64882e2/
kraken-sigin.com.ru
Suspiciou Kraken domain
https://urlscan.io/result/445403df-a601-4693-b15c-b151acdf9fa7/
api-binance.co
https://urlscan.io/result/a9cbe649-6f60-4b51-b56a-ef3811c337a1/ …
> myehtervvalliet.com + more

- blacklists/domains.json
accounts-blockchain.info
Suspicious blockchain domain
https://urlscan.io/result/deda84e6-f6c0-42ec-9b3f-9a9169ac0866/
binance.com87654897.ml
Fake Binance phishing for logins with POST /submit.php
https://urlscan.io/result/41635e91-f904-4f77-bbaa-6226f3a74850/
https://urlscan.io/result/31a65816-9192-4147-8210-f5b4083fe4c2
https://urlscan.io/result/0819056a-5af8-4d7c-8dd1-2e5cf32ef0ad
https://urlscan.io/result/c462b09f-493e-46b4-94a7-ec609b6f4bc7
binance-in.com
Fake Binance phishing for logins with POST /indexSend.php
https://urlscan.io/result/c7436d40-bf7b-4019-ab32-dcbebc14ff87/
bittrex-br.com
Fake Bittrex phishing for logins
https://urlscan.io/result/c5584bbf-7180-4dfd-88fc-f202cac834b8/
https://urlscan.io/result/59e90326-c125-402c-8589-493ecbd6450c/
> accounts-blockchain.info + more

- blacklists/domains.json
walletverify.info
Fake DDEX phishing for keys
https://urlscan.io/result/a8552b93-4ca3-44df-9c5f-0cdd2676f0be/
myetherwallet.com.walletverify.info
https://urlscan.io/result/7562ef29-977a-4781-ac9b-2955ba27b9c7/
> walletverify.info + more

- blacklists/domains.json
myethervvallet.pw
https://urlscan.io/result/143cd7af-f9fb-48d0-94d3-c0b5483ea0a6/
https://urlscan.io/result/a0a7f550-807f-4590-a796-b958d866ed41/
myetherwallet.co.za
https://urlscan.io/result/b450ea9e-b9fd-41b2-b5fb-29078c84fdf1/
myetherwallett.fhapp.xyz
https://urlscan.io/result/e1ebff8f-fbb1-4cf5-abb1-683de3ed1416/
web-binance.com
https://urlscan.io/result/2d36def6-08a4-4859-987d-b8996c9ed02f/
https://urlscan.io/result/cf726ea8-b33e-4a04-aead-427b1624ed55/
xn--bittrxx-vya.com
Fake Bittrex phishing for logins with POST /../loginn.php
https://urlscan.io/result/2056085a-ad0a-4767-ba43-13ec25bd32a4/
memonero.co
Fake MyMonero phishing for logins …
> myethervvallet.pw + more

- blacklists/domains.json
biltmex.com
Fake Bitmex phishing for logins with POST /send1.php
https://urlscan.io/result/a64759bd-8a75-4e39-8067-348299f80fcc/
https://urlscan.io/result/9226315a-f67b-46d5-a044-b522e2ef9f6d/
https://urlscan.io/result/49b761d3-7224-4918-aaaa-b210557fc8cd/
lbtsx.com
Hosting a fake Cex.io exchange login phishing for logins with POST /indexSend.php
https://urlscan.io/result/0548c9cd-c0dd-4a05-84b5-c7936637ff70/
xn--bimex-leb.com
Suspicious bitmex domain - not deployed yet
https://urlscan.io/result/9dd986d0-95bc-4370-8e69-1757830f01e4/
bitmex-login.com
Suspicious bitmex domain - not deployed yet
https://urlscan.io/result/5db88041-eeab-48c4-ab59-53cd0bd7d977/
> biltmex.com + more

- blacklists/domains.json
lbitmex-in.com
Suspicious bitmex domain
https://urlscan.io/result/39db4c08-0f60-4ee8-bd22-cf9baf601c1a/
myetalonwindow.info
https://urlscan.io/result/d5eca6ee-691f-4612-b953-95b4cc4bf7a4/
> lbitmex-in.com + myetalonwindow.info

- blacklists/domains.json
blokclnain.com
Fake Blockchain phishing for logins
https://urlscan.io/result/d3605842-c030-46dc-ae91-47ae66a2de60
giftreturn.mysteria.cz
https://urlscan.io/result/f6458d01-724c-4eaf-bd53-f2ccd2ed05cd/
address: 0x7Fc94073a3aDf4553D59D09E0b0808bB9d408735
ethdrop.cn
https://urlscan.io/result/93c04c17-7852-43d7-a665-0d6603f688d9/
address: 0x23E34BBCCB320951D8D5db864ccE0BA9452ae663
giveaways24.info
https://urlscan.io/result/05d9154f-f2c8-4ed1-af01-56a1e2714737/
address: 0xC7a25050f5F067762e070dfBC3198B9DFD6a2Ad1
airdrop-live.com
https://urlscan.io/result/00f7982d-4437-44d8-8a6f-efeb4827f811/
address: 0x2F0D741580d9dBC27E51e5DBe83f5797f868C2e0
grijub.blogspot.com …
> blokclnain.com + more

- blacklists/domains.json
axibovs.blogspot.com
https://urlscan.io/result/877f19a5-56b7-404b-8f4d-93d0a0f00312/
address: 0xc4856c6C04Ee3416dAEaeD3E5abAE3622BBE1eBe
send.ethparty.us
https://urlscan.io/result/4b143611-9823-4cb6-bc93-0dd06e428cfd/
address: 0x8Bb8a410e770a693C169a6b2B5286297d9eccbeD
ethparty.us
https://urlscan.io/result/10f6b73e-93bf-4adb-a251-3a4c14bc0aa1
address: 0xF97Cb2b86deE9C33c7624Fd7412889543cCA7F5A
ethaway.000webhostapp.com
https://urlscan.io/result/7b562473-53b4-46b5-b4ce-3e107837b3f8/
address: 0x44610ceE8C56D34e80468243065e3a319250e32a
blognance.blogspot.com
https://urlscan.io/result/aabcc513-6e01-4462-9a71-083a2da63f8e/
address: 0xc4856c6C04Ee3416dAEaeD3E5abAE3622BBE1eBe …
> axibovs.blogspot.com + more

- blacklists/domains.json
login-coinone-co-kr.com
Suspicious coinone login domain (not deployed yet)
https://urlscan.io/result/b2a954f3-77dd-4fb7-b589-66f9cccc6a56
pumpkinpro.co
Fake ICO (fake team) - https://steemit.com/scam/@iamdeadlyz/fake-airdrops-and-icos-everywhere
https://urlscan.io/result/9836e503-50b4-4797-8013-42aa45d8bc09
> login-coinone-co-kr.com + pumpkinpro.co

- blacklists/domains.json
medium-io.site
https://urlscan.io/result/0dd525be-bfcc-459e-80bb-835d3890daaa/
address: 0x964A7C09E3dB065ece947FdB7f90bf0068a6F98e
claim.safepaycoins.com
https://urlscan.io/result/10ed968e-5e42-4e5c-9aca-3cb64334e5ea/
address: 0x4349B24Ee0Bb23c51569E63B2c1d457Dd75464D7
airdrop-exchange.com
https://urlscan.io/result/1a4394c5-f1d7-42fe-b267-f5668afbda11/
address: 0xcd39300c31776AB6303fC64B930c1109c008eA0A
secure.eth-claim.online
https://urlscan.io/result/29f2e1d3-01f6-4287-a833-454a861656a3/
address: 0x7069BB601755F69c81560192ecC2a62Fed1c20B5
medium.in.net
Trust trading scam site. Directing users to kutt.it/KjHyKL -> giveaways24.info
https://urlscan.io/result/48bbd55a-f1b9-4927-8013-a35b46c6aec8/# …
> medium-io.site + more

- blacklists/domains.json
coinbasesecuritytokens.com
Suspicious Coinbase domain
https://urlscan.io/result/13575392-6133-4d06-9d3a-662411a3b3a6/
coinbasepay.info
Ponzi scheme. Wrong company number 10829913
https://urlscan.io/result/7a23c64a-e4fd-4a0e-b45e-e257e5663022/
hitbtcrecovery.com
Suspicious hitbtc domain
https://urlscan.io/result/20f3f032-c754-4ce8-9c76-813e50f50a29/
hitbtc-ads.com
Suspicious hitbtc domain
https://urlscan.io/result/479ca000-aa45-49a5-9117-213f07c16cbb/
hitbtc-adv.com
Suspicious hitbtc domain
https://urlscan.io/result/da5b52a3-a35b-4363-a41f-c59192d251fb/
gemini-wallet.com
Suspicious Gemini domain
https://urlscan.io/result/738e1c5e-c4f5-47e6-a858-16c1a08d2f7f/
gemini2fa.com
Suspicious Gemini domain
https://urlscan.io/result/3eda48f8-f0a1-4c0a-836c-0330d60fb73f/
geminiaccount.com
Suspicious …
> coinbasesecuritytokens.com + more

- blacklists/domains.json
earn.dailydivs.com
Ponzi scheme - unverified contract - 'This is a game, not an investment. Your profit is funded by new players.'
https://urlscan.io/result/4296df6b-15af-4248-85ed-60df6ef0aed2
https://urlscan.io/result/c3d96e64-5a6a-4c60-b2d5-5f03dd7462fa
address: 0xFaD05ee13c8e0Ec94E5eE9Dc056DC451B2Ad6b1d
safe.minedtokens.com
https://urlscan.io/result/d5888947-ae2d-41cd-907a-44e6d784b08a/
https://urlscan.io/result/e5528161-9c0a-4564-bba9-8e0a7ed0a6d9/
address: 0xF9B14517E630aacc5C9c9429cBE969aa61B3Adc9
address: 0x8Bfe1C609CdF6E7e43C5CD8910Bd566a2C142688
smartsend-5000.website
https://urlscan.io/result/7cd1623f-92e5-40c4-ab08-33be9629ae92/
address: 0x566e797616526498bc274597805F0d4a2682a6a6
airdropeth.tech …
> earn.dailydivs.com + more

- blacklists/domains.json
cryptoeth.live
https://urlscan.io/result/592b615c-eac7-41d2-9622-27dfff03c5df/
address: 0x504c839dB36171D13f1B78Ab323CF3eA084995FA
crypto-win.club
https://urlscan.io/result/337e879f-8891-4515-b930-e9337cf924ee/
https://urlscan.io/result/bbe46dd3-5dd9-459f-825a-bf3d9d7ccc65/
address: 0x5c5452D1a4FB7175812de3b4a4F1c34D5Bc5a261
crypto-medium.com
https://urlscan.io/result/f639b597-ca74-4cc9-8a21-38a6b422cbe4/
https://urlscan.io/result/9b94ac59-8337-4891-83d1-ebe6fa1c41dd/
address: 0x520C7DD3d265B6eDd88C623D4C9EddAcBf082eA6
getairdrop.eu
https://urlscan.io/result/26af60e1-11a4-41c7-b203-65a659386a0d/
address: 0x362f1d7C705f0d8f38786b4D6eFd6eCC54199be6
sending-smartcontract.website
Trust trading scam …
> cryptoeth.live + more

- blacklists/domains.json
trxgold.io
Fake airdrop site with KYC directing users to a fake MyEtherWallet signature.xn--mytherwalet-3qb10c.com with cli.re/signed
https://urlscan.io/result/cb988b10-2e07-47e6-b44c-c5579fde7fa2/
signature.xn--mytherwalet-3qb10c.com
Fake MyEtherWallet stealing keys with POST /process.php
https://urlscan.io/result/0c2144e9-924f-4324-8426-caa97066ef4f/
blockchian-login.info
Suspicious Blockchain domain
https://urlscan.io/result/34dfbc1f-ffa0-4539-aa9a-fc945616f8c0/
login-blokchain.com
Fake Blockchain phishing for logins
https://urlscan.io/result/c5c7fee1-06be-479b-9fc8-db4c8b034568/
https://urlscan.io/result/89cea23c-0ee4-49d8-8657-6a979e32f119/
login-blockchian.net
Suspicious Blockchain domain
https://urlscan.io/result/e273939d-293f-42bd-91b9-a325d425eaab/
blockchian-wallets.com …
> trxgold.io + more

- blacklists/domains.json
gramnetwork.net
https://urlscan.io/result/039b6587-8161-43da-aa5e-3637373593b2/
https://urlscan.io/result/7e2c749f-4290-462a-90f7-6f49b1a92461/
address: 0xf94b8e0ceba6dcd1b888fe02141dd9d0b8e67715
> gramnetwork.net

- blacklists/domains.json
Promoted by a twitter account with ~1m followers / twitter verified.
https://twitter.com/givenchy/status/1043222585637515264
Trust-Trading - Urlscan - https://urlscan.io/result/c91d2d60-e5bb-4544-9c17-9d9dd2c88f71
> Added - bcrypto.club

- blacklists/domains.json
hitbtc.li
Fake HitBTC phishing for logins with POST /phone.php and POST /sms-code.php
https://urlscan.io/result/5f1e05dd-3d06-4f46-a9b7-6ff7aa52a361/
https://urlscan.io/result/9f4186c3-fe31-499f-86c2-57d987f1cf6e/
https://urlscan.io/result/d85e766f-1bd0-46a4-abed-277eabfa56ea/
xn--spectroconn-7zb.com
Fake SpectroCoin phishing for logins with POST /../post.php
https://urlscan.io/result/be2f65f1-4211-457d-809f-cfdcd94ea49c/
https://urlscan.io/result/b94fe136-fde1-43d0-84fe-a44953399c35/
paxfullwallet.com
Fake Paxful wallet phishing for details
https://urlscan.io/result/9d09740b-b982-48f6-ab7d-ce6a34c16fb9/
user.paxfulpolicy.com
Fake Paxful site phishing for details
https://urlscan.io/result/8365f7cf-9a0d-49f9-81e5-0cef2b73a23e/
paxful.com.balums.gq
Fake Paxful site phishing for details …
> hitbtc.li + more

- blacklists/domains.json
myetnerwallet.com.send-status.info
https://urlscan.io/result/a852572e-682a-4098-a7c3-95054eea162d/
send-status.info
Fake EtherDelta phishing for keys with POST /callback.php
https://urlscan.io/result/88c965e5-f68c-4dec-a770-d1a9169b6be8
paxful.com.pl
Fake Paxful exchange phishing for logins with POST ./temp.php
https://urlscan.io/result/59fda966-f84c-4f1c-b689-3076c7b7084e/
myetherwallet-id.space
https://urlscan.io/result/e259c810-4c57-445c-acdf-a06235cf2884/
eth-databasecontract.website
https://urlscan.io/result/f24bc62a-9635-4285-8d05-c47b49e29703/
address: 0xc57597f5fC469386AB8C53740b5Cf6c4A78e8EeC
geteos.eu
Fake EOS site phishing for keys with POST / …
> myetnerwallet.com.send-status.info + more

- blacklists/domains.json
send-gift.website
https://urlscan.io/result/e3cefa35-81c7-4a95-9ac1-a0501efb995f/
address: 0xd9a1968Aec13220e91A31D602f2519262B38dD3A
etherium.org.payment.7t24-srv.site
https://urlscan.io/result/03ce9812-9595-4b28-b4c1-9a7f48a9d961/
address: 0xff0e20E3A7575D823302bbB27E233c23f2c3070b
medium.com.7t24-srv.site
Trust trading scam site. Linking users to etherium.org.payment.7t24-srv.site
https://urlscan.io/result/c07e0215-137a-4b4a-8bc7-b7faeba5cf22
address: 0xff0e20E3A7575D823302bbB27E233c23f2c3070b
airdrops.technology
https://urlscan.io/result/f86028e9-5876-46b9-8e97-d44f92b472f6
address: 0xB1843d1Eb962dA7760A80fC91B442491cf437492
myetherwallet-cpt.space …
> send-gift.website + more

- blacklists/domains.json
binance.com6537261.ml
Fake Binance phishing for logins with POST /function.php
https://urlscan.io/result/5713f0c5-594f-4cab-bef2-bcbbeac1aed9/
binance.com762381.cf
Fake Binance phishing for logins with POST /function.php
https://urlscan.io/result/5fe05bc5-7b90-4752-b7f6-15d19d0eec8e/
vitalik-campaign.xyz
Trust trading scam site. Bitcoin address: 1DzUBk8PDjQKdBgo5YG4qzk6icCH3GaPxJ
https://urlscan.io/result/539137c8-fdda-429f-8e4a-547ffb5db6c5/
https://urlscan.io/result/90c30e66-16c7-44cc-917c-0529f73ff780/
address: 0xe45AA28d270A049B489CcbB156C2e2c3De0d571d
getgift.tech
Trust trading scam site. Bitcoin address: 13Lo1Pjh8DKpq9Fvf5aNb1hfnHVDxQBoqE 19w6pZoUKTKzEtFZQJNnV6RjztPbFU8xSV
https://urlscan.io/result/45d6335f-6380-44fd-8506-2df658e6667d/ …
> binance.com6537261.ml + more

- blacklists/domains.json
paxful.com-bitcoin-wallet-trade-escrow.paxfulsecure.com
Fake Paxful phishing for logins with POST /login.php
https://urlscan.io/result/b7ea3da1-5e07-490c-a412-98d2b603e38f/
mnyicthervallict.com
Fake MyEtherWallet phishing for keys with POST /log.php
https://urlscan.io/result/7ab5af27-0cbd-4bff-9eaf-4098a625bb6a/
mnyidthewalliot.com
Fake MyEtherWallet phishing for keys with POST /log.php
https://urlscan.io/result/a854ec38-56c0-4d4c-880c-19eff8af82e1/
binchaincampaign.com
Trust trading scam site. Bitcoin address: 36CfVjvns6ce1ijpdKB8YKeBVzVpxCfRrH
https://urlscan.io/result/a140f939-4dac-4f05-8773-ecac1cb3da6d/
https://urlscan.io/result/eb9ac249-fe28-4683-8bd5-2b48897e0fc3/
binachaincompetition.com
Trust trading scam site. Bitcoin address: 36CfVjvns6ce1ijpdKB8YKeBVzVpxCfRrH …
> paxful.com-bitcoin-wallet-trade-escrow.paxfulsecure.com + more

- blacklists/domains.json
electrun.org
Stealing phrases with POST /check.php
https://urlscan.io/result/4d282fc0-6beb-4d2f-aab0-d21e01efc400
> electrun.org

- blacklists/domains.json
hitbtc.pratiktlyukleme.com
Fake Hitbtc phishing for logins (and email passwords) with POST /index--_.php
https://urlscan.io/result/e765ba95-72d8-42d7-a8d7-2ff194e3ad0b/
https://urlscan.io/result/986e280f-30c6-4911-b1c9-798c137c16fa/
https://urlscan.io/result/97f07f9c-751b-4b56-b948-34c7d832abd0/
https://urlscan.io/result/a2063477-b41e-412b-be61-c944483055e6/
https://urlscan.io/result/834c522a-83a9-4f80-a1ba-34c2bbd755a2/
https://urlscan.io/result/828ed034-50c3-4096-bc71-59863281cdce/
xn--mercaox-rrb.com
Fake Mercatox phishing for logins with POST /auth/ajax_process.php
https://urlscan.io/result/32320fc4-fb7f-4f72-b11d-affdeed9988e/
https://urlscan.io/result/16f756d9-9149-4901-9c34-74dab7332776/
xn--phld-rqa7a.com
Suspicious uphold domain …
> hitbtc.pratiktlyukleme.com + more

- blacklists/domains.json
ehitbtc.com.viptempobetgirisi.com
Fake HitBtc phishing for logins with POST /index--_.php
https://urlscan.io/result/de4e77e1-8cd1-4ae8-b87d-159cc40b43e2/
https://urlscan.io/result/15c6fb4e-2a54-4091-ab71-387a4f3ccb42/
> ehitbtc.com.viptempobetgirisi.com

- blacklists/domains.json
xn--blocchn-4ya8tls.com
Fake blockchain phishing for logins with POST /wallet/sessions - api_code = 1770d5d9-bcea-4d28-ad21-6cbd5be018a8
https://urlscan.io/result/c31eb602-0191-464d-9104-b28bec33eb30/
xn--myeterwaliet-fs4f.com
Suspicious MyEtherWallet domain (Apache2 default page)
https://urlscan.io/result/25fb980e-6e75-492a-8799-4d8bfab157ef/
xn--myeherwallet-fpc.com
Suspicious MyEtherWallet domain (Namecheap default page)
https://urlscan.io/result/5043650e-1eb7-44f1-9f91-d460094d1e44/
xn--blockhan-w0a6d.com
Fake Blockchain phishing for logins with POST /wallet/sessions
https://urlscan.io/result/4da5cd5d-0cc1-4d28-8df9-e363cbb81ce6/
xn--bockhain-v0a06f.com
Fake Blockchain phishing for logins with POST /wallet/sessions
https://urlscan.io/result/b4da9a59-488f-4897-8a24-d68bcb4f46d6/ …
> xn--blocchn-4ya8tls.com + more

- blacklists/domains.json
cryptoblackfriday.blogspot.com
https://urlscan.io/result/e6cd0329-70bf-4e36-b779-1a54644d4633
address: TPcDNYz4AxCaLCY2Xx4i95jGYwCjUrxg5r
freecryptogift.org
Trust trading scam site. XRP address: rCozquBhPba8D4hnCJh5DzJVZxZtNFGbV 
https://urlscan.io/result/ab41fd9d-14a2-4b5f-a4db-e5e5d8280114
https://urlscan.io/result/12440fe7-21c9-4dd6-aaa3-4263cbce7b20
https://urlscan.io/result/4375a548-e24d-4d48-8f0b-7219603b8e07
https://urlscan.io/result/629a4dbd-eac7-41ee-b7ee-beed0cd50aac
address: 189p87dMz7FeFdp98AGkmYo4ScMYgqUAkh 
address: 0xC82e2dfC140FB5D94B612af056c45d08C6560c84 
tronblackfriday.blogspot.com
Trust trading scam site.
https://urlscan.io/result/fe6020b4-6a5a-45a3-bc6f-ad7c14f3353b/
address: TPcDNYz4AxCaLCY2Xx4i95jGYwCjUrxg5r
btc-gift.tech
Trust trading scam …
> cryptoblackfriday.blogspot.com + more

- blacklists/domains.json
medium-ether.com
https://urlscan.io/result/c84f0df4-5443-4ac3-96bb-cdd619ffda60
address: 0x9068327FF0f5E99aF7D1AEfC5310e4560C32b84B
gift-btc.net
https://urlscan.io/result/083ee581-7df5-4d21-8857-fafc84d57e13/
address: 18oVCJ1h7MzpPk899FJiTWRb7Wm3FU8fjS
myetnerwallet.com.application-send.info
Fake MyEtherWallet phishing for keys with POST /callback.php
https://urlscan.io/result/320822ff-19c3-4f6d-b6cb-473227f43fe1/
application-send.info
Fake IDEX phishing for keys with POST /callback.php
https://urlscan.io/result/acb80e9c-f66a-4d4b-911c-df58d23cd485/loading
mediumz.top
https://urlscan.io/result/16a11a96-eaee-442d-9b98-cf10b030a6e4/
https://urlscan.io/result/dd1bf135-4a93-4c98-ae4e-0fd9459f1a6e/
address: …
> medium-ether.com + more

- blacklists/domains.json
blockchain-update.bounceme.net 
Fake Blockchain phishing for logins with POST /next1.php
https://urlscan.io/result/3a210119-fdb9-4d97-ac9c-f9965e2d2b9c/
coinbene.net 
Fake Coinbene phishing for logins with POST /login.php
https://urlscan.io/result/b6436adb-2b8d-40f5-a57a-ee674014d77b/
https://urlscan.io/result/b8d1f25c-5edd-4d76-a928-bf6085559efd/
---
coinbase-pro.org
https://urlscan.io/result/78799b36-b501-472b-8b38-e52d16e2028f/
address: 0xd6F1739aF2e63575F2df02af59F23F643EAe3403
> blockchain-update.bounceme.net + more

- blacklists/domains.json
tronkucoin.blogspot.com
https://urlscan.io/result/59db98d8-f61b-4e74-b853-6153d7ed7c4f/
address: TPcDNYz4AxCaLCY2Xx4i95jGYwCjUrxg5r
> tronkucoin.blogspot.com

- blacklists/domains.json
bitcashsv.org
Fake BitcoinCashSV splitter and email harvesrer
https://urlscan.io/result/f6a22947-7126-4faa-bdf7-b9fa9d3a81ec/
address: qp9rk7fg4avwlu6cf88qq3533g0qyvwh7y78vf4wrk
> bitcashsv.org

- blacklists/domains.json
bittlrex.com
Fake Bittrex phishing for logins with POST /Account/Login
https://urlscan.io/result/e05e7cce-056a-4ae8-be8a-4059729ad1b8/
https://urlscan.io/result/9b3843c9-cb8f-4bd9-9c87-e1e7a72f37d1/
xn--binnce-rhc.com
Trust trading scam site - linking users to www.binance.exchange2018.support/event
https://urlscan.io/result/dbd027bf-21b2-44ca-9e40-caa6aa336120/
address: 3HzQJ3CGQKkWuxGSiWW286PePSed7tgKWp
binance.exchange2018.support
https://urlscan.io/result/307d137b-93d9-4a07-8fa7-c78ec8ea438c/
https://urlscan.io/result/771cae8a-4b00-400e-a194-168a458c3479/
address: 3HzQJ3CGQKkWuxGSiWW286PePSed7tgKWp
binancehelpdesk.com
Fake helpdesk harvesting user emails
https://urlscan.io/result/84cdf127-f04d-46dd-a846-7c7791157b1a/
pumapay.io.giveaway-user.com 
Fake …
> bittlrex.com + more

- blacklists/domains.json
coinbase-airdrop.top
https://urlscan.io/result/5797f848-6bce-494b-9965-9b2d6cd291ad/
https://urlscan.io/result/72943f79-196d-4ca6-98eb-a9c5051c727b/
https://urlscan.io/result/79cf52d8-9f84-4524-92bb-85d1e46a8649/
address: 1MpLjpT44A5yyRbtGG61rtpgwxdJB3onsB
coinbase-btc.xyz
https://urlscan.io/result/8587b1af-4500-4653-b741-3d5d1a35ffc8/
https://urlscan.io/result/b38627e4-3ea1-41db-adf0-46c3734794e6/
https://urlscan.io/result/140e9ae1-4fdd-4868-954f-168f4737b77d/
address: 1MpLjpT44A5yyRbtGG61rtpgwxdJB3onsB
kucoindectrx.blogspot.com
https://urlscan.io/result/c01ea702-9d1c-4cce-9382-1f69b7bd5843/
address: TPcDNYz4AxCaLCY2Xx4i95jGYwCjUrxg5r
jaxx.im
Fake Jaxx download - …
> coinbase-airdrop.top + more

- js/options.js
- manifest.json
- options.html
- settings.html
* Modified PhishFort repo link for blacklists
* Added Quiknode affiliate link
* Added link to EtherScamDB
> Link fixes

- blacklists/domains.json
newyearcrypto.blogspot.com
https://urlscan.io/result/b6adfa3c-78e3-46fa-91ef-3b7d448290fc/
https://urlscan.io/result/c3cbce1c-9e35-42fc-96a2-175a81bf623f/
https://urlscan.io/result/0925f917-653e-450b-bc25-c206d633f42a/
https://urlscan.io/result/5c5b9c93-b945-46b1-bc73-da784c4f1baf/
address: Ae2tdPwUPEZGpHCMV2L7iMY4vUGX6Pzx5U2YgQD1wK7ZUzKVmgg5RRmp2dF (ada)
address: TPcDNYz4AxCaLCY2Xx4i95jGYwCjUrxg5r (trx)
address: 0x55B775Ea2CA493c082F3e17A8433e4D220FBB8d8 (eth)
address: 1JSeDGPmq74JP2RQXqJFdHH3L2jcie3w4X (btc)
> newyearcrypto.blogspot.com

- blacklists/domains.json
Attempts to mislead people into believing it is facebook. Submitting KYC documents/creating profiles. 
https://urlscan.io/result/dc659205-ab61-428a-a88f-d5de154173cc
> Added faceusd.com

- blacklists/domains.json
bintrx.blogspot.com
https://urlscan.io/result/ff739523-b6e8-4a76-af56-7cbb7d8d0875
address: TRyZs5aTpVrS6ZgWb1NxCnGjktxHYtrD1F (trx)
bin-ance.blogspot.com.tr
https://urlscan.io/result/ed04e87b-576e-4574-9394-9d8881a892cc
address: 0x55B775Ea2CA493c082F3e17A8433e4D220FBB8d8 (eth)
binaxrp.blogspot.com
https://urlscan.io/result/0b0e4e5d-1558-4768-8a44-bcdccda29a0c
address: rne6bY8h8SFEdvSezLADvVDfTiAcVov6js (xrp)
itubeonline.com
Fake KyberSwap HTTrack signature
https://urlscan.io/result/2c1def52-017c-4069-9682-db240d9b8c70
> bintrx.blogspot.com + more

- js/DomainBlacklist.js
- js/options.js
* Fixes the icon title after visiting a bookmarked domain and navigating away to another domain that is not bookmarked
> Icon title fix

- js/DomManipulator.js
- js/app/rpcNodeSelector.js
- js/options.js
- options.html
- settings.html
* Added RPC details and identifiers based on network id
> RPC change fix #1089

- blacklists/domains.json
dexbetalaunchcampaign.com
https://urlscan.io/result/89549e51-e08c-48cd-a839-c367e343ed06/
https://urlscan.io/result/e3582515-109d-48d3-a8f8-ac870a3e17e5/
address: 0xB74Cb9e1defDE24b499b3ca01300c6F7ba53edE7
bitcoin-btc-adder.com
Fake Bitcoin generator
https://urlscan.io/result/8d03d9c5-de38-46dc-8de3-6bfaad7e7652/
https://urlscan.io/result/ca5cdf8a-f6e5-4e4a-b23f-b0249ebf3ea4
constantinopleplus.tech
https://urlscan.io/result/e13388ef-d780-4692-a5f9-2afc6c6f9803/
address: 0x80f43E67169c917c68391F823FcFf41b9B786D69
tokensico.online 
Fake Ethereum wallet phishing for secrets with POST /send_private_key.php - suspected address: 0x48a17df119f20d50b829f15e43e0e59a658c7476
https://urlscan.io/result/a0bdc099-311a-4588-baf9-3b1e14ef5acb/ …
> dexbetalaunchcampaign.com + more

- blacklists/domains.json
crypto-promo.com
https://urlscan.io/result/52e13833-716e-476a-9c9d-2a7de7eeec22/
address: 1M71ywatR8TCZQqS61Rh3soEn4eiEaDKoN (btc)
address: 0x71D663DE2Df38D61A1871Bb8eF503d18D19964d6 (eth)
giveaway-btc.net
https://urlscan.io/result/5518e59e-8fb3-4db8-9887-340891fa60f0/
address: 1WsvoEkx1rTq9c61U68UxAKsdNi5X7AJT (btc)
promocrypto.net
https://urlscan.io/result/925175e3-8464-43d0-b00f-13f7c048a5ec/
address: 1M71ywatR8TCZQqS61Rh3soEn4eiEaDKoN (btc)
address: 0x71D663DE2Df38D61A1871Bb8eF503d18D19964d6 (eth)
binancev2.live
https://urlscan.io/result/5d645c36-4dcb-4aae-b2ca-3b7d67d181ab/
address: 1Q7TjFii9fPj1gnXMXkssjDkTFniXEjYBZ (btc)
binance-btc.neocities.org  …
> crypto-promo.com + more

- blacklists/domains.json
eth giveaway impersonating binance.
> eventbinance

- blacklists/domains.json
bakktlaunch.com
https://urlscan.io/result/6c06782e-0239-4b27-b20e-36c5f99bbe94/
https://urlscan.io/result/36083738-6cbe-4f05-a881-74ff41966f71/
https://urlscan.io/result/cbe721da-440d-486b-9468-314f8b341561/
address: 18hYaDXFpx7zfKb8mo62gyScmwZGEoBDnE  (btc)
address: 0x7A2BB19483e0df6fC7D5159e2F70480CfeF4C50A (eth)
newcryptogift.com
https://urlscan.io/result/de04f512-6b27-4ea4-ae3a-c11f7e8234a1/
https://urlscan.io/result/54f8298c-dbe5-41d8-a7d5-b6ac72ae981f/
https://urlscan.io/result/46af9033-ab57-4922-9959-8d8cca285b8f/
address: 1PvTkqAPqscdZkt1sVLg2mvAhi6NqbJ53N  (btc)
address: 0x032Fb380D84917D408EA172383Cf214c28b4fE21  (eth)
dex-get.net
https://urlscan.io/result/ccb4697a-753f-4968-bfed-d599423e2c2c/ …
> bakktlaunch.com + more

- blacklists/domains.json
- whitelists/domains.json
privatex.io
https://github.com/409H/EtherAddressLookup/commit/29ee9a9c274debe320b0a91fc57afcd4a59ac70d#commitcomment-36234318
> privatex.io

- js/DomainBlacklist.js
- js/options.js
- manifest.json
- static/phishing/phishing-notices.js
- static/phishing/phishing.html
* Updated default node to work with correct responses (Quiknode node subscription ended)
* Added logic to blacklist domain and path (ie: youtube videos and telegra.ph posts)
> Domain path blacklist

- blacklists/domains.json
stellar.org.sb is a phishing site conducting a staking scam to collect stellar secret keys
> Add stellar.org.im

- blacklists/domains.json
stellar.org.lv is a phishing site conducting a staking scam to collect stellar secret keys
> Add stellar.org.lv

- blacklists/domains.json
This is a phishing site collecting secret keys
> Adding stellarpay.org

- blacklists/domains.json
Added stellar.org.mu and s3-stellar.org domains
> stellar.org.mu
