js/DomManipulator.js
js/app/chooseBlockchain.js
js/options.js
manifest.json
options.html

* Adds the feature to choose your preferred blockchain explorer - this will be used upon tab refresh. Currently, only 2 explorers are supported, but it's easy enough to add more in the dropdown.

[ FEATURE ] Choose blockchain explorer {release}

---

js/DomManipulator.js

* Whitelists `<li>` element to search and match HTML tags.

[ HOTFIX #6 ] Added li to the whitelist {master}

---

package.json

This will allow other projects (like MetaMask) to import the blacklist as a dependency via npm, and automatically get your updates when you update the repo.

Add package.json for npm installation of blacklist

---

js/DomManipulator.js
js/DomainBlacklist.js
manifest.json

Moved the blacklist domain logic to `document_start` runtime so that it doesn't wait for the entire document to load before it checks the domain, this solves some issues with sometimes not redirecting users on a blacklisted domain (like 1 in 50 refreshes) and detection is faster.

Blacklisted domain detection on document_start

---

whitelists/domains.json

Currently ethermine.org is getting erroneously blocked. In order to avoid our sites from getting blocked in the future please add them to your whitelist.

Whitelist etherchain.org, ethpool.org, ethermine.org & ethernodes.org

---

whitelists/domains.json

Etherplan is a global wealth management network on Ethereum.

Adding etherplan.com www.etherplan.com to the whitelist.

---

whitelists/domains.json

Somebody reported that MetaMask is blacklisting this site. I'm the owner and I can testify there's no phishing or malware: no registration needed, no redirecting to other urls.

Added steem.supply to white ilst

---

whitelists/domains.json

Ethex.market is a new distributed exchange DApp. Currently only fully deployed on Ropsten. Works as a registered parity dapp (in applications tab), or with Parity Chrome extension at ethex.market or with metamask Chrome extension at ethex.market. Metamask is very slow on ropsten. Should work in Mist, but we haven't tested it at all.

Add erroneously blocked domain (ethex.market)

---

js/DomManipulator.js
manifest.json

If you are on your favourite blockchain explorer, links won't open in a new tab.

Issue #35 - target _blank changed on blockchain explorer

---

whitelists/domains.json

At Maecenas we're doing a crowsale which starts at 5th sept. I'm adding Maecenas and CofoundIt urls to the list of valid domains

Added Maecenas and Cofoundit urls

---

blacklists/domains.json

Phishing via Google Ads.
Source:
https://twitter.com/lmcuende/status/905508311444987905

Add bittirrex.com

---

blacklists/domains.json

Impersonates kyber.network
As reported on MetaMask support center.

Add kybernetwork.io to blacklist

---

blacklists/domains.json

Fix typo about myetherwallet.north, 
blacklist request-network.com (ongoing phishing on our slack)
The REAL website is https://request.network  (see our blog : https://blog.request.network/)

blacklist request-network.com

---

blacklists/domains.json

https://urlscan.io/result/499b0170-b71d-4ec4-b1a4-8382025c5a83#summary
impersonating to privatix.io. This is the 5th impersonation in a few days.

Adding privatix.me to domains.json

---

blacklists/domains.json

The proper owners have regained control of the domain name. The site is back up, and secured again.
https://www.reddit.com/r/EtherDelta/comments/7lf9ni/psa_site_has_been_restored_and_secured_official/

Remove etherdelta.com

---

blacklists/domains.json

Fake EtherDelta domain - hosted on the same server as the fake powrledger.io/airdrop/ domain. Assuming bad actor.
https://urlscan.io/result/83fd9bac-ed49-411e-b534-b4ecb6681c64#summary

etherdelta.pw

---

whitelists/domains.json

Update domains to include http://crowdstart.capital, the website of XSC and Crowdstart Capital, an incentive scheme for the blockchain ecosystem.

crowdstart.capital

---

blacklists/domains.json

1. Website not available, https://urlscan.io/result/6bbbc757-947f-4c6d-bff9-234b7a935f56#summary
2. https://www.whois.com/whois/zenprolocol.com

Adding zenprolocol.com to blacklist

---

css/app.css
js/DomManipulator.js
js/app/rpcNodeSelector.js
js/app/toggleAddressLookups.js
js/options.js
manifest.json
options.html
settings.html

This feature lets you make EAL use your own RPC node (which is used for the onhover address to get the address stats (https://github.com/409H/EtherAddressLookup/releases/tag/v1.12)). This will allow for the option for stats to be fetched from the various testnets.

Custom RPC nodes

---

blacklists/domains.json

Incorrectly blacklisted.
Closes https://github.com/409H/EtherAddressLookup/issues/260

vechainfoundation.com

---

whitelists/domains.json

More details on Chronologic and the DAY token - [https://chronologic.network/](https://chronologic.network/).
Mainnet address: https://etherscan.io/token/0xE814aeE960a85208C3dB542C53E7D4a6C8D5f60F

Added chronologic.network to the whitelist

---

blacklists/domains.json

This is a phishing site of wanchain.org used has ico sale, the ethereum address is 0xd9D25DcE4c3765855c76F3d2BAccc0755C4d0bc5
Screenshot: https://i.imgur.com/4q1ItNv.jpg

wanchainltd.org

---

blacklists/domains.json

Fake blockchain.info website
urlscan cannot resolve it, neither can I.

block.chaiins.in

---

blacklists/domains.json

decentral.market is a fake cryptocurrency news website that posts articles from other sites. When it copies ICO participation guides, it replaces the contribution address with a different address.
Example: [Arcblock](https://decentral.market/2018/02/03/how-to-participate-in-arcblock-token-sale/) and [Republic Protocol](https://decentral.market/2018/02/03/how-to-participate-in-republic-protocol-crowdsale/) have the same Ethereum address (0xdefb014b9e2f3bd81cdb084821f99b681cfca695).
https://urlscan.io/result/13e72351-ec0c-4ea0-89b4-c2b9e3031197#summary

Blacklist decentral.market

---

css/app.css
js/DomainBlacklist.js
js/options.js
manifest.json
options.html

* Re-arranged blacklisting/whitelisting check logic.
* Converted the `getWhitelistedDomainsFromSource()` method to async returning a promise.
* Whitelistes will refresh every 300 seconds.
Fixes https://github.com/409H/EtherAddressLookup/issues/262

Fix whitelist bug that redirected to warning page

---

blacklists/domains.json

Adding fusion-ico.com to blacklist. See https://urlscan.io/result/a5711040-fdd0-4a4c-b3d4-1b4ff6e96924#summary. The valid link is https://fusion.org/.

Adding fusion-ico.com to blacklist

---

blacklists/domains.json

See https://urlscan.io/result/04cd85b7-6530-4944-af28-197cdee50eb3#summary. The actual site, https://fusion.org/.

Adding fusion.tokencrowdsale.online to blacklist

---

blacklists/domains.json

New coindesk phishing site - https://www.xn--coindek-873c.com/ (appears as https://coindeşk.com/ - mind the "ş"!)

xn--coindek-873c.com

---

blacklists/domains.json

New MEW phishing site: https://xn--yetherwalle-tv8ezt.com/ (ṁyetherwallet.com - mind the "ṁ"!)

xn--yetherwalle-tv8ezt.com

---

blacklists/uri.json

Fake Airdrop for Salt Lending.

Salt Lending airdrop phishing in google forms

---

whitelists/domains.json

False-positive blacklist
https://urlscan.io/result/69e2e9a1-1897-4342-a71e-d47dbb104c08#summary
Fixes https://github.com/409H/EtherAddressLookup/issues/362

zycrypto.com & crypto.cat

---

blacklists/domains.json

.ru site is hosting a fake desktop app download, presumably a miner. I don't have a sandbox to detonate in.
.ng site is in-progress build of presumably a new airdrop phishing site.

Two more SALT pages

---

blacklists/domains.json

See link, https://urlscan.io/result/cfa1c0a9-437e-4cf1-8ae9-9296cc2f74b5#summary.

Adding telegramnetwork.org into blacklist

---

blacklists/domains.json

See link, https://urlscan.io/result/e64c78b2-c870-4ca1-9fd9-002c2d49237c#summary.

Adding ethopen.com into the blacklist

---

whitelists/domains.json

Hello, 
We are a new coin launching on the 31st of this month. 
Hello,
This is incorrect. https://myegemwallet.com/ is not a fake - it is our live site for EGEM wallet.
We are launching EGEM on the 31st.
https://github.com/TeamEGEM
https://egem.io
Please contact us for more info.
Thanks,
TeamEGEM
https://github.com/409H/EtherAddressLookup/issues/399

Adding myegemwallet.com + egem.io  to whitelist

---

blacklists/domains.json

See link, https://urlscan.io/result/3c86facf-d9ee-4293-b7ab-150b31015e71#summary.

Adding cryptoplus.be into blacklist

---

blacklists/domains.json

See link, https://urlscan.io/result/9747bc1c-4877-4869-82f4-ce178fa7f9c5#summary.

Adding tron-giveavay-weeklyreport.bitballoon.com into blacklist

---

blacklists/domains.json

The twitter eth giveaway onslaught continues, these guys are hitting dozens of ICOs, here are the latest domains in use.

More giveaways

---

blacklists/domains.json

https://urlscan.io/result/0083e3ab-1749-4aab-9896-2a2d05d578d7#summary
https://urlscan.io/result/e4bf722e-4bde-453e-89ee-dcbb138f5cb1#summary
address: 0xe00e1f7117a69c34694ac1815177c93491fc448f

ethereum-give.byethost16.com

---

blacklists/domains.json

Fake origin crowdsale site
https://urlscan.io/result/e43b12e1-bcf8-4b11-89dc-88c699c51443
https://urlscan.io/result/3f626d6c-3315-4b68-a76c-895a2cca1de6
address: 0x0d4f74c538613ed6e6c8c1bc8896ecfd45f5ef23

originprotocols.com

---

blacklists/domains.json

https://urlscan.io/result/26dadd21-312c-462c-bb38-81188154c2ab

clo-airdrop.info

---

blacklists/domains.json

Trust-trading scam site (promoted by a fake swarm city twitter account https://mobile.twitter.com/Swarm_CityDApp 988059498169491456)
https://urlscan.io/result/b37cbed9-f785-40f1-851a-538c7bad9b88

eth-airdrop.online + ether-giveaway.atspace.eu

---

blacklists/domains.json

Phishing site from scraping of our company website.  This is just yet another iteration from what we believe is the same group behind the attacks on SALT Lending.

Added work.nelsconsult.com.ng

---

blacklists/domains.json

i-idex.market
Fake Idex phishing for private keys. Sends off to POST http://176[.]122[.]20[.]15/sendkey
https://urlscan.io/result/5afc9f77-2d82-405e-956c-691432b92f78/
https://urlscan.io/result/23d70a91-6aee-436d-8145-b7451adaff37/
forkdelta.net
Fake ForkDelta GUI
https://urlscan.io/result/51dee6ed-de25-44ce-b2b1-cd33b9a59849/

i-idex.market + forkdelta.net

---

blacklists/domains.json

promo-give-ethereum.org
Trust-trading scam site. Promoted by Twitter ID: 992951433690398720 (@Aurora_dao_)
https://urlscan.io/result/9cfea787-9e9c-4308-ac22-6ab050e87034/
address: 0x7D922A4f7F24fFcb130c4EEAF291A6475e3e4Dd2
give-ethereum.org
Trust-trading scam site. Promoted by medium-give-ethereum[dot]org and Twitter ID: 992951433690398720 (@Aurora_dao_)
https://urlscan.io/result/407e88cd-8108-4192-8053-8ef3836dcca8
https://urlscan.io/result/265b0fbe-0276-4253-8843-c393d3e475ad/
address: 0x7D922A4f7F24fFcb130c4EEAF291A6475e3e4Dd2
ethereum-giveaway.site
Trust-trading scam site. Promoted by Twitter ID: 132293081 (@Aurora___dao)
https://urlscan.io/result/e107a9cd-bc1b-41f7-8f39-c51c4d2749c5
address: 0x299628fD380813622305517E64eee89BB6a49Ca3 …

promo-give-ethereum.org + more

---

js/DomainBlacklist.js
js/app/toggleBlacklistDomains.js
js/options.js
manifest.json
options.html
package.json

* Added logic to blacklist all punycode domains. This will help tackle phishing in a big way as we are seeing a lot of IDN homograph attack domains on places such as coinbase, poloniex, mycrypto, and myetherwallet.
* This block is toggable, but by default it's turned on.
* Adjusted edit distance for `myetherwallet.com` from 7 to 5 to prevent a lot of false-positives.

Blacklist punycode domains

---

blacklists/domains.json

xn--tbtc-upa94a.com
Hitbtc IDN homograph attack domain
https://urlscan.io/result/8ba318ad-2de0-4e94-b0e3-ccbca4148adf
xn--itbtc-9g1b.com
HitBtc IDN homograph attack domain
https://urlscan.io/result/b2a99dfa-8942-40e5-9dfe-8f5c4b22e10e
myetherwalleth.org
https://urlscan.io/result/dee9a62f-c4b7-43ea-8741-d312a604bbf2
brickblocks.io
Fake Brickblock crowdsale site
https://urlscan.io/result/62e91cae-f09a-4684-be41-40538dab9d01#summary
address:  0x2Dc5616EC2b9D24906F0e11dC8D8a736392dFeDD
zilliqanetwork.com
Fake Zilliqa airdrop phishing for private keys
https://urlscan.io/result/ab513a2f-d18e-4c45-8ba6-187c7ce18805
https://urlscan.io/result/906a4afa-2e05-476c-af80-5310b1a672f8
https://urlscan.io/result/33146cb3-2b61-41ba-bfd1-967b5478f0bc
brickblock.cc
Fake Brickblock …

xn--tbtc-upa94a.com + more

---

blacklists/domains.json

giveawayethereum.win
https://urlscan.io/result/8b714acc-b0c5-40b2-b610-9e629235243e
address: 0x8aF1380c436fC019b8055C61d09e3Ee5F182278C
myeterwallct-p.com
Suspect MyEtherWallet domain
https://urlscan.io/result/01b8f66b-75fe-47a7-8f17-e6f73aab0a93/
myethcrwallct-a.com
Suspect MyEtherWallet domain
https://urlscan.io/result/8d595bf4-53bd-457e-891d-649615f23194/
myethcrwallet-b.com
Suspect MyEtherWallet domain
https://urlscan.io/result/f0ce5269-8a2f-4492-a234-7c3fddec5fb3/
myethcrwallet-c.com
Suspect MyEtherWallet domain
https://urlscan.io/result/91f96f57-dc2d-4b81-aa04-1ae60746eb88/
myethcrwallet-d.com
Suspect MyEtherWallet domain
https://urlscan.io/result/438d36e6-12a5-472f-bda2-942a906f82ed/
myethervvallet.win
Suspect MyEtherWallet domain …

giveawayethereum.win + more

---

blacklists/domains.json

musk-party-gifts.updog.co
https://urlscan.io/result/910a27b7-0484-4608-8892-61ef3fac0b0d
address:  0x10c44aB858B90E09C725158906F71833fF417ACC
yobittrading.net
Fake Yobit phishing for logins
https://urlscan.io/result/3544d2aa-24ba-4ae9-869b-643b87e717bf/
yobit-trading.net
Fake Yobit phishing for logins
https://urlscan.io/result/666b538b-b924-43d6-8134-227374cfd777/

musk-party-gifts.updog.co + more

---

blacklists/domains.json

privcoin.io
Fake Ethereum mixer
https://urlscan.io/result/984000c1-2232-43b0-94ab-3f954960bf10/
suspected address:  0xa3e785ee490e1102fe32512973c96Dc7DC876348
free-eth.paperplane.io
https://urlscan.io/result/0d58983b-a077-40eb-bb0c-9955258ccc6a/
address:  0x92cd726CE03cEaa4bF7198ce9c52D05D63ceE575
ihcx.market
Fake Idex market
https://urlscan.io/result/3c3cec2a-4925-4a3f-b615-3210c37f7de9/
https://urlscan.io/result/b60ca10a-76fc-4a30-a930-e280e0b40c50/
helbizcoin.net
Fake airdrop phishing for private keys linking to a fake MyEtherWallet xn--myetherwallt-ovb.net
https://urlscan.io/result/f70319e5-9548-47f9-9c87-5b09bef7b218/
https://urlscan.io/result/f388ff99-cafd-4b53-94c3-f630f2342407/

privcoin.io + more

---

blacklists/domains.json

xn--polonix-17a.com
Possible Fake Poloniex - IDN homograph attack domain
https://urlscan.io/result/dd1c3447-e641-44ab-804c-fa2ba168011a/
xn--tro-k5y.com
Fake Tron site - IDN homograph attack domain - directs user to fake MEW xn--myethewalet-ms8erq.com
https://urlscan.io/result/697570b9-b0b3-4300-bfda-43ee4e9a86e6/

xn--polonix-17a.com + xn--tro-k5y.com

---

blacklists/domains.json

xn--bifinex-fb4c.com
Fake Bitfinex promoting a fake giveaway (trust-trading) - IDN homograph attack domain
https://urlscan.io/result/3e2af687-b705-4fb5-9e77-b8b55e073ae4/
https://urlscan.io/result/551eb57d-2c7c-4121-a9dc-ebdc789fe2df/
https://urlscan.io/result/e6e98a26-177a-4a17-8fbc-c7f1e7312c96/
address:  0x09430a9Fb46a1a3B83980768C4cEDF654d8eefa3
xn--blockcain-g95d.com
Fake blockchain domain - IDN homograph attack domain
https://urlscan.io/result/d6155859-055a-40be-991f-8ced9eb5cd01/
xn--coinbas-z8a.info
Fake coinbase domain - IDN homograph attack domain
https://urlscan.io/result/e203d686-3164-44e9-8056-30e652ef36d2/
xn--htbt-3oa0a.com
Fake Hitbtc domain - IDN homograph attack domain
https://urlscan.io/result/b48afb7a-3133-4761-9ec3-a7b62cd0848e/
xn--tbtc-upa94a.com
Fake Hitbtc domain …

xn--bifinex-fb4c.com + more

---

blacklists/domains.json

etherfree.tech
Trust-trading scam site, promoted by twitter userid: 330491787
https://urlscan.io/result/16734e7f-017f-454f-ad29-0a60191e75ee
address: 0x8C9D135aC2778e1A7d326932AaD302e7c22c94D7

etherfree.tech

---

blacklists/domains.json

etherums-givingaway.atspace.tv
Trust-trading scam site promoted by twitter userid 992068651569287170
https://urlscan.io/result/9015c65f-470c-4cbe-9c12-c74ea3970d7f/
addresss:  0x368bE389Ce940bf17C3296344086E368bc4C60f3

etherums-givingaway.atspace.tv

---

blacklists/domains.json

ethgiveavvay.site
https://urlscan.io/result/45b3534d-7722-4936-99b5-b4ff382a9d83
address:  0x0C4762Bc7B1Af1DC9448A827f53861c118B712dE

ethgiveavvay.site

---

blacklists/domains.json

See link, https://urlscan.io/result/f02dddfb-357f-4e0d-9234-e5a77f8da632.

Adding quarkchain-presale.io into blacklist

---

blacklists/domains.json

5000ethereum.online
https://urlscan.io/result/6d91fc66-0751-4b26-8a13-016ab6bee276/
address: 0xa5e83199a7ECB6669064d492F15ddC096b6cbAb8
hederahashgaph.com
Fake HederaHashGraph crowdsale site
https://urlscan.io/result/72f0e61c-b7ba-42af-895d-487a696e80e9/
https://urlscan.io/result/10818b4e-04d7-403b-b1bf-52957b2557da/
address: 0x873a35F651892AEe1D9360be80ae904f7D76068f
5000-eth.paperplane.io
https://urlscan.io/result/9cc72afa-df4c-49f9-a640-65bc2cb2e3f5/
address: 0x1691B2F9986598E12C57Aba5bE50ebd5346247E0
ethpromo.org
https://urlscan.io/result/e780ae7d-4702-49f5-874b-bc8802e2d843/
address: 0x52beED3924b0824411D03EA2fE51E429717dcF10
zilliqablockchain.org
Fake Zilliqa airdrop phishing for private keys …

5000ethereum.online + more

---

blacklists/domains.json

eth-giveaway.today
https://urlscan.io/result/cb202214-02a1-4a07-a112-f1db79932308/
address: 0x3F2cf669C657316985B01b1B797cb259c97d6551
etherget.online
https://urlscan.io/result/72e80e6c-515a-4e59-9042-5fc7754aeab3/
https://urlscan.io/result/7cda6081-4bba-47ab-85d6-053a6b45f078
address: 0xa8afa9a714e06b9eb1b500617494ac213f2d428a
ethplatform.org
https://urlscan.io/result/da8bf6a1-868a-4125-b26a-0f213d2d684e/
address: 0x54B623C82365ef20680B17301bD949BcD5599Eb9
mycrypton.net
https://urlscan.io/result/2aa06783-eb36-492a-a9c0-3a4a5a774450/
address: 0x7eD44f8b304cD71664Cbe8C94614660859Fca2c6
hydroplatform.org
Fake airdrop directing users to a fake MyEtherWallet …

eth-giveaway.today + more

---

blacklists/domains.json

quarkchains.io
Fake Quarkchains crowdsale site
https://urlscan.io/result/e912cd64-ee28-42ad-86d0-263903c8ee99/
address: 0xd7bb68B0cE5893983e5a2511b87E083609eB6fF9
ethcollection.paperplane.io
https://urlscan.io/result/7d4e356e-cc7a-4b55-b236-8447c54a2150/
address: 0xc8a7eFA8FF219CF002081c10c47F1D5F62b3FEe5
hydroggenplatform.com
Fake Hydro site linking to a fake MyEtherWallet - xn--myetherwalt-crb27c.com
https://urlscan.io/result/1a768393-0abc-4084-b38b-32ec22dd824c/
ldcx.market
Fake idex market phishing for private keys
https://urlscan.io/result/d592ac38-9d4a-4914-a25b-bad24a830aa3/
xn--mytherwallet-5vb.net
https://urlscan.io/result/3b1cb53b-5668-43e7-b25c-692f865f665e/
eth-airdrop.com …

quarkchains.io + more

---

blacklists/domains.json

pundix.tech
Fake airdrop site phishing for private keys
https://urlscan.io/result/e62e529f-c009-41a2-b831-0892a7e4bffa/
https://urlscan.io/result/798eef51-9a69-4d94-b82e-16059e740e57/
https://urlscan.io/result/3edf13ef-b0d4-4d06-bde3-ff46f23e3ef2/

pundix.tech

---

blacklists/domains.json

quarkchain.pl
https://urlscan.io/result/fa2fa7fb-a09c-4985-a85e-19bbdcb18671/
https://urlscan.io/result/f9631b40-6b5f-4ede-90a6-be1eb1ed04a3/
address: 0x7448dF6E1031d10e237b1481930a074B13FAAbD2
get-5001-ethereum.com
https://urlscan.io/result/c652c593-7a0f-41a2-85d4-007dc61558af/
address: 0x7D922A4f7F24fFcb130c4EEAF291A6475e3e4Dd2
get-5000-ethereum.com
https://urlscan.io/result/f2388aad-4a65-482e-ab39-c7a3d3f47c4a/
address: 0x1056d8d9EbB0E0d8710A0E2A1852d4A09d56464A
myetzerwallet.com
https://urlscan.io/result/22749122-afc6-459f-a507-5c419ed9b759/
promobtc.win
Trust-trading scam site (btc) - address: 14h4Zrd1xVg6Mj3JcYApoi2wY2UXue2ETb
https://urlscan.io/result/f065a6cb-24ee-449d-b846-41a1a4dc77f …

quarkchain.pl + more

---

blacklists/domains.json

xn--therdelta-uf7d.com
Fake EtherDelta - IDN homograph attack domain
https://urlscan.io/result/84a1f753-e1b0-46bf-ba12-40275fbbd15e/
xn--etherdela-ss6d.com
Fake EtherDelta - IDN homograph attack domain
https://urlscan.io/result/a89ad5a4-1086-4efe-b849-4771fb91c224/
xn--etherdelt-876d.com
Fake EtherDelta - IDN homograph attack domain
https://urlscan.io/result/7b37135f-d63c-4cfc-8e01-af1fb30ee878/
waves-ethereum-eth.org
https://urlscan.io/result/8476cf28-aadc-44b3-96fa-5feb8b762a62/
address: 0xfbb62df5cbc8d0bc4c2a0e5c53b8602d49471495

waves-ethereum-eth.org

---

blacklists/domains.json

See link, https://urlscan.io/result/0e615e1d-2b7e-44ee-8e59-ad1998d2eeb2 and https://twitter.com/BlqCheds/status/992402297442488320.

Adding icostarex.mipropia.com into blacklist

---

blacklists/domains.json

See link, https://urlscan.io/result/19210a3f-a33e-43fc-8900-da71aaee2c4b.

Adding giveaway-ether.com into blacklist

---

blacklists/domains.json

pay.ethconfirm.com
https://urlscan.io/result/98fd2339-f702-4ff2-a45e-5f1d3058d3cb/
address: 0x9BaaC782EA141718437a825704Fc61802993C03a
ethconfirm.com
https://urlscan.io/result/ac9d1c03-f780-41fb-811c-8b940b8f61da/
address: 0xb48c99C37b7cf4AC0A1c2dcA518782C1FEB4f066
eth-share.com
https://urlscan.io/result/52822950-ab88-40a1-abaf-74c09d24636c/
address: 0x024C344DA7208e60356378a252dAb771c34Be111
eth-gift.com.paperplane.io
https://urlscan.io/result/7badd11a-f68e-4146-82aa-0c82acf8a342/
address: 0x1CE4312fDd45c9184A5561314122B2244Bd862c9
iidexmarket.com
Fake Idex market stealing private keys
https://urlscan.io/result/3d468eca-a6d7-4c1b-85d3-0cf84dc05af0/

pay.ethconfirm.com + more

---

blacklists/domains.json

eth-promo.net
https://urlscan.io/result/a5537a9e-d1e7-4a88-bff2-415b9637f59c/
address:  0x18BfF0b35d63B6e19775d3FBbB5a9fa9D7288A74
tdex.market
Fake Idex market
https://urlscan.io/result/20e663f0-3c64-496f-b282-34446cd47854/
login-myetherwallets.com
https://urlscan.io/result/55bb9bf4-5fe9-41f8-9332-f9ab7938cd34/
ethgive.online
https://urlscan.io/result/5b7cc296-e4fd-4a3c-b6bc-46254be94964/
address:  0xE03C6FDD69e268A00cC93Fa282Fb3ce82afC8B12

eth-promo.net + more

---

blacklists/domains.json

etherdelta.githiub.io
Fake EtherDelta phishing for keys
https://urlscan.io/result/41a55787-4d42-4589-b1c8-b65286b6bb65/
https://urlscan.io/result/c55ea5c2-cb63-4066-88f2-a210259165f2/
ether-promo.org
https://urlscan.io/result/9dac2ed5-2a85-4036-9e2d-aa0b0fdb1f10/
address: 0xf6eb7d25dfb8cd1d8fcb8d1cccab9f6f3e594ea8
ico-telegram.org
https://urlscan.io/result/ee0ea79c-cf88-41a9-b644-5c8bbf6fb275/
address: 0x5a3dEe76449fE47158Bf6b3B68c629c4ecD2554f
atn437.ethgiveeth.com
https://urlscan.io/result/c1e509a1-7d54-42c4-bd50-86e64b12a5c9/
address: 0xa47879FC57ECD8b52bfe7cF61B9bb41B7ef84eFC
ethgiveeth.com
Hosting trust-trading scam sites
https://urlscan.io/result/39eded42-b52b-45bd-b6b8-fbd93dee2c1c/
address: …

etherdelta.githiub.io + more

---

blacklists/domains.json

ethgift.org
https://urlscan.io/result/d358cad2-c827-4fce-bcc9-86a4736b4a9a
address:  0xbCA804D30E8602F3ca47F8C8b3A44f8e03fe1594
hydroraindrop.typeform.com
https://urlscan.io/result/d8c4a13b-c6f4-45bb-90cf-5dabfa918fb9

ethgift.org + hydroraindrop.typeform.com

---

blacklists/domains.json

klareol5.ru
https://urlscan.io/result/b78f0e98-7b67-41da-805b-f50e8a306a2e/
address: 0x3d9D797B15Dfe68d5010fE9C9e8a1AAb1F040932
20000.paperplane.io
https://urlscan.io/result/b326c49a-5f55-4a16-bb99-8236d5de9d5c/
address: 0x58DCE1959623E1210FE465ca3AFa3a05590cC4E7
secure093555613.safethpay.com
https://urlscan.io/result/03cec5c5-3796-464d-81f6-3e262ca8f188/
address: 0xe2972F7b92E32162E8dD4c30B0516bAa2A24C3c9

klareol5.ru + more

---

blacklists/domains.json

tron-block.com
Fake TRON web wallet (cannot withdraw)
https://urlscan.io/result/14a0686a-1c27-44ab-ba4c-a6ea20b8d89f/
address: 0xdd1db171b110fb857311fde3236217894e7e9ab8
idex-market.site
Suspicious domain for idex.market
https://urlscan.io/result/d9ecc3e8-8795-4238-924f-5ec4504fd62a/
ethgive.net
https://urlscan.io/result/505224db-3818-4fe6-a8b9-532dc6dd160a/
address: 0x9fe0627303fe40f1631231B4DD016d30c13EafC7

tron-block.com + more

---

blacklists/domains.json

givefree-eth.com
https://urlscan.io/result/bad66464-c8d9-4b3b-ab76-e5c289c3388a/
address:  0x8c34460976e89EDdE3e2898DC7F23b597d295103
now-5000ether.paperplane.io
https://urlscan.io/result/c93cc8b5-3b23-4410-88f0-13279f277fa0/
address:  0xDC3896Be3EB4bB3B3eb2f936348E942796078920
eth-give.info
https://urlscan.io/result/51efc557-f9d8-4af2-b8b6-5943f6b4a1bd/
address:  0x7eA4270D456BC7B3E1C72f8a21a88a90C3D60147

givefree-eth.com + more

---

blacklists/domains.json

ethpromo.org
https://urlscan.io/result/fa9a4c31-a050-4171-8dd7-fff5e68002fe/
address: 0x07cfB04588154b06E3958b5d70408244102014D5
eth-request.org
https://urlscan.io/result/2fc3c732-b7fa-40c8-89c0-ef98ebfde3ac/
address: 0x718eE443Ffdf50b30a5e8226d4Ff71E605C5cA7C
eths.space
https://urlscan.io/result/2af94512-8176-46bf-9d6e-16cae27a8ed0/
address: 0x096C39aB4fa36cA74A36FE1F4767FF487762f0Aa
btc-gift.org
https://urlscan.io/result/f68afd05-e7a0-4374-a297-61125f285ef3/
myethcrwallet-d.com
Fake MyEtherWallet - iframing 94.100.18.96/my2/ - suspected address: 0x59032DAB819f2457bf01E52D02dd42073D2E7D13
https://urlscan.io/result/f688d3d5-f011-4ed8-839a-86ce1666700f/ …

ethpromo.org + more

---

blacklists/domains.json

tomochain.tech
Fake Tomochain airdrop phishing for private keys
https://urlscan.io/result/e5fee213-90cc-4bd2-9a07-235c3e5e77ad/
https://urlscan.io/result/4e70356c-a0bd-46fb-8697-989bad358ed4/
https://urlscan.io/result/bd186b12-9184-4be9-bf58-349375ec2dce/
geteth.online
https://urlscan.io/result/6a04769a-9384-402b-a104-da9f5f3d3588/
address: geteth.online 
xn--myethrwalet-vrb05c.com/signmsg.html
https://urlscan.io/result/c6b29af2-8d46-4ac6-847b-da28df527b00/
https://urlscan.io/result/195435ed-8d32-4bb3-8987-15503793469b/
ethclaimer.byethost32.com/claim.php
https://urlscan.io/result/703a4532-5e24-43cd-94b3-7b5c06927ced/
eth-give.info …

tomochain.tech + more

---

blacklists/domains.json

got-eth.com
https://urlscan.io/result/2fbd7dd3-efbf-42eb-9aae-074f09567895/
address: 0xb0D2d2791657ce6CdF48b77A1E10F62E9b4Ee74B
eth-share.com
https://urlscan.io/result/e4278155-8b0d-4c7e-b198-88cb6d9e0c5c
address: 0xb0D2d2791657ce6CdF48b77A1E10F62E9b4Ee74B

got-eth.com + eth-share.com

---

blacklists/domains.json

air-eos.com
Fake EOS airdrop phishing for private keys
https://urlscan.io/result/68f65da4-0da8-400e-8d8b-f90becb972f2/
https://urlscan.io/result/4baebde4-1821-47f9-abf3-206c2e95fd00

air-eos.com

---

blacklists/domains.json

ethgiveaway.zkr.kr
https://urlscan.io/result/6a755409-20bc-48b9-8af2-b21b10b2dfb5/
address: 0x9852286460022e5151381361bA4271c7272cF966
eth-promo.wixsite.com
https://urlscan.io/result/9a662a44-7d02-459f-86b6-76a81e2cc6da/
address: 0x9852286460022e5151381361bA4271c7272cF966
calchain.io
Fake airdrop emailing users to go to signupform1.typeform.com via email, which then directs them to xn--myetherwalt-kbb96i.com
https://urlscan.io/result/4192662f-9496-4572-a45c-b24143ff721b/
https://urlscan.io/result/2ca50f69-3fd0-4e91-8cc2-4502977e7e2b/

ethgiveaway.zkr.kr + more

---

blacklists/domains.json

eoslaunch.io
Fake EOS site phishing for private keys
https://urlscan.io/result/9a270b7a-d578-4651-a54f-010dc9046951
https://urlscan.io/result/9a270b7a-d578-4651-a54f-010dc9046951

eoslaunch.io

---

blacklists/domains.json

ethg.me
https://urlscan.io/result/f56b696b-cf85-41e7-858a-e4dff63cc5d8/
address: 0xB9CEe6fa32eb4d0c8F30E3cd335b72461bD9126e
jdex.market
Fake Idex market site stealing private keys
https://urlscan.io/result/d348adc2-a97d-42a9-951c-9b0e777140ce/
idex-myaccount.com
Fake Idex market site stealing private keys
https://urlscan.io/result/ad09dab8-a77a-4567-9109-0853b30edaac/
index-markct.com
Fake Idex market site stealing private keys
https://urlscan.io/result/bb0f9101-30b3-4083-aeb9-a58831886cb5/
ldox.market
Fake Idex market site stealing private keys
https://urlscan.io/result/b8f029df-111f-40c4-b672-53a90748a4c8/

ethg.me + more

---

blacklists/domains.json

xn--mytherwalt-smbh17c.com
https://urlscan.io/result/bdedc869-8da9-4da7-b129-11415daabc50
https://urlscan.io/result/d125ab9a-503c-4cfa-b966-b7c685ca2eea
Fixes https://github.com/409H/EtherAddressLookup/issues/623

xn--mytherwalt-smbh17c.com

---

blacklists/domains.json

calchain.net
Fake airdrop directing users to a fake MyEtherWallet (xn--myetherwlet-37a36j[dot]com & xn--myetherwllt-37a50e[dot]com). Suspected address:  0x4121cc82607ebab3f334e067f37fe2709c403bf6
https://urlscan.io/result/bd447370-4992-4d03-b41e-ab4afd24103c/
https://urlscan.io/result/892e43a7-10e2-4b57-9a27-996d967f96f5/
ethpays.me
https://etherscan.io/address/0x297A88c749273F2DE6a378A6015Dd624D993C671
address:  0x297A88c749273F2DE6a378A6015Dd624D993C671

calchain.net + ethpays.me

---

blacklists/domains.json

ethpromo.io
https://urlscan.io/result/802c5bce-c40e-42d7-8f6a-cc65d6c5a5bf
address: 0x4Dad23689bEf624aF5d1757A56135901c915FCFD
myetherwallet.com.signinverication.verifcaon.site
Fake MyEtherWallet. Suspected address: 0xCDb26199dB086d54F7b11e50cA4374b4Dd9CE13f
https://urlscan.io/result/66e84dbd-bf6b-4b96-8d16-98dce1025c6f/
https://urlscan.io/result/47be8e46-ddc4-4a93-b776-6847138cc918/
verifywallet.typeform.com
Fake airdrop directing users to a fake MyEtherWallet xn--myethewallet-4nf.net
https://urlscan.io/result/ecf4888e-2f9c-4bea-8f01-40ad98e80dc3/
xn--myethewallet-4nf.net
Fake MyEtherWallet - IDN homograph attack domain. Suspected address: 0x1ee6b25a0e3f855a10916766df3a056e924e5dce
https://urlscan.io/result/073f84b4-ef76-4bfc-8d81-544b26e92afd/ …

ethpromo.io + more

---

blacklists/domains.json

saferpayether.com
https://urlscan.io/result/009e33e8-7787-4f64-be5f-731284318afa/
address: 0x4Dad23689bEf624aF5d1757A56135901c915FCFD
ethgive.global
https://urlscan.io/result/46792cd3-e970-48f3-8f9b-62b25e39e02a/
address: 0x9849424a2f3516B70b56D70330c45c25DcCb2C02
ethpromo.info
https://urlscan.io/result/92f5e9e6-1175-417b-86c8-a7ef0f374f6a/
address: 0x88620C720523c822adCdc1d5484915fcD85BAf73
ethereum-promo.org
https://urlscan.io/result/69373894-565e-4aab-8b8e-d5e6c0676ab0/
address: 0x48dcc01a31E38e14F6a63846E371C6e9Cb0C3f3a
crypto-claims.org
https://urlscan.io/result/83bc8915-e840-49e0-9167-e174c72d28dd/
address: 0x839DB3994bef8842C0809AB84996bA839fCac11e
getethnow.com …

saferpayether.com + more

---

blacklists/domains.json

kinetictokenform.typeform.com
Fake airdrop redirecting users to xn--myetherwllt-r7a44e.com
https://urlscan.io/result/ec31a417-ac95-41c6-ab66-b4cbfbf63c07
xn--myetherwllt-r7a44e.com
https://urlscan.io/result/29ae1633-1da5-4c23-bad0-bd7d1ef762ac

kinetictokenform.typeform.com + xn--myetherwllt-r7a44e.com

---

blacklists/domains.json

myetehrewallet.com
https://urlscan.io/result/8e75a814-3f7b-4de0-ac08-2ca577017731/
lbex.market
https://urlscan.io/result/8e75a814-3f7b-4de0-ac08-2ca577017731/
idex-info.net
https://urlscan.io/result/85332caf-df30-4aaa-8fca-16c9970daa4b/
get-eth.win
https://urlscan.io/result/b64e468a-e397-4801-903e-d30c0d216ac2/
address: 0x3BD49b98ffcC5f717eED0c9e78a276Ae979de6e4
eth-claim.org
https://urlscan.io/result/a587f026-fc54-42b2-96db-f4dafe60f183/
address: 0x34d202c37f9609A3d0d44db259ff51Bae8ea2D0f
eth-givebacknow.tumblr.com
https://urlscan.io/result/52ca3146-aafc-4b1e-8371-7e85a97160d0/
address: 0x6CFDdE4E08c9e2CF1b9A32d2C31203966B17f816 …

myetehrewallet.com + more

---

blacklists/domains.json

idexmarket.io
Fake Idex market phishing keys with GET store.php?mapza=&action1=1
https://urlscan.io/result/151f9aff-a89c-4866-bab8-afb3356f4f1a
https://urlscan.io/result/b47a139d-b4a2-4b9c-88db-46ae619274a0

idexmarket.io

---

blacklists/domains.json

ethofficial.info
https://urlscan.io/result/2528f876-0fd3-4e8a-b7ea-28ba969544c0/
address: 0xfB03e59c83b984DA0f6a5575B955541af28cCC65
getsomeeth.com
https://urlscan.io/result/27470387-5834-4428-8ae0-7b5feadea1fb/
address: 0xdb850d7dC1aDe8eC00CE4269e732d3Aa44286f73
giveawaycrypto.org
https://urlscan.io/result/ff03cb73-050c-4b93-81f6-6b03d49b80c8/
address: 0xeaA4b711e7C025899460b429BeF1ff8155ba4C66

ethofficial.info + more

---

blacklists/domains.json

keyfund.io
Fake airdrop directing users to a fake MyEtherWallet xn--myethrwalt-vmbe17c.com
https://urlscan.io/result/164ac14a-06a9-4119-9a9b-f22a0fe126db/
https://urlscan.io/result/d8327bb3-ff86-4620-9f6c-716bb93aeca0/
ethereum-promo.xf.cz
https://urlscan.io/result/b68e6017-64fc-40b6-9d6f-8940f0341343/
address: 0x997ad34840281d459251abdf9c90d9a8c6a6e01a
myetherwallet.comsigninverication.signmessage.crocweb.online
Fake MyEtherWallet. Suspected address: 0x6ab2a9088916bf97c248888009b669aa37bab681 0xcdb26199db086d54f7b11e50ca4374b4dd9ce13f 0x5127E8d79160f4cD177F5aC5A1e860acAa59a34B
https://urlscan.io/result/46be63c2-3bf1-470f-88df-edc88c95284d/
https://urlscan.io/result/9d5b4442-7b25-49ab-90f1-715b045ebfd1/
myeosdac.top
Fake EOS airdrop asking for address validation on …

keyfund.io + more

---

blacklists/domains.json

eos-swap.com
Fake EOS countdown, phishing for private keys with POST /VerifyToken.php
https://urlscan.io/result/0a39213a-6447-4660-b663-09fd8fdb8d0c/

eos-swap.com

---

blacklists/domains.json

ethpromo.cc
https://urlscan.io/result/77f317d7-44a8-4774-affc-f1303fc1a409/
address:  0x05e85D73Eaf6fEF228294fdF867aBBa98552A99F
idex-market.eu
Fake idex phishing for keys
https://urlscan.io/result/4fbd0c72-4bca-47eb-890a-8197a14a1a42/
idex-login.net
Fake idex phishing for keys
https://urlscan.io/result/7b3fe2c9-cefe-4463-886c-d4dd3cdd0623/

ethpromo.cc + more

---

blacklists/domains.json

promotoeth.org
https://urlscan.io/result/b59fd627-9211-4725-a6b4-1b9cabd617d9
address:  0xb733A811edF703701d2403d8196df87306BED6D6

promotoeth.org

---

blacklists/domains.json

electrocoin.typeform.com
Fake airdrop directing users to a fake MyEtherWallet - myetherwalllet.trade
https://urlscan.io/result/7a5852b5-b5a2-4938-b027-4488e56b8a78/
myetherwalllet.trade
https://urlscan.io/result/46901a9f-7bb0-4774-bee5-9c43080363aa/

electrocoin.typeform.com + myetherwalllet.trade

---

blacklists/domains.json

telegram.vu
https://urlscan.io/result/dfa596be-555c-4e49-a260-3546d732a1ba
address: 0xbf863b57322A1E634388946F942306393A5D4c69
mydeliverycv.com
https://urlscan.io/result/5bf2032c-b012-4b72-a329-bcc17f8c74bb/
ethereumbonus.org
https://urlscan.io/result/5d323899-056d-4d2d-a73f-3568c870a7d1/
address: 0x2271A88623266069352196363c1E54f61C5141E1
ether-giveaway.online
https://urlscan.io/result/16977475-37b5-4290-add5-88fbe718171d/
address: 0x483ec0E946d1d61696Bc8F69ef10365bD80862dc

telegram.vu + more

---

blacklists/domains.json

get.ethpublic.com
https://urlscan.io/result/5e9a29e9-648b-43db-b2f6-510ef6a1f0d7
address: 0xe4fc4C3889B5442391acAD627673F4Ef7Efe7B97
ethpublic.com
https://urlscan.io/result/4177f5a4-4828-442b-9462-2e5c773cb873
address: 0xe349B26753ECa84A2858901d414c612c8c8e20f9
ethereum-get.org
https://urlscan.io/result/2dae7ce1-aa28-432e-b625-6e5253d3ac3e/
address: 0xaBbD5F7D4DE3c91706c73FD7d09b9ec3Ed9cA697

get.ethpublic.com + more

---

blacklists/domains.json

myethrwatt.com
https://urlscan.io/result/1f77aa01-14ee-4317-be8f-1d2030cb553c/
ether-share.com
https://urlscan.io/result/33a218d0-7e94-4d4e-8090-13f65ab41907/
address: 0xEd51c3c2fb6E6965aEd7beeC167B0596dc36116D
btcs-share.com
Trust trading scam site. Bitcoin address: 1N2GSugUiQ9bgG94YFhexLqdEXrLZ9CQXa
https://urlscan.io/result/a7fbb413-e0df-4622-ae19-95196c3b1dc0/

myethrwatt.com + more

---

blacklists/domains.json

xn--myetherwalett-4hc.net
https://urlscan.io/result/09f14bd0-e3a7-4856-935d-f2b8099055b0/
https://urlscan.io/result/ddcc788a-777c-447e-9b59-0eef6164f559/
ethereumgiveaway.typeform.com
Fake giveaway collecting data on users and directing them to a fake MyEtherWallet xn--myetherwalett-4hc.net
https://urlscan.io/result/e40eb8c4-86a3-4551-a108-c481ab40afed/

xn--myetherwalett-4hc.net + ethereumgiveaway.typeform.com

---

blacklists/domains.json

cryptoaway.org
https://urlscan.io/result/c587e886-8192-41f2-b632-cb5cb2254ce0/
address: 0xbEC9410b01671bB6521996B141BB95Ebff87Cb31
ethdeals.org
https://urlscan.io/result/e5e8f7b5-1aff-4228-8e31-4aa9205b7bee/
address: 0x0E42f55Da7ADe5673130e23232CEC6094d34087c
ethgiveaway.io
https://urlscan.io/result/75d1d363-0132-4618-8a75-14b29b6dae6a/
address: 0x06091b32533835265Bfa6EF8B32B04747Ba77bB2
claimeth.me
https://urlscan.io/result/d4823a7c-6932-4417-873b-0df5657611f7/
address: 0xf2Db2f7AEC4E32Fe10A8352e1E02D099a194f7A7

cryptoaway.org + more

---

blacklists/domains.json

safe.ethxchanges.com
https://urlscan.io/result/7ddef598-9bc6-40a9-ab1d-4fa28f283da5/
address: 0x27F897EBeeD82240734489D52AA7e39a8cA257E9
ethxchanges.com
https://urlscan.io/result/37c9b0b7-8441-4630-9d89-20136c74e21c/
address: 0x27F897EBeeD82240734489D52AA7e39a8cA257E9
xn--mythrwalet-c7ac47i.com
https://urlscan.io/result/56dda366-2eda-4066-8009-c24029bcce3f
xn--mythrwallt-c7a86c5a.com
https://urlscan.io/result/958680db-9cf0-44ea-9ea1-dc552963bc59

safe.ethxchanges.com + more

---

blacklists/domains.json

xn--myethrwalett-8vb19c.net
https://urlscan.io/result/870b6b80-baa5-4d0c-b9c1-44bc75d38f2d/
https://urlscan.io/result/134f33a4-1fb7-4e02-9468-73e380d97588/
Fixes https://github.com/409H/EtherAddressLookup/issues/667

xn--myethrwalett-8vb19c.net

---

blacklists/domains.json

myetherethwallet.com
https://urlscan.io/result/45442ba7-f836-4319-80c3-c37d0eade14a/
myethervualet.gq
Fake MyEtherWallet (suspicious domain, kit not deployed yet)
https://urlscan.io/result/2a6c7b21-b9c8-40f6-8f07-453a482fe0c7/
myetherwallea.org
Fake MyEtherWallet (suspicious domain)
https://urlscan.io/result/e2f0f962-2731-4eb7-9a35-fec6088714c4/
myetherwallee.org
Fake MyEtherWallet (suspicious domain)
https://urlscan.io/result/a51c49fd-461a-493f-8662-1eca27590b9c/
myetherwalletl.org
https://urlscan.io/result/697dbf58-7ca0-427f-a8f4-edffa45cd07f/
myetherwalleu.org
https://urlscan.io/result/ab97594c-1888-4db8-b2fc-dc0d9374296c/

A bunch of fake MyEtherWallets

---

blacklists/domains.json

ether-give.club
https://urlscan.io/result/cd5adf1f-97b0-4371-9399-58a202875ebd
address: 0x50a9a8c8ce2bb0ea10f4d4a586ac2d77257b8247
myethertrust.com
https://urlscan.io/result/7a407d1b-72b4-41f3-8a77-9931faced750/
https://urlscan.io/result/95cff247-e7a5-4257-be42-31cefbf91906/

myethertrust.com

---

blacklists/domains.json

xn--myetherrwalet-5hc.net
Fake MyEtherWallet - IDN homograph attack domain. Suspected address: 0x7e25f33c1e3402f2197dab251ce2d73cdbcb77a3
https://urlscan.io/result/451f46eb-10d1-4f73-a3db-accbd07bd231/
https://urlscan.io/result/1a5b2a0e-bc4c-494e-8d9b-a0c70660e94f/
idice.epizy.com
Fake idice GUI
https://urlscan.io/result/afb9685c-b12e-428b-a7c3-fc6c9a32405b
address: 0x9b2D66562bea3EefEc436dF0Fee88Dd89CbE547b
gene.network
Fake crowdsale site directing users to a fake MyEtherWallet http://bahs.edu.tt/https_myetherwallet.com:gese_token_redeem/
https://urlscan.io/result/400cf5f4-43bb-4671-bdba-5508c4113596
bahs.edu.tt
Hosting a fake MyEtherWallet
https://urlscan.io/result/02b1388f-408b-4f7a-811f-dbf5f9f797fa/
https://urlscan.io/result/dc97ff76-e8b7-47db-89bc-91d5335cccc2/

xn--myetherrwalet-5hc.net + more

---

blacklists/domains.json

xn--myetherwalle-mm5f.com
Fake MyEtherWallet - IDN homograph attack domain - not deployed yet
https://urlscan.io/result/b01afd50-265c-40f2-a47b-61d12b458fa4/
xn--myeherwallet-4j5f.net
Fake MyEtherWallet - IDN homograph attack domain - not deployed yet
https://urlscan.io/result/82292a41-b776-4772-bf81-ef99df50fdca/
xn--myethrwllet-q7a5h.com
https://urlscan.io/result/6da58982-b108-46da-8ee9-2c73eb13b48b/
xn--dexmarket-98d.com
Fake Idex - IDN homograph attack domain
https://urlscan.io/result/d5e9d423-b402-4360-b8a9-fcdd1751e609/

xn--myetherwalle-mm5f.com + more

---

blacklists/domains.json

kentra.tech
Fake airdrop directing users to a fake MyEtherWallet - xn--myethrwalt-inbe64c.com
https://urlscan.io/result/5a6ac1e3-1447-4ef8-a0e8-d3f9aaf00f46/
https://urlscan.io/result/a15f09f4-5548-45e5-addc-edc3acf01648/
xn--myethrwalt-inbe64c.com
https://urlscan.io/result/03af7e40-ebcf-4056-ad3f-57f0402d9597/
https://urlscan.io/result/0bcb0635-0977-4d72-a673-618195cbf5d1/
address:  0x0A796062214Cf4FC232Dd8538a19035Ac79a595c

kentra.tech + xn--myethrwalt-inbe64c.com

---

blacklists/domains.json

ethpubs.com
https://urlscan.io/result/0312e541-0319-4733-b6c1-26c51a3f5904/
address: 0x52Bdb97E587a35d5e54b01344168D41783120310
binancegiveaway.org
https://urlscan.io/result/7dc36378-3e1e-449e-9434-96e82306014a
address: 0x1aBC65765FD0DF7D997635EBE3027384BCF7923E
ethgws.org
https://urlscan.io/result/c99c3418-d284-4a8c-80ca-a16ddca723dc/
address: 0x28A6D6E41fcCA5b003f22ceBa48Aa689325Dd62B
ethereumreturns.com
https://urlscan.io/result/8067b857-b169-4ca4-adc9-ff3c3c529a40/
address: 0x2E6Ace64e85572eeDAaD739c3172EcE853153C73
takeeth.org
https://urlscan.io/result/1b84c11d-656f-44cf-bde1-9934b4b081a0/
address: 0x28A6D6E41fcCA5b003f22ceBa48Aa689325Dd62B

ethpubs.com + more

---

blacklists/domains.json

creteprint-driveways.co.uk
https://urlscan.io/result/fc1a6bf3-235d-458e-a55f-85c1a8d6a88f
address: 0x607c78AeAaBADb84AdC3298fb3077fc75429e8bD
ethype.org
https://urlscan.io/result/6f03f717-aa58-4b9f-a92c-0b88c0e78d1b/
address: 0xB9b848702a47AE78A70D18c45e552aB1637B5908
etherpromotion.org
https://urlscan.io/result/f67991dc-a3e4-4221-b9bf-ef59c39850f7/
address: 0x32Ea6b24675349EDb6dF2896457819289Aad180E

creteprint-driveways.co.uk + more

---

blacklists/domains.json

eth.blogmedium.top
https://urlscan.io/result/13555aff-7e59-432c-8033-553d6ea0fd82/
address: 0x9aC33De53E16b21250Ba2418150fe07Ce8C7e5e7
eosregistry.site
Stealing seed phrases. Fake EOS register
https://urlscan.io/result/70b178e4-ee6b-411a-a354-e9d9fd92c757/
https://urlscan.io/result/de0c8bc2-b643-446e-9f16-e3a949deb3e8/
xn--coindes-jhb.com
Fake Coindesk promoting a fake EOS article. Suspected address: 0xF9390CdA498171e748cD0B43FF65f747867E3eD3
https://urlscan.io/result/c35aca1b-ef3c-4c1d-ac61-0c79b5254582/
https://urlscan.io/result/5d9b3969-ebda-4160-8277-cdc1ad7e8b92/

eth.blogmedium.top + more

---

blacklists/domains.json

ethpromoaction.com
https://urlscan.io/result/e3492e92-5d7a-42e8-ad25-5c9252f03281/
address: 0xBee06db915F38C62D61aBa80932369007bEAe9d8
ethinfo.org
https://urlscan.io/result/c447f9e1-028c-4ade-a59e-400ac2dbb767/
address: 0x34b6341655061f4B5830CD1a7B20A3516043AF57
airgws.org
https://urlscan.io/result/01d49f90-753a-4483-a517-d35b894e5ff7/
address: 0xc364451d6316Be34CB1b8f8B0922fE59d5CF2Ca9

ethpromoaction.com + more

---

blacklists/domains.json

ethergive.net
https://urlscan.io/result/066db09b-331c-4d23-935e-1e2189ef30c3
address: 0x2E3Fd2B400a269f7a0B1AaF448EF02679cd557e9

ethergive.net

---

blacklists/domains.json

airtake.info
https://urlscan.io/result/2c0e8447-0ac3-41aa-8638-4736cc48244f
address: 0xB9556A1cb3150148443e9e9E9C29491FF48640Ee

airtake.info

---

blacklists/domains.json

getbigdeals.org
https://urlscan.io/result/862b618b-36fa-4597-9d51-e51ce2a95065
address: 0x1d138d1f0e8E5F67540b6054De7dB08A610F85B4
ethpromotions.org
https://urlscan.io/result/b3160585-929f-4ecd-9155-b2d331e6293d/
address: 0x016c0261C48D089Ac26d0a48f840c9A9d5e203dd
wincheck.org
https://urlscan.io/result/26a16ed0-f949-4835-ba56-640551ddd00b/
address: 0xF1a4b668D15F0E66543e9F1F795cC2B0f97E3ef2
ethfor.info
https://urlscan.io/result/e97b3b14-c8bf-4811-ac6e-4815b6596ebc/
address: 0x2299c90980777Bb9ebf2D8D58a92Cb3AB7F7fAA0

getbigdeals.org + more

---

blacklists/domains.json

giveawaypromo.byethost14.com
https://urlscan.io/result/b4b99bc5-c986-4e82-8819-fc5a6e04115e/
address: 0x6a9C2EC4f4888D7338fC1b28584AaAfEb01e6Db3
xn--myethrwllt-y4a7gf.com
https://urlscan.io/result/514607ea-ab4b-450f-8f31-b921cc5889d7

giveawaypromo.byethost14.com + xn--myethrwllt-y4a7gf.com

---

blacklists/domains.json

index-markels.com
Fake Idex Market phishing for keys
https://urlscan.io/result/a295c4d3-1313-4169-b1f9-be9e6f3e3204

index-markels.com

---

blacklists/domains.json

eth-claim.org
https://urlscan.io/result/b9e0175d-1627-42f7-8e07-1b1e5b314d18/
address: 0x87F655E887827eD11Eb3fBC74767B18E142cCced
ethpays.org
https://urlscan.io/result/f0f39673-df5d-422b-b4e6-9b582d4bea77/
address: 0x56ccaA034A0bDb7D3A9515CB580FB5448EfB584C
verify.officialeth.com
https://urlscan.io/result/5c496a5a-cb55-44e6-b355-7b0f58f013e4/
address: 0x6eC56FB2436BA6706CeCD42403B6a1b69fF0817F
safe.ethpaynow.com
https://urlscan.io/result/06ec366f-5e8c-4817-9e80-cbc1ba90027a/
address: 0xa23203C466A57649b83687A3D9129D3EC427C50a
elon-gives.com
https://urlscan.io/result/619af9c7-8cac-4989-a64c-5ddb62ca7997/
address: 0xeb6a066D30c55609fB9f3f6446C6Ef8f27033D2A

eth-claim.org + more

---

js/options.js
manifest.json

* If the user doesn't open the extension, the list is never refetched causing everyone to be catgeory neutral - this fixes that

Fixes issue with Twitter list not fetching

---

blacklists/domains.json

today-ethereum.com
https://urlscan.io/result/0deae08e-688c-414a-97e6-e3fe675b5344
address: 0x4dD0eF53784030fA675e2677F9CdC2a3e32E956B
ethnow.org
https://urlscan.io/result/045a6b1d-6808-4347-8227-99ce3686cdbd
address: 0x3963C374e0E71018dBA76814c13fdd5458d55898

today-ethereum.com + more

---

blacklists/domains.json

ethereumgw.org
https://urlscan.io/result/606005ea-97da-44a0-8b90-00c568b4543b/
address: 0xA6f2814C0020c38882e82D9bFde7B485a7297a1D
epromo.cc
https://urlscan.io/result/c1788f18-d7e8-4f3c-9b09-8907e1ff2ba6/
address: 0xc9194a772c23A595dFAB28E30376f2e16eC39E01

ethereumgw.org + epromo.cc

---

blacklists/domains.json

giveawaypromo.byethost14.com
https://urlscan.io/result/0937b2ec-aa70-4a5d-8ce1-bf8f608c3a5d
https://urlscan.io/result/33778c52-874b-4fd4-8278-456674e4f415
address: 0x8D3CFe26a635A322F814512d3e09dF75F7CbfBd3
myetherwalllet.online
https://urlscan.io/result/d283b3cf-8d78-4cfb-a652-6d6f7003bc33/
odyssey.plus
Fake Airdrop phishing for private keys
https://urlscan.io/result/81c5f681-3e76-48fe-86ac-e6dd27be6d48/
https://urlscan.io/result/905d3f38-c720-4755-9ed5-0cfee96c8ac7/
https://urlscan.io/result/c8fd8cd5-2e13-4840-aa92-acaa9f8404dd/
address: 0xaf8185ffff6a3508fc5498a5165bf64de0b0a1e5

giveawaypromo.byethost14.com + more

---

blacklists/domains.json

iddexmarket.com
Fake Idex Market phishing for keys
https://urlscan.io/result/32dc9167-d27c-463b-8f22-f7d4b194b22c/
index-marker.com
Suspicious Idex Market domain
https://urlscan.io/result/2756c997-1ea4-4544-897f-ae2dd4f061bd/
index-markels.com
Suspicious Idex market domain
https://urlscan.io/result/fb0c0817-ec17-4342-a014-113125a86db8/
iddexmark.et.com
Suspicious Idex Market Domain
https://urlscan.io/result/a788e178-df3d-43fd-9f07-d588384d7793/
iddexma.rket.com
Suspicious Idex Market Domain
https://urlscan.io/result/9a4fbb8e-90de-41e0-bd63-2c7b49c1f687/
ideexmarket.com
Suspicious Idex Market Domain
https://urlscan.io/result/650e4fb7-6321-4166-9f57-f83e0dde8a28/
idexmarket.com
Suspicious Idex Market Domain
https://urlscan.io/result/40e4d5e3-4054-4ced-b6b6-643d2c565764/

iddexmarket.com + more

---

blacklists/domains.json

indexmarkett-corp.com
Suspicious Idex market site
https://urlscan.io/result/aec5f487-a91d-4dc7-b57a-3c4aeb7f4655/
giveth.ws
https://urlscan.io/result/92d763ea-49f0-4b03-9f03-208cea4cdfd1/
address: 0x89271335DB9d0024F725Ab23415678CdEA3EB368
giveeth.org
https://urlscan.io/result/eb736756-e0d7-494a-b30f-9f07703069a6/
address: 0xA6f2814C0020c38882e82D9bFde7B485a7297a1D
ethereum.org.give-eth.today
https://urlscan.io/result/103b8e43-cfec-467f-bdd6-c5f9ae974743/
address: 0xA213344262535D3EA5EFeAA7f7Cf74e792dA6258
give-eth.today
https://urlscan.io/result/f28cbe7d-fb2e-4162-961c-e04aa7f8a1cf/
address: 0xA213344262535D3EA5EFeAA7f7Cf74e792dA6258
collect-ethaway.com …

indexmarkett-corp.com + more

---

blacklists/domains.json

ethereum-prize.com
https://urlscan.io/result/5c6c1e2e-ea9c-46e0-8255-071b2605b300/
address: 0xc46E1430B1D4B7066B9B6655293492256BA216B9
sharekit.io
https://urlscan.io/result/b81e805c-bcf2-4d16-8b22-c8cdaf8a09a6/
address: 0x89271335DB9d0024F725Ab23415678CdEA3EB368
etherbonus.live
https://urlscan.io/result/eb174f8c-46c4-4184-bfb2-18a2410ca29d
address: 0x5188d13bdd9D7Ac30324a569E2cE42488374738e
fantom-foundation.tech
Fake Fantom crowdsale site
https://urlscan.io/result/21e94e99-d334-4e41-aea6-2dacd8deab4f
address: 0x567211d48BCFc706EDbAf5103196425cDf54289F
sparkster.site
Fake Sparkster crowdsale site
https://urlscan.io/result/9b6c3c08-d7d6-4061-a6d5-3d55b2ca0dbd/ …

ethereum-prize.com + more

---

blacklists/domains.json

myetherwallett.net
Fake MyEtherWallet Domain
https://urlscan.io/result/fa3e5c56-4ceb-4b4b-9572-03f03898c8c3/
magntech.tk
Hosting a fake MyEtherWallet (magntech.tk/01ef43c4b617f6/wallet/)
https://urlscan.io/result/aed35a9c-4e11-4a0d-855b-2c23984b0d1a/
coinzzz.pro
Hosting a fake Aragon giveaway (https://t.me/Aragonofficial & https://t.me/Aragonannoucement)
https://urlscan.io/result/c671b699-419f-49c1-babe-3ae336bc9ea4/
https://urlscan.io/result/e81cdbc9-812f-4937-88d3-7392b4a4cbb5/
today-ethereum.com
https://urlscan.io/result/0deae08e-688c-414a-97e6-e3fe675b5344/
address: 0x4dD0eF53784030fA675e2677F9CdC2a3e32E956B
ico.metronome.bz
Fake Metronome crowdsale site
https://urlscan.io/result/bc9e0689-3793-4d6c-8e77-8420781f5157/ …

myetherwallett.net + more

---

blacklists/domains.json

get.perfecteth.com
https://urlscan.io/result/4aea6e9f-3c80-4230-8da9-2b6225a6351a/
address: 0x6997726E03707Bf08032B8b6Da935cae80524bCA
perfecteth.com
https://urlscan.io/result/a67d8d88-a5c1-4850-97f1-ccc58e0fd681/
address: 0x6997726E03707Bf08032B8b6Da935cae80524bCA
newsair.org
https://urlscan.io/result/db00b2f1-fc35-4da9-8ae3-407eed4964ac/
address: 0xF1a4b668D15F0E66543e9F1F795cC2B0f97E3ef2
top-ethereum.com
https://urlscan.io/result/dc12715e-257d-469f-9c4f-e68cb57a4e27/
address: 0x83D7Cb758C30d067e99E9f52F9e4f987101aB888

get.perfecteth.com + more

---

whitelists/domains.json

Adds fenêt.re to the whitelist.
Fixes: #725

added xn--fent-ipa.re to whitelist

---

blacklists/domains.json

ethereum-claim.org
https://urlscan.io/result/72994984-e750-432f-916f-785e020e1039/
address: 0x2092B75719EC6f1dfE3f0d8C73239aD0297522BE
get.safesteth.com
https://urlscan.io/result/d4bdf505-2e40-4e97-8d48-22826ad999eb/
address: 0x37a8C55F6860e19f353686f5dd9c603ADB8448b6
safesteth.com
https://urlscan.io/result/8d0c3081-0e94-41c0-a7f6-708f8119467a/
address: 0x37a8C55F6860e19f353686f5dd9c603ADB8448b6
secure.ethscan.us
https://urlscan.io/result/02673a53-e59f-4113-acbc-aaec85e715d0/
address: 0x1A11585B374D5827F44e117e07941A8728a5f342

ethereum-claim.org + more

---

blacklists/domains.json

ethshare.org
https://urlscan.io/result/ba9e9637-afda-4032-860a-aa14ad4048e3/
address: 0x03E115D99F005F9df8AcCeC3F3d07F54b593eE96
ethergive.info
https://urlscan.io/result/f78872b8-15be-46be-ad8b-e77dcf1b168d/
address: 0xC71610821ac6042E52Be9d7d76df4c425F30f41f
myetherwalet.heliohost.org
https://urlscan.io/result/324c8485-c0f9-47b9-afe1-b769a109ee6a/
keyfundairdrop.typeform.com
Fake EOS airdrop directing users to myetherwallet.com.signmessage.me (https://bitly.com/2HTNWuj+)
https://urlscan.io/result/832bef2f-3cd3-46bf-95ad-e694a8879fd2/
eosdash.io
Fake EOS airdrop directing uses to myetherwallet.com.signmessage.me (https://bitly.com/2HTNWuj+)
https://urlscan.io/result/1a230f02-ae2c-406d-8a8a-238ec5365041/

ethshare.org + more

---

blacklists/domains.json

xn--coinbas-z8a.tk
Fake Coinbase - IDN homograph attack domain
https://urlscan.io/result/7e60dc3e-4e96-4583-a44e-e15b63609b32

xn--coinbas-z8a.tk

---

blacklists/domains.json

waves-platform.net
https://urlscan.io/result/4d7ebcdc-7703-4b4b-a232-142a4839447d/
address: 0x074f95064A579de2287B21B6ed33033C18CB80ef
myefherwaliet.com
Fake MyEtherWallet - Suspected address: 0x766316F65C88486bcb59Fd57D5CE0087780c1424
https://urlscan.io/result/a7c2e50d-1a92-4255-88d7-fc3d284ba075/
ethsafe.net
https://urlscan.io/result/20448380-df07-4237-b804-12b9d4aa07c1/
https://urlscan.io/result/99a5d5f8-beed-43a4-84ec-1fd95b8712a1/
address: 0x64Ebd0467304E04F96520aB73C6E07D40aD25970

waves-platform.net + more

---

blacklists/domains.json

c-kamowski.fr
Trust trading scam site. Bitcoin address: 19DBRq4M98XaeBjnjx2NuU9MMrTK3u259L
https://urlscan.io/result/373cc8e2-d04f-4a4d-bab5-d0f4d46f8f26
eosprivate.io
Fake KYC directing users to a Fake MyEtherWallet (myetherwallet.com.api.signmessage.me/signmsg.html) via bit.ly/2tj9f2U+
https://urlscan.io/result/1acbf584-c245-4106-9f34-87adf9d833ad/
https://urlscan.io/result/09a72fcb-180c-414a-88a9-aaa9dbe8fa05/
https://urlscan.io/result/b6563c24-0364-44cc-b1c1-e619e2f67f0f/
myetherwallet.com.api.signmessage.me
https://urlscan.io/result/be41ee23-b01a-41be-88f1-be81d6382a7e/
shapeshiftv.com
Suspicious ShapeShift domain
https://urlscan.io/result/194e79ab-0c52-4def-92f0-36b7383fc32e/
get-ether-now.com …

c-kamowski.fr + more

---

blacklists/domains.json

get.personaleth.com
https://urlscan.io/result/5c516db6-b791-45bf-83c0-46c90c9edfb9/
address: 0x9d03A3AD580cC2fb820349d3FF002Fb2FC7a6b19
personaleth.com
https://urlscan.io/result/efb5b67e-2e26-4b85-b065-507d2379b648/
address: 0x9d03A3AD580cC2fb820349d3FF002Fb2FC7a6b19
indexmarket-inc.com
Suspicious Idex Market domain
https://urlscan.io/result/9955cac9-cc6f-44a7-acdb-3af8d164d2f4/
mnyctervailliet.com
https://urlscan.io/result/ceac9e6e-3234-44e5-a112-037f19208329/
mnyidthewallot.com
https://urlscan.io/result/7947fc2a-73c3-47ba-aded-ec99f8cd1ced/

get.personaleth.com + more

---

blacklists/domains.json

idexmarketllc.com
Fake Idex Market phishing for keys
https://urlscan.io/result/da8918fb-bdbf-49ff-8843-339fa0001c9c/
idexwebaa.com
Fake Idex Market phishing for keys
https://urlscan.io/result/11279cd6-8a3f-4c8a-8095-254399b0013e/
ethfast.io
https://urlscan.io/result/efef9eb0-781d-4613-9f9f-342738a92d76/
address: 0x679A8cF6E181EbbcD9d14D0bd9595d8cFB79eCDf
givewaypromo.org
https://urlscan.io/result/0d9eeee9-50b0-41c3-9a49-acc57a732f41/
address: 0x83D7Cb758C30d067e99E9f52F9e4f987101aB888
ethereum-givaway.social
https://urlscan.io/result/a5586740-36ea-4ee5-b247-c65feebe7370/
address: 0x777c6aD16B303639489a38b369e423AA2c491884

idexmarketllc.com + more

---

blacklists/domains.json

ethaction.io
https://urlscan.io/result/4e026223-8976-4fa4-855a-0f0eebe1b92d/
address: 0x679A8cF6E181EbbcD9d14D0bd9595d8cFB79eCDf
24h.szakdoga.net
Trust trading scam site. Suspected address: 0x9f05a98487b64608ddE56A23cD1B031f4C567f3f
https://urlscan.io/result/d85b83d8-1698-4422-8501-e30de42fed64/
address: 0x77C89A9987017Fd0AF1c7d057FfB9e9fA254aa4b
luno-help-desk-update.weebly.com
Reported as a fake Luno login (it is now down)
https://urlscan.io/result/491fc368-0abd-43e7-ad31-7f615cea05c2/
airdropform900.typeform.com
Fake Airdrop directing users to a fake MyEtherWallet (https://myetherwallet.com.api.root.signmsg.me/signmsg.html) - https://bitly.com/2thn41W+. Suspected address: 0x8b9310e47cd2d4aad77735a3218d9420cb152709 …

ethaction.io + more

---

blacklists/domains.json

event-eth.org
https://urlscan.io/result/4db85e1c-5510-445e-9e81-16f945ab2ff1
address: 0x680f7bEa6EbA9AdcD0F47A0DE630CfA8F95Bf0ba
giveawaypromo.org
https://urlscan.io/result/5b862df2-d892-4487-a126-7f8bde13f88b
address: 0x224B9f4666472682f3e805f4dC1e0Fc39B7B96fB
aireth.today
https://urlscan.io/result/cea92a0e-3a97-4159-86dc-f7a41485d11f
https://urlscan.io/result/a529e2d1-6a40-40aa-9ea8-d88c5fc3bb78
address: 0x443F933362D9472ac8Fb9d1C4a8EaD512881630D

event-eth.org + giveawaypromo.org

---

blacklists/domains.json

eos-platform.net
Fake EOS web wallet - email verification from ddddssssmmmm.fvds.ru (188.120.227.79)
https://urlscan.io/result/62b9f333-28fc-4299-8ebc-ba5395d5d4b6/
address: 0x73BAF168D9f5FEe3D845f33b3567Fe916F730838
btcfast.io
Trust trading scam site. Bitcoin address: 33RRw7sdn6SQsNGPAb4fGUuAM9yHfL2ecH
https://urlscan.io/result/a7e2cf99-51cd-4dec-aadf-f9b2c85582e2/
idexxsoftload.com
Fake Idex Market domain phishing for keys
https://urlscan.io/result/a3c9a071-0ca0-4497-9216-c8029bdcbe74/
idexmarket-corps.com
Suspicious Idex Market domain
https://urlscan.io/result/3026568a-8393-4317-8e54-50486f9a3c0b/

eos-platform.net + more

---

blacklists/domains.json

neo-x.info
Fake Neo web wallet
https://urlscan.io/result/12f70feb-05fd-4574-894c-e8d301b05777/
myetherplace.com
https://urlscan.io/result/80b3d0f8-b047-4a2d-a13b-5a680d45c45a/
address: 0xee07f244d1bc5b077296975bd062c930b9ab9ea6
ether-give.live
https://urlscan.io/result/6a5d77ec-9ef4-4264-b320-e749ccd59b72/
address: 0x11608c87d514d55e28eb94984bdbacd3fd38b182
btc-give.org
Trust trading scam site. Bitcoin address: 1KXLXfdFS7aKZJWwVxH9im9WyzA9SBBEed
https://urlscan.io/result/3e05b081-d542-40bc-b00b-24ad20dcc8bc/

neo-x.info + more

---

blacklists/domains.json

e.airdropeos.com
Fake EOS Airdrop phishing for private keys
https://urlscan.io/result/d004a1c0-fa50-4c54-9159-d9ebaab5f024/
https://urlscan.io/result/8f9019f7-78ac-43eb-81d7-3ebfd76f6b50/

e.airdropeos.com

---

blacklists/domains.json

get.ethsupport.net
https://urlscan.io/result/0c7e0e14-420e-4537-aa68-0acbd782025d/
address: 0xC0095047d767857Bb40CC77EF54569d4124984C3
ethsupport.net
https://urlscan.io/result/0818f599-4ac3-44fb-83a7-2ac55c913224/
address: 0xC0095047d767857Bb40CC77EF54569d4124984C3
newsair.info
https://urlscan.io/result/23544306-fe1c-4f6e-8148-6d3fb2dcec82/
address: 0xF1a4b668D15F0E66543e9F1F795cC2B0f97E3ef2
officialgiveaway.org
https://urlscan.io/result/974ca124-e17b-4f55-adf3-d6cfe591e831/
address: 0x83D7Cb758C30d067e99E9f52F9e4f987101aB888
collectionseth.com
https://urlscan.io/result/98d4c6c1-2eff-45a1-8fb3-dce3fbde1c1d/
address: 0xfb997Ea4c102fAd4ec67f8bb069752030C0C0531

get.ethsupport.net + more

---

blacklists/domains.json

myeostrust.com
Fake EOS web wallet phishing for keys (POST /store.php)
https://urlscan.io/result/da324895-cf75-4897-82f4-b0550061c2bd
eosdrop.xn--mythrwallt-c7a86c5a.com
Fake EOS airdrop. Directing users to a fake MyEtherWallet xn--mythrwallt-c7a86c5a.com/signmsg.html via bit.ly/2Jlh9zL+
https://urlscan.io/result/9f701baf-90d3-4cea-83d2-7db93d04230d
https://urlscan.io/result/1e5fe28a-08c0-4093-ad41-68c1b7b16440
eth-claim.net
https://urlscan.io/result/73088752-e7cc-4e5d-a73e-5c4fb9ace29c/
address: 0x45C3eF2bc2719586Cd92766B3895868d3EE9Ef92
ethfreegift.org
https://urlscan.io/result/b69dd93f-4478-4420-845c-f8a2b6d3294c/
address: 0x46Cbc3c3710dC4a632842e155f18f30d4AB38aaC
myenterworlld.com
Fake MyEtherWallet/MyEtherWallet …

myeostrust.com + more

---

blacklists/domains.json

xn--eosauthorty-wcb.com
Fake EOSAuthority phishing for keys (POST /store.php)
https://urlscan.io/result/b899a6d2-b8e6-4f78-8592-34fbad046aa8/
btc.etherfree.info
Trust trading scam site. Bitcoin address: 18b7PTLaa2TPtn5V5moBwSsWTEm6Ny2n8Y
https://urlscan.io/result/bf88caa6-d8a7-4f1e-aedd-9d92ed30d8a8/
etherfree.info
https://urlscan.io/result/e6dbae7f-adf7-4c65-8c3d-0f600edb6210/
address: 0xba8A5cF96D605B630025E3e2C8bd177391e32122
free-ethers.org
https://urlscan.io/result/332578a1-1a5c-45f3-b8b4-10154f79e383/
address: 0x4c6cdD82bF2B0627350bB660C2a18B2Db8880Ce1

xn--eosauthorty-wcb.com + more

---

blacklists/domains.json

ethereum.odyssey.center
https://urlscan.io/result/3658676c-7027-4976-a5f3-d3196a702eae

ethereum.odyssey.center

---

blacklists/domains.json

ethextra.net
https://urlscan.io/result/12556668-a423-4090-bf6b-6c04b02c7918/
address: 0xA1FF3Bc95D29C7DFCcD60C2226697b9C9aC0a16b

ethextra.net

---

blacklists/domains.json

ethereum-event.com
https://urlscan.io/result/0412668a-97ac-4452-aeba-d26d466ea789/
address: 0x6668bD45B15E2775F03e738Ef6257637A9745287

ethereum-event.com

---

blacklists/domains.json

eos-authority.com
Fake EOS form phishing for private keys
https://urlscan.io/result/c3a099c6-24e1-495b-9deb-36aa9c053cdb/
myethrawallet.com
Fake MyEtherWallet (redirected via https://bitly.com/2yI7J0c+)
https://urlscan.io/result/fe89292b-c7c3-4b27-925c-71b8a0935c80/

eos-authority.com + myethrawallet.com

---

blacklists/domains.json

post.mediumdotcom.top
Trust trading scam site (directing to ethe.mediumblog.top/payment.php)
https://urlscan.io/result/5e7d937b-622a-4674-a2d9-3b9f40d6e647/
https://urlscan.io/result/0dc1ea20-badc-4d6d-ad86-fb3b37746335/
https://urlscan.io/result/3fa6a03a-e288-4344-9ea0-280e470ee31e/
https://urlscan.io/result/dacc26d6-0f3e-43f6-bf34-308ae99c61a0/
address: 0xaec2Cc8986BB14C0C604d5Adf725BA33920102bc

post.mediumdotcom.top

---

blacklists/domains.json

wallet.eostoolkits.io
Fake EOS web wallet. Stealing private keys with POST /eot/store.php?mapza=public&mapza2=private&action1=1
https://urlscan.io/result/9849f27a-ea51-4532-873a-b37d21ee0ed6/
eostoolkits.io
Fake EOS web wallet. Stealing private keys with POST /store.php
https://urlscan.io/result/7adfaf8b-0047-4fff-8976-b747dbaffab5/
chanfelly.com
Suspicious Changelly domain
https://urlscan.io/result/834cc2cf-f60e-48d0-a06d-642de3ae6956/
idiex.market
Fake IDEX market stealing keys
https://urlscan.io/result/24395aa3-8d27-48c4-9710-2f3f31fde2ff/

wallet.eostoolkits.io + more

---

blacklists/domains.json

ethaway.com
Trust trading scam site (promoted via bit.ly/2Iw0Kae+)
https://urlscan.io/result/038a3df4-dfe1-4981-bf8e-887843c96b70
address: 0x1c40D1a1cAc7C586b9509C565296F91c8441aF9f
eth.tronbonus.network
https://urlscan.io/result/39c13514-f4ea-45a6-ae8d-0eda4284f89f/
address: 0x0f89B38968065A571eeaf34dD6BF2093fb55c20F
eth-gift.net
https://urlscan.io/result/7b85d749-3b52-4bc1-89a5-56d5fb567769/
address: 0x73c9B03B1DaDeA685f34b17DdAFBC11BD6327B6D
eosdark.com
Fake airdrop directing users to a fake MyEtherWallet xn--mytherwaet-y7a46ha.com
https://urlscan.io/result/31015722-adc4-4edb-aeaf-ec9a83f30b5a/
https://urlscan.io/result/f5bf5d08-cd14-43b2-8ac6-55e1d2da9d3b/
xn--mytherwaet-y7a46ha.com
Fake MyEtherWallet domain - IDN homograph attack domain …

ethaway.com + more

---

blacklists/domains.json

eosauthorithy.com
Fake EOS domain - phishing for private keys with POST /store.php
https://urlscan.io/result/e09358b9-6ae8-4a67-aaf2-14ddc2fd6561
ethereumanniversary.org
https://urlscan.io/result/5780b378-df75-49c5-8459-c6d178a5a4bd
address:  0xaec2Cc8986BB14C0C604d5Adf725BA33920102bc

eosauthorithy.com + ethereumanniversary.org

---

blacklists/domains.json

idext.market
Fake Idex market. Suspected address: 0x31f530b58efa42dab4bd1789184b4cc6b884dea0
https://urlscan.io/result/c85717c0-7f56-4953-81e1-0bce969e9f9f/
etherdelta.com.ua
Fake EtherDelta
https://urlscan.io/result/b2ed10fc-b177-4729-8995-faefdc5fb9b9/
etzerdelta.com
Fake EtherDelta
https://urlscan.io/result/0084d818-c498-4af1-a8e7-d4e04755632d/
forkdelta.co
Fake ForkDelta
https://urlscan.io/result/cbef90cf-7a5b-406b-aae8-35e2769adf59/
myeftervvellet.com
https://urlscan.io/result/402b4def-fa9e-4af7-98e2-23f384230e48/

idext.market + more

---

blacklists/domains.json

eosauthority.website
Fake EOS site phishing for keys (POST /store.php)
https://urlscan.io/result/de7e0387-f090-4ec9-9dd0-280912c3dae0/

eosauthority.website

---

blacklists/domains.json

dapp.doubledouble.io
Fake Ethereum doubler
https://urlscan.io/result/fb577daf-cbe4-49b5-8d79-14413f00b78a/
https://urlscan.io/result/c756b21e-3a88-456d-98c2-54565694eb30/
address: 0x0a4a2413d7c604647c7788fd3564b3c54fe06763 
bitcoinvest.cc
Ponzi scheme
https://urlscan.io/result/21b7aab8-e930-4f0a-9ca1-9a7c1f805489
https://urlscan.io/result/aa42dd7a-864d-4257-a3f0-04a878bb6390
address: 0xaedc8a3afc62a3deee4eb232bfdb28058bf554d8
celebration-eth.com
https://urlscan.io/result/69524210-262e-4b62-83f2-bdfac1eb9001
address: 0xB6eCd180F5CBB9167147394841D31f94EfF77DBf

dapp.doubledouble.io + more

---

blacklists/domains.json

pumphash.com
https://urlscan.io/result/7d85cea8-0667-4fdb-a5b3-69cc6b091cdb
address: 0xDd1f234967913C25f176bda85A9825BA880e447E
tronplay.network
Fake Tron airdrop directing users to a fake MyEtherWallet xn--mytherwalet-srb35c.com/signmsg.html via bitly.com/2K90ioo+
https://urlscan.io/result/8e826d40-2b07-43f3-ade4-f14faadd9746/
https://urlscan.io/result/08473218-370c-4d36-8233-8a6fdd4759b8/
xn--mytherwalet-srb35c.com
Fake MyEtherWallet phishing users keys
https://urlscan.io/result/9f6b9d9c-671e-4afd-9d52-aa5983fba80e/
eosauthority.bitballoon.com
Fake EOS site phishing for keys
https://urlscan.io/result/f4756abc-47b0-438e-8d2b-18d66b8c575b/

pumphash.com + more

---

blacklists/domains.json

hitbtc-login.com
Fake Hitbtc site phishing for logins
https://urlscan.io/result/556feb89-8283-43bb-a5d8-6ebedcb9d11d/
https://urlscan.io/result/6d905b16-a7f8-4db4-a897-3e3bd88ec88d/
promobinance.com
Fake Binance site phishing for logins
https://urlscan.io/result/16215007-665e-4295-b01b-158c27b69f28/
bittrex-ix.com
Fake Bittrex site phishing for logins
https://urlscan.io/result/e48cb58b-d1f9-43c0-b14c-fa783a4f3409/
bittrex-app.com
Fake Bittrex site phishing for logins
https://urlscan.io/result/a3ba0b9b-8d10-4f7f-a55a-aced69817420/
bittrecx.com
Fakr Bittrex site phishing for logins
https://urlscan.io/result/14f00645-e1c2-4a7b-b71b-cf892e96c17d/
https://urlscan.io/result/37f41dc5-b351-4256-b3e9-0890b8aadae3/
telegra.ph/Bittrex-giving-away-5000-Ethereum-ETH-03-26 …

hitbtc-login.com + more

---

blacklists/domains.json

ethbig.net
Trust trading scam site. Being promoted by Twitter user 321652568
https://urlscan.io/result/64816934-168f-4e31-8245-48359ba33d2e
address: 0xA22270850FabDE01E1f5c5879ea65DD82890AF31
vechain-platform.org
Fake VeChain web wallet
https://urlscan.io/result/af61a7f8-45de-4d5e-9ab4-cf5c08900b80/
address: 0xEaAaF85E36267d4a44532E4df628254D6cE7f9cD
vechain-block.com
Fake VeChain web wallet
https://urlscan.io/result/64cc6bd1-65cf-4b4b-91bf-a7f2bbc113ae/
address: 0xaf48cfd4eee2b9f185fda12bf0cbbec5b90ed8c9
----
eth.blogmedium.top
https://urlscan.io/result/e585f1f3-72b4-46ac-8a4c-4d93b97d5edc/
address: 0xAeD20775C1d0D64796C9D023c8a7ac84557BA1Ad
celebration-eth.com
https://urlscan.io/result/29f0f450-ffe5-4e33-aa4a-47f55683f428/
address: …

ethbig.net + more

---

blacklists/domains.json

eth.mediumblog.org
Twitter Phishing Site And Fake Medium Site
https://urlscan.io/result/f0e9b108-7087-4367-b58a-1810cc7826e1/
Address: 0xebe808320931473e5ED488e582F93dEdf8369A77

eth.mediumblog.org

---

blacklists/domains.json

ethereumfoundationgift.tumblr.com
Trust trading scam site linking to ethe.mediumblog.top/payment.php
https://urlscan.io/result/1e011872-7c62-460b-8266-a633ff065b7e/
address: 0x5208d7f63A089906889A5A9CAed81E9C889E64F8
btcpramengyve.com
Trust trading scam site. Bitcoin address: 34oxKKuq8g7W23gvDD6K3bpbTVCg1FLYGb
https://urlscan.io/result/14575086-86a1-4002-930b-84817f383e62/
claim-btc.org
Trust trading scam site. Bitcoin address: 1FVwwp98FBKJV8MzSFNN38afSHqiYrxXjs
https://urlscan.io/result/a4d0b7b8-53cc-4bba-ac8d-0cdc442ac4e4/
btcbig.org
Trust trading scam site. Bitcoin address: 15HM6dXaUvDdXri3rz44wKv13No57h4TN
https://urlscan.io/result/17b2ab1e-bffb-4728-a591-358459a23f9b/
btcbonus.win
Trust trading scam site. Bitcoin address: 1Co5gnEn1wBTyigfH9udnuUgha27pdETS9 …

ethereumfoundationgift.tumblr.com + more

---

blacklists/domains.json

etherdeltha.info
Suspicious EtherDelta domain
https://urlscan.io/result/3a5f8674-dbe4-4948-a826-f294f19bdecf
forcdelta.com
Fake ForkDelta stealing keys
https://urlscan.io/result/d5b7c135-fc49-4671-b333-5be19d944e64

etherdeltha.info + forcdelta.com

---

blacklists/domains.json

ethpromofree.com
https://urlscan.io/result/dd9666df-e862-4760-9c98-cbe6e9dc0746/
address: 0x0E50faC3B2eaEe7BA87B6d644B6c03E946B19f8d
sparkster.com.de
Fake Sparkster crowdsale site
https://urlscan.io/result/b516e3f9-1756-4905-8b6a-bbe0c9bb2de1/
https://urlscan.io/result/132957ea-6cab-4778-84ad-45fdf85adfb6/
address: 0xd0aCAc843AAAb4Cef20b322405405E67e90147d1

ethpromofree.com + sparkster.com.de

---

blacklists/domains.json

get.lotsofeth.com
https://urlscan.io/result/a1b771e4-d7e1-4090-9139-97552cfc81c7
address: 0x8EEad6A5776dCE374257bF7D4500CfE3C1e362a6
lotsofeth.com
https://urlscan.io/result/aaf0c166-7d1f-4ecf-a4c6-1189017602e3
address: 0x8EEad6A5776dCE374257bF7D4500CfE3C1e362a6
ethcountdown.ga
https://urlscan.io/result/51d4b552-9d18-4ed1-b14e-0e08ca86f9c9
address: 0x8781ebb17371D0c530285433308C02b81b895DAE

get.lotsofeth.com + more

---

blacklists/domains.json

ethmore.net
https://urlscan.io/result/987cb0d4-9fde-49e7-9f96-ae63832778be/
address: 0x0c2cB2d98F9f5ed558D9560D0E38E47187b2Bfe1
electrunn.org
Fake Electrum wallet download site
https://urlscan.io/result/212ae255-14a8-41ac-8274-f812bd898847/
myehterwallct.com
Fake MyEtherWallet. Stealing keys with GET ____key?key=%7B%22type%22%3A%22Buffer%22%2C%22data%22%3A%5B18%2C52%2C86%2C120%2C158%2C254%2C254%2C254%2C254%2C254%2C254%2C254%2C254%2C254%2C254%2C254%2C254%2C239%2C239%2C239%2C239%2C239%2C239%2C239%2C239%2C23
https://urlscan.io/result/1cc33869-41d9-4a9c-bbb0-ab0e6f0d99c5/
https://urlscan.io/result/77b85819-e064-43a3-b355-d4d8f85bb1c8/
mychterwallet.com
https://urlscan.io/result/1cc33869-41d9-4a9c-bbb0-ab0e6f0d99c5/

ethmore.net + more

---

blacklists/domains.json

bittrcex.com
Fake Bittrex phishing for logins
https://urlscan.io/result/e936a073-f919-4d9b-be38-cf83c42a6672/
https://urlscan.io/result/f6ac9bc2-36da-4ca3-ac0d-12c8b5c84a6d/
binance.promoting.world
https://urlscan.io/result/2c7baa0d-8c8c-4eb9-a1cc-dcb63fc66a6e/
https://urlscan.io/result/dcd6260a-b18a-4794-9193-4e53f47b5b22/
address: 0x4BC69a335D353dce4De09399b24079aEd48F7865
ether-promotion.info
https://urlscan.io/result/fb4bcb0f-0582-4b3c-90df-34349d7be44e
https://urlscan.io/result/6c2a9615-c380-4b29-a3ce-ffc30af4ad40/
https://urlscan.io/result/1af55c90-90b8-4cbf-a3e2-30b753649cda/
address: 0xa9Ec9789c80eE9DCE8840f114112c6bADC1Ecfda
eventeth.com
https://urlscan.io/result/a2511742-83c0-4656-be7b-41aaf87cc990/
address: …

bittrcex.com + more

---

blacklists/domains.json

ethcryptopromos.com
https://urlscan.io/result/fbab4c5f-e91b-4c57-981e-332b1110d8ae/
address: 0xAaaA3b6D0b72aDE31A99C933a8BF737a4E904527
ether-foundation.website
https://urlscan.io/result/cccf2ee9-9fa0-4fd7-a3d6-6f3ab9971686/
https://urlscan.io/result/47ae77f0-0ac7-4090-a878-50c7bc7871d4/
address: 0x52b949fb4678c20873135ce6b3727949432af1d7
ethofficial.net
https://urlscan.io/result/7dd89084-6d85-402d-a665-0ef73643ef5e/
address: 0x3bD330F121c493dB91e59d9125968D3Df090A66F
etherclaim.net
https://urlscan.io/result/8a158e81-7c0c-4e73-bd77-d0c5aa439cd9/
address: 0xab5fD091C56A9B801E945A902e986E894e4f407D
medium.ethereumfoundation.top
Trust trading scam site (also linking to ethe.mediumblog.top) …

ethcryptopromos.com + more

---

blacklists/domains.json

safe.eth10000.org
https://urlscan.io/result/b200a55a-1c7e-49a5-871a-d892fa1cccca/
address: 0xF7d0FcD21D7bF83358656BaAEb3C8c1903Aa9614
eth10000.org
https://urlscan.io/result/b200a55a-1c7e-49a5-871a-d892fa1cccca/
https://urlscan.io/result/1b5a24ff-59fb-42b0-82af-5ade3b5f167a/
address: 0xF7d0FcD21D7bF83358656BaAEb3C8c1903Aa9614
gift-eth.org
https://urlscan.io/result/7430f1ef-d86f-4b53-a0be-93fbe5f4b9a7/
address: 0x8BcB21d162Af74718C583E249Ab112B9E6Ad5267
ethsoffer.com
https://urlscan.io/result/61197b05-f0c2-47a7-a2ef-43110289e8e5/
address: 0xF7fB243Ff0df4B35f5F7Fa5317c128f16E71cF9A
ethonline.io
Fake Ethereum web miner
https://urlscan.io/result/174dff20-67ce-48bc-a05d-dc31659a8e81/
address: …

safe.eth10000.org + more

---

blacklists/domains.json

ethereumpromote.wixsite.com
Trust trading scam site. Promoted by Twitter user id 1012075718405185538. Directed via bit.ly/2sK3rPO+
https://urlscan.io/result/86a81ee8-0925-447d-84e8-c4874a7dd680/
address: 0x159CCfFB293a06Aafaec1b254A00522A2bC40639
ethgive.club
Reported trust trading scam site. Reported address: 0x9E91ea0C442dd2B41CC7fE2d54fAEcd34f59C134
https://urlscan.io/result/50b4d5a1-460b-4eb2-82d8-519526fad919/
etherclaims22.top
https://urlscan.io/result/b17ef239-488e-49b9-b4ab-0c99dc7a7f54/
https://urlscan.io/result/6194fca7-577e-498c-833b-985b85c10de6/
https://urlscan.io/result/420d9009-48f4-4353-a88f-1ed76624b3da/
https://urlscan.io/result/065ebdf3-8118-4a69-8e7e-d4cb2528f8c3/
https://urlscan.io/result/11c055bf-75d6-40d3-a9c4-040c94a87104/
address: …

ethereumpromote.wixsite.com + more

---

blacklists/domains.json

www.indexmarkket-site.com
Suspicious IDEX market domain
https://urlscan.io/result/118d3ff8-b9b3-4639-8244-5a7ef9153f49/
idexnetone.com
Fake Idex phishing for private keys
https://urlscan.io/result/e22d685d-89c0-4f10-85e6-df6a78bdc1b9/

indexmarkket-site.com + more

---

blacklists/domains.json

ethmore.live
Trust trading scam site. Promoted by twitter id 59058979
https://urlscan.io/result/f717080f-2d14-4332-b68d-981ab8978ddd/
address: 0x68E2EF6244Be67fE149C8309e1c5E978fa1a3Cab
myehtewallet.com
https://urlscan.io/result/f208e7fc-7508-4b6e-b53d-be20fd832b51/
meyehterwallet.com
https://urlscan.io/result/e45b56d3-3173-4b96-915b-be9eb6803bf5/

ethmore.live + more

---

blacklists/domains.json

ethpromotion.info
https://urlscan.io/result/a2d72540-c0cb-4d3e-9f11-c26d0f27a983/
address: 0xbde430F54A63016D8A5F31F243761653728086A2
secure.ethgiftnow.com
https://urlscan.io/result/85a13cd1-9411-4e5d-9319-2228d276884f/
address: 0x3d075995577c0C3c65a466Fee47FfB1bA6a41B02
btcpromotion.info
Trust trading scam site. Bitcoin address: 1FEt2GWxEidTKz1PkFuiccKTMD5AHkdRdq
https://urlscan.io/result/6e552901-cc4f-4267-b42b-358ab99e69f7/
betaclient-rzcoinwaps.cf
Fake Waves client phishing for seed words with POST /sendwaves.php
https://urlscan.io/result/63e559be-ffc3-4bde-8c61-fbad439cbeb1/
----
elon-gift.com
https://urlscan.io/result/a5630c07-f073-46ab-b340-a45a1266b625/
5000eth-giving.online …

ethpromotion.info + more

---

blacklists/domains.json

idexd.market
Fake Idex market phishing for private keys
https://urlscan.io/result/8268cba4-ff7c-48d9-b1ab-45c1b3889454/
ethbounty.info
https://urlscan.io/result/f2cc8daf-b4b0-4a5c-bb77-d602b2683119/
https://urlscan.io/result/350c648c-e49b-4810-84f8-2f8e820adcc9/
address: 0x429D386Adc915adE21593609B1b89b976B2F2af4
address: 0x1177D4F07C6EF70f51cF23493C66E713f7acCCdA
eosbounty.co
https://urlscan.io/result/5a6dae37-9e6c-488a-8678-c871a28c97da/
address: 0x4E360fAF9F228452aF65C9B7a89AE023363672b4

idexd.market + more

---

blacklists/domains.json

cashaaprivate.com
Fake KYC form redirecting users to a fake MyEtherWallet myetherwallet.com.rootsign.icu/signmsg.html via bit.ly/2ukYhLw+
https://urlscan.io/result/62c1eb23-1a08-460d-8484-fdd52c469dda
https://urlscan.io/result/582db137-208a-4e7b-bbd1-4031d35c8824/
signcontract-etherwallet.net
Fake MyEtherWallet redirected via https://bitly.com/2Mo5i5F+
https://urlscan.io/result/afd0e394-9884-4a9a-aede-c5927dff291e/
ether-idex.online
Fake MyEtherWallet phishing for keys with POST /bot/bot.php
https://urlscan.io/result/e4c2eb53-f9ae-4a3e-ba0a-cc85ff7772d1/
https://urlscan.io/result/410ec5cc-4750-42a5-809a-c062a7c3808b/
mediumpost.ga
https://urlscan.io/result/8438b7cf-a565-4000-84fe-71416abc9043/
address: 0xff8e6af02d41a576a0c82f7835535193e1a6bccc
ocntoken.com
Fake …

cashaaprivate.com + more

---

blacklists/domains.json

walletico.com
Fake Idex phishing for private keys
https://urlscan.io/result/d914dec6-68ed-4eb7-a04a-42e5b5e8ae52

walletico.com

---

blacklists/domains.json

refundcontract-etherwallet.net
Fake MyEtherWallet. Users redirected over email via https://bitly.com/2L3Ua1a+
https://urlscan.io/result/6b13d39e-005e-40bd-ae29-b45bfc88573b/
idexr.market
https://urlscan.io/result/e4951908-3628-491f-98d0-961ebbb422dc/
https://urlscan.io/result/b2db3889-9b3e-48b3-8226-38c284c4ff8d/

refundcontract-etherwallet.net + idexr.market

---

blacklists/domains.json

elonmusk.ethgivings.net
https://urlscan.io/result/adfc41dc-5ee3-4ded-9965-1905a96062da/
https://urlscan.io/result/70387c2f-11d6-45f4-910d-366ee9991a2c/
https://urlscan.io/result/2d3f7129-4ada-4538-8ed9-ede8f0d4cd30/
https://urlscan.io/result/8417e473-266b-49da-b04b-499731d97310/
address: 0x2B164ae662a0AB1832C87cb4A226EFEC56219FB6

elonmusk.ethgivings.net

---

blacklists/domains.json

index-markett-network.com
Fake Idex market redirecting to idexmarkketslogin.com
https://urlscan.io/result/00b77930-ebd4-4685-924a-69372d0624bc
idexmarkketslogin.com
Fake Idex market phishing for private keys (iframing ideeweb1.com)
https://urlscan.io/result/064098d1-05c2-40b1-96f1-d2312fa5edba/
ideeweb1.com
Fake Idex market phishing for private keys
https://urlscan.io/result/d1876449-32c8-49a5-92bb-e8969f31fac6/
https://urlscan.io/result/35ce3c7e-04f5-4cd5-ba36-7eabd96c01e5/

index-markett-network.com + more

---

blacklists/domains.json

ether-event.com
https://urlscan.io/result/49acbd6f-d2fe-4dc2-bab6-1c7d07440aa7/
address: 0x8729Abb00a517bBA3d615ed13E7C9C55aB311D41
w-eos.com
Fake EOS web wallet
https://urlscan.io/result/925c99e3-2f68-4926-b28f-bb90f2267934
address: 0x5Ef4EC670246Af663F64aFf354a30Ca54B43DAFD
----
top-ethereum.com
https://urlscan.io/result/d79c68ea-90fa-41d7-b33d-97bd9df45d0d/
address: 0x9844F5C5F9aA7146a74ffC7b9227742acFA71dEa

ether-event.com + more

---

blacklists/domains.json

login.blockchaim.co
Fake Blockchain phishing for logins
https://urlscan.io/result/66142f8a-f22b-41af-8f20-8e14add2287e/
https://urlscan.io/result/237b03d0-003b-429b-a403-28732740bca9/
transactionlist.info
Hosting subdomains for phishing NEO and MEW users

login.blockchaim.co

---

blacklists/domains.json

mcafee.promo
https://urlscan.io/result/53a9bb6f-cc47-44d6-b5ae-a473ec5bc93b/
address: 0xD8D0506ED425364EE126819E8b73Fc3160C39D49
eth60.top
https://urlscan.io/result/cf408e48-82d3-4bc8-a77c-b6aaade8d155
address: 0xab7ec7596fc05bc55afc07008cc06c1193ed6f9a
getfree-eth.org
https://urlscan.io/result/7b0125bd-957d-4eb5-a0f9-f7860340e575/
address: 0x2B1C266E2a39a7a30aED472Fad47d6b6AB953F7e
vaxx.co
https://urlscan.io/result/a62acc3a-d00f-47ed-8915-697e8804c243/
address: 0xD8D0506ED425364EE126819E8b73Fc3160C39D49
cryptoether.info
https://urlscan.io/result/005d3c60-0798-428d-92b1-0225f4c271c3/
address: 0xA4F06F1afB7B8589D1F4609257e5010C30eD3D2b
coincapitals.org
Trust trading scam …

mcafee.promo + more

---

blacklists/domains.json

coinssafe.org
https://urlscan.io/result/df104578-45c5-4980-8471-4a328f5c875a/
address: 0x68AaCF41FA22ecD5ca0BB102dA46b0f503E2E168
idex.group
Fake Idex domain
https://urlscan.io/result/088fcd3d-2019-4949-ae7e-4cad6703c187/

coinssafe.org

---

blacklists/domains.json

getethernow.org
https://urlscan.io/result/eec0ccd1-115e-4da6-b008-3ba28a0c789a/
address: 0x7aA266963882F13eB0Ab5920E16aFeF2F26cDa8f
officialairdrop.com
https://urlscan.io/result/b3b488c7-01e2-4dde-abf6-5d3e2dcf09dd/
https://urlscan.io/result/ef945c75-0598-48e5-8fd9-3b974ef0643f/
address: 0x451ba6133b64829398fe074ae649a7998acb16f3
eth-event.com
https://urlscan.io/result/22bab091-fa4d-4ee0-be17-e2fa83240360/
address: 0x8729Abb00a517bBA3d615ed13E7C9C55aB311D41
ethclose.info
https://urlscan.io/result/32ed5540-a90b-430f-8ec0-bad957bfb940/
address: 0x74a01390635D8D4016827fA3AfB1A0f6c33eD8d8
freecoindrop.com
https://urlscan.io/result/09fecd3b-2b74-4399-9993-c112e66a585f …

getethernow.org + more

---

blacklists/domains.json

idex-markt-roosen-gmbh.com
Suspicious domain targetting idex users (being iframed on idex-market.me)
https://urlscan.io/result/037c8054-f7cb-4881-9b3f-f5903348460a/
idex-market.me
Suspicious domain targetting idex users (iframing idex-markt-roosen-gmbh.com)
https://urlscan.io/result/c2361e20-385f-403a-a0d7-40f9f3188397/
iclex-market.com
Suspicious domain targetting idex users
https://urlscan.io/result/3f5eb5f9-3934-4640-b0f4-02483558f071/
xn--dex-market-58a.com
Suspicious domain targetting idex users
https://urlscan.io/result/612a4b4f-dcb1-4d46-8d63-036e627e8957/
idex-markett.com
Suspicious domain targetting idex users
https://urlscan.io/result/12e97d2e-67c2-428d-b6d4-c9cc0730dde0/
medium.getethernow.top
Trust trading scam site - directing to verify.ethereumnow.top/payment.php …

idex-markt-roosen-gmbh.com + more

---

blacklists/domains.json

dailycurrency.ml
https://urlscan.io/result/7f1521ae-b823-457b-9dc9-7e736028cab5/
https://urlscan.io/result/7f1521ae-b823-457b-9dc9-7e736028cab5/
https://urlscan.io/result/3dc9e2ff-75a5-4cb7-bf19-a0b9a20947e7/
address: 0xFc6BB078EC56C85E8f7adDFed0F2dE6CB86ee3c3
ethgivewaypromo.info
https://urlscan.io/result/7dc550d7-6553-4ed1-8b6f-885057d1b84a/
address: 0xC597498f0d102036ff7bf9fDa401F3174d2E9D96
xn--etherem-y24c.com
Fake Ethereum site - IDN homograph attack domain - directing users to xn--mythrwallt-yq3ecf.com/#eth-staking - email sent from info@mail5-ethereum.com
https://urlscan.io/result/097223bf-c71b-4f9a-8ac6-ca406b5c5a08/
https://urlscan.io/result/e6317331-faa5-48b0-bd58-02b9f526eb13/

dailycurrency.ml + more

---

blacklists/domains.json

claimprize.org
https://urlscan.io/result/5e4f3c33-1ca8-450b-bc00-76ac1909bfd9/
address: 0xaE34b154ADA796cFEbE8a60D265d266eF809Fb05
eosgas.net
Fake EOS KYC form directing users to a fake MyEtherWallet myetherwallet.com.api6.icu/signmsg.html via bit.ly/2LrOL4a+
https://urlscan.io/result/4cf40f3b-6ce0-4180-8b57-59d7708138cf/
https://urlscan.io/result/fdc2c7c0-6e1f-4531-bd33-d63381338239/
myetherwallet.com.api6.icu
https://urlscan.io/result/0b1ddd32-0b26-4a64-884f-93c218885caf/

claimprize.org + more

---

blacklists/domains.json

idex-market.biz.pl
https://urlscan.io/result/203a5dfa-5488-4956-b219-3a0dc039b917
https://urlscan.io/result/8b2e6516-ffcd-481b-a7b8-dcaa29d037f3
getethereumforfree.com
https://urlscan.io/result/80a28520-7403-442a-b235-f5467e12e626/
address: 0xC7566BA63f39bA75B56EAdc0328F9A76Dbd1ADf3
medium-hitbtc.tumblr.com
Trust trading scam site linking to http://ethereum-return.com/hitbtc/payment.php
https://urlscan.io/result/5b63be29-8112-4707-b451-5f96bf72b1df/
address: 0x8C500BD17174e8604ff9aD3399bD13af245EeF52
ethereum-return.com
https://urlscan.io/result/491ef95c-935f-4541-8a1e-24d207bfea45/
https://urlscan.io/result/f47b89a0-f631-43be-8ed6-885234acf4de/
address: 0x8C500BD17174e8604ff9aD3399bD13af245EeF52

idex-market.biz.pl + more

---

blacklists/domains.json

grabeth.cf
https://urlscan.io/result/fb58aa6e-cc11-462f-a76a-9c85979b55e9/
address: 0x827216bd50d13B3e1daC8686e85f8B6B1bf2e856
ether-claim.com
https://urlscan.io/result/acccb957-ce0e-4ab7-a142-042494e47ea5/
address: 0x2dfc601dB0C0b5EEfc302249acDf936Dce83cFb3
eos-airdrop.info
Fake airdrop linking users to myetheruvvalet.com. Reported address: 0x81fbb23ce259d141339e49ece91599ed97cc8b49
https://urlscan.io/result/6ad84b0a-27ac-4221-9406-ca7d5e086946/
myethervallet.000webhostapp.com
Fake MyEtherWallet stealing keys
https://urlscan.io/result/8a2baecb-d55a-4935-b123-889d594dc6b1/
myetheruvvalet.com
Fake MyEtherWallet. Reported address: 0x81fbb23ce259d141339e49ece91599ed97cc8b49
https://urlscan.io/result/c1216b0d-be3e-474f-9f5c-dff5b4ba9424/

grabeth.cf + more

---

blacklists/domains.json

medeum-airdrop-news.com
Trust trading scam site - linking users to ethereum-transfer.net
https://urlscan.io/result/f163756e-08db-46b1-8528-bcb749d4e6e5/
address: 0x43FA247764BfBe1Beba49111e4ed215524f02c41
ethereum-transfer.net
https://urlscan.io/result/d84279a4-9e1e-414f-a5c3-9752f89c88a3/
address: 0x43FA247764BfBe1Beba49111e4ed215524f02c41

medeum-airdrop-news.com + ethereum-transfer.net

---

blacklists/domains.json

xn--bnanc-r51bze.com
Fake Binance - IDN homograph attack domain
https://urlscan.io/result/23f13b42-7281-4502-a330-19b2362cafce/
ycbit.net
Suspcious Yobit phishing for logins (not deployed yet)
https://urlscan.io/result/336676b4-d765-4f4a-aa6e-5e75686ba7b3/
kuccin.com
Suspcious Kucoin (not deployed yet)
https://urlscan.io/result/142167bc-a626-435e-9e43-9586f508b67e/
lnitbtc.com
Suspcious Hitbtc (not deployed yet)
https://urlscan.io/result/0242fd36-fc10-45e6-8ed6-26700ce07481/
www-nycryqto.com
Suspicious mycrypto domain
https://urlscan.io/result/a86bc4cb-06a6-4282-bbc7-69ae43518834/
www-nycryptos.com
Suspicious mycrypto domain
https://urlscan.io/result/e99a5f5f-c13e-4d79-b4c2-fd2a25fbd571/
go.ethers.pw
https://urlscan.io/result/2bc5066e-7bfa-4942-8c56-6dd9a533a29c/ …

xn--bnanc-r51bze.com + more

---

blacklists/domains.json

xn--omiseg-ul8b.com
Fake OmiseGo publication linking to a fake MyEtherWallet xn--myethrwalle-6qb4278g.com/#contracts
https://urlscan.io/result/2b86d579-3cac-44dd-8147-e52e9e863e8d
https://urlscan.io/result/4c6e80a7-ffce-4dc7-b707-9104669936fd
xn--myethrwalle-6qb4278g.com
Fake MyEtherWallet - IDN homograph attack - phishing for keys
https://urlscan.io/result/c3d99bd1-d309-4c42-a68a-d0fe0bf449d8
myethervvallet.net
https://urlscan.io/result/2d8b4d34-10da-4381-9cd0-6bb6617dcf9b/
myehterwelliet.com
https://urlscan.io/result/381b05a5-97c5-4545-9fd6-236bb65876a1/

xn--omiseg-ul8b.com + more

---

whitelists/domains.json

https://www.minds.com/token will live on Monday August 13th after an extensive testnet period

Adds Minds.com to whitelists

---

blacklists/domains.json

nectracker.co
Fake NeoTracker site phishing for keys
https://urlscan.io/result/470580cf-d797-4444-a047-2bb0e7f3aba9/
https://urlscan.io/result/a9d41439-27fd-460e-acf9-81984934ec61/
myethervvallet.org
https://urlscan.io/result/51d98126-c52f-413a-94f2-87b1ef5f4e5c/
ethereum10000.website
https://urlscan.io/result/ef02af45-3e4d-4f06-a4a9-2ca77deb9c42/
address: 0x4d2c10881813a371B2A6B8c0D9d06e83Ccb9E418
xn--dx-ejao.market
Fake Idex market phishing for keys with POST /furia.php
https://urlscan.io/result/9e413ef0-16b1-4c7e-9aca-1b592cd72b91/
https://urlscan.io/result/323dc4c0-2fdf-485f-ab42-f0ef411db642/
ethchange.online
Fake MyEtherWallet phishing for keys with POST bot/bot.php
https://urlscan.io/result/c26e99f6-40da-4997-bb8c-fceb9c08f1f4/ …

nectracker.co + more

---

blacklists/domains.json

bittrex-sigin.com
Fake Bittrex phishing for logins with POST /verification.php
https://urlscan.io/result/9875a705-35da-420a-bc8a-0c643d0db6dc/
---
giveaway.ether-claim.org
https://urlscan.io/result/4d447289-a35d-43cf-a885-b4a0a44eee71/
address: 0xe1228F81C01b80EfeFAC957483d63a40c6d635e1

bittrex-sigin.com

---

blacklists/domains.json

musk-air.org
https://urlscan.io/result/2dd66c5f-1860-440f-a21c-ea6b6869975d/
address: 0x72696cE345abB71398384e42CfbF6C9A995246c0
safe-claims.info
Trust trading scam site. Linking users to giveawaypromo.byethost14.com
https://urlscan.io/result/eb1d9dd5-6af9-452e-9eda-66278a02eddf/
address: 0x6a9c2ec4f4888d7338fc1b28584aaafeb01e6db3
bitstamp.pw
Fake Bitstamp exchange phishing for logins with POST /_indexSend.php
https://urlscan.io/result/eb5baf6a-4170-4502-986d-1dd07bc6abf5/
https://urlscan.io/result/5e607e6b-d132-4aec-b78b-d1789cefdc42
binance-web.com
Fake Binance exchange phishing for logins with POST /_loginSend.php
https://urlscan.io/result/61e8fd01-eaa0-45d0-a9a3-98cd6160ec25/
https://urlscan.io/result/b259851a-d380-4d5d-8ea3-6b128776ad03/

musk-air.org + more

---

blacklists/domains.json

eth-claim.pw
https://urlscan.io/result/73a07fe4-9426-4b11-942b-7c08b36ca480
address: 0x4D1DCFbF1299EB1007d55976754bb41a87eb9D0F
xn--tronscn-mwa.com
Fake Tronscan phishing for keys with POST /auth.php
https://urlscan.io/result/a1eb8d1b-d9ac-42ed-9a6b-e51c61dec208/
tron-scan.info
Fake Tronscan phishing for keys (redirecting to xn--tronscn-mwa.com)
https://urlscan.io/result/fa7e0bf6-18c5-4b40-89fa-aa76f9460e41/

eth-claim.pw + more

---

blacklists/domains.json

idexmark.online
Fake MyEtherWallet phishing for keys with POST /bot/bot.php
https://urlscan.io/result/5c785bb5-2fe3-4946-bf0a-b64585b7c414/
https://urlscan.io/result/5652f6ab-c39f-4755-a281-5c49911a4a89/
eth-gifting.com
https://urlscan.io/result/13b34ee3-3fbb-4d81-ba43-dbcf299f029b/
address: 0x5d0Dbbf6460Ba020A5ab06006Ea447ffC7612b2d

idexmark.online + eth-gifting.com

---

blacklists/domains.json

google.com.tokensale.ws
Fake Google crowdsale site
https://urlscan.io/result/51df4bee-f037-43be-8561-892e70a28dd5/
https://urlscan.io/result/c5804ad2-d3f1-4197-9dcb-ea248c7a11e5/
address: 0x89f4d39667Aa080502c517B613A6c92786aa14Bd

google.com.tokensale.ws

---

blacklists/domains.json

myetherwallat.club
https://urlscan.io/result/3194bdc5-fd8b-4fa6-a288-f30135f72892/
myetherwallet.co.nz
Suspicious MyEtherWallet domain - nothing deployed yet
https://urlscan.io/result/6dab8af2-ef51-4913-a894-882ac88caeef/
myethforkwallet.com.ru
Suspicious MyEtherWallet domain - nothing deployed yet
https://urlscan.io/result/4947578d-69d5-4416-b530-34bf52b08517/
myethherwalletr.com
Suspicious MyEtherWallet domain - nothing deployed yet
https://urlscan.io/result/82e20adb-21f0-4ad2-86f5-4223594859ce/
ww25.myethereum.info
Suspicious MyEtherWallet domain - nothing deployed yet
https://urlscan.io/result/0dc4fa4b-3043-4640-a3fa-afa668db4255/
myetherwallet.co.nz
Suspicious MyEtherWallet domain - nothing deployed yet
https://urlscan.io/result/20ec5cec-7f88-43f7-a225-1ae75979fa07/ …

myetherwallat.club + more

---

blacklists/domains.json

binance-lgin.com
Suspicious Binance domain (same infra as log-in-binance.com)
https://urlscan.io/result/d6d60680-720d-4c33-af19-617572b71cf6/
xn--methewallet-v48e1x.com
Suspicious MyEtherWallet domain - nothing deployed yet
https://urlscan.io/result/42d75e4f-18dd-40a5-a015-d5a605123374/
xn--myethrewalle-xoc.com
Suspicious MyEtherWallet domain - nothing deployed yet
https://urlscan.io/result/95537436-47d1-4903-aae1-5a376e34ecb5/

binance-lgin.com + more

---

blacklists/domains.json

elonmusk.ltd
Trust trading scam site. Linking users to elonmusk.fund/e/
https://urlscan.io/result/da9eb451-dc85-4095-b32c-dcc92e93d5d8/
address: 0x08afea4eC3659A2e478F81fef2B784176a0B7D2F
elonmusk.fund
https://urlscan.io/result/512de643-7033-413a-9985-bbd770559748/
address: 0x08afea4eC3659A2e478F81fef2B784176a0B7D2F
loginbinance-com.umbler.net
Fake binance phishing for logins with POST /processar_1.php
https://urlscan.io/result/0949343d-1f7b-4546-a3a1-8f598223d03e/

elonmusk.ltd + more

---

blacklists/domains.json

ethertoken.online
Fake MyEtherWallet phishing for keys with POST /bot/bot.php
https://urlscan.io/result/21ae7db2-4abc-43f4-a800-0df782112fde/
binance-ether.org
https://urlscan.io/result/bbf4c9d6-e344-4c6d-9d76-6348f87812a3/
address: 0x2784574e2405A7d3be1259B5F00412Ae652018f4
mywindorwallert.space
https://urlscan.io/result/0940becd-7e67-493d-a12a-ae26348f3660/
neostracker.com
Fake NEO tracker phishing for keys - https://twitter.com/jmoconnor415/status/1035688910188212224
https://urlscan.io/result/c0865dd6-b334-42af-9a1a-927769de0f4b/

ethertoken.online + more

---

blacklists/domains.json

elctrurn.org
Fake Electrum site with potentially malicious downloads: https://www.virustotal.com/#/url/cc732ec6eb0b8450ae616bed50fb14c5ca95e5859dba97367a00e3a5e9a541c4/detection
https://urlscan.io/result/f13a47ff-ba95-4ab4-a983-17742dcf797d/
jaxx.one
Fake Jaxx web wallet
https://urlscan.io/result/9e423c2c-5086-4af3-82bd-0107b47e710c/

elctrurn.org + more

---

blacklists/domains.json

ubex.us
Fake Ubex crowdsale site
https://urlscan.io/result/72bfdd26-0e73-4d29-8d97-f5429ef5660c
address: 0x1b7bdc46Fb5d65c6d688bFAdCfb7D3A434413956
bnbdex-ethcampaign.com
https://urlscan.io/result/6d22817f-7976-41f6-8f9b-999d18567c90/
https://urlscan.io/result/66310eaf-5177-4ab8-ad10-0872074b0918/
address: 0x0cBFf6C0365083f20C9De72084Be7FB11278Aa86

ubex.us + bnbdex-ethcampaign.com

---

blacklists/domains.json

cew.safewallet.replayattack.us
Fake MyEtherWallet/ClassicEtherWallet
https://urlscan.io/result/0158e0eb-40cf-42d8-af6b-7c03f6054e86/
medium.com.7t23-srv.site
Trust trading scam site. Linking users to www.etherium.org.payment.7t23-srv.site/promo/10000-eth-giveaway/
https://urlscan.io/result/47de7a61-9fb8-483a-9d06-2f99ff16fc29/
address: 0x075DC757633700b257E090d62b62AAC5997a99D4
etherium.org.payment.7t23-srv.site
https://urlscan.io/result/d26d6c05-ec3b-4567-b062-0fc558c916f7
address: 0x075DC757633700b257E090d62b62AAC5997a99D4

cew.safewallet.replayattack.us + more

---

blacklists/domains.json

firstcrypt.info
Fake exchange (clone of firecrypto.info). Bitcoin address: 1PTAaVk6onxkgU1ZXxMfcPG9txgQ6rYVef
https://urlscan.io/result/175caa23-598d-44e5-923c-ad2e338c1705/
https://urlscan.io/result/d40ba48e-6594-4925-b04b-bf06832c6bb9/
address: 0x1E711A766cD4EC07C590EeF54A112190B4826b4e

firstcrypt.info

---

blacklists/domains.json

b-crypto.me
Trust trading scam site. Bitcoin address: 1AZXBeoGtCnK5jVHaDBoNphsND2dLWtRE2
https://urlscan.io/result/390bc165-05e9-4873-96fa-ef24c8f5db86/
arbitragecoins.com
Scam bot - steals deposits - many many online reports
https://urlscan.io/result/0c42ceaf-833c-4b7e-b328-2c448bcc4303/
address: 0x3258674d5eb5cfca42c18585b95fff50e098ebd4
apexone.online
Clone of apexone.io
https://urlscan.io/result/1feff908-d6d2-439d-8d42-eac0e7236e58/
https://urlscan.io/result/afb0eb6a-a522-4d77-b3f4-b0937000762b/
address: 0x23f1909f7a65cba4d2a4a42ee1ba7d9772c3ba93

b-crypto.me + more

---

blacklists/domains.json

xn--dex-uma.market
Suspicious IDEX market domain
https://urlscan.io/result/6bcec480-a253-44c0-ad7c-6703abafa2da/
polonniex.online
Fake Poloniex phishing for logins with POST /login.php
https://urlscan.io/result/20ad0cce-79ca-4ea5-a3ed-dbf421e85a68/
niceihash.com
Fake Nicehash domain
https://urlscan.io/result/84d55dcf-7bb0-401c-97ec-34639aab802d/

xn--dex-uma.market + more

---

blacklists/domains.json

giftforfans.website
https://urlscan.io/result/95c1e2bf-1ff3-4eb2-b121-74f59bfec66f/
address: 0x08A14BD2E2993809583Fc20CE528f1C835Ea29e0
etherium.org.payment.7t27-srv.site
https://urlscan.io/result/7a906668-3296-437b-b43d-16ebb248a9cc/
https://urlscan.io/result/2254b1b3-f956-4fa4-84f3-7bad44fdd76b/
address: 0xb4A50B673cbfad24c3bF3E3e4cA46BE6FE7A87ea
address: 0xd343317205A5111D6aFb8343C996f1B3a7678290
giveawey.tumblr.com
https://phishcheck.me/124154/details
address: 0xeC4E9a06c4e024D03Dab3A27F66bCe03cC9bb33a
medium.com.7t27-srv.site
Trust trading scam site. Linking users to etherium.org.payment.7t27-srv.site/promo/10000-eth-giveaway/
https://urlscan.io/result/0eb745f4-dbb5-4b04-8812-077155504164/
address: …

giftforfans.website + more

---

blacklists/domains.json

line-crypto.com
Scam exchange
https://urlscan.io/result/9698ca7d-b6a1-48a5-ae3e-91177f8e2ccd
address: 0x1E711A766cD4EC07C590EeF54A112190B4826b4e
etherdelta.icu
Fake EtherDelta phishing for keys with POST /api.php
https://urlscan.io/result/c288eecd-d902-4ae4-8ff8-fe058644439b/
xtrony.blogspot.com
Trust trading scam site. Tron address: address:TPcDNYz4AxCaLCY2Xx4i95jGYwCjUrxg5r
https://urlscan.io/result/96886f2c-6d2b-4bb1-9e21-e53cb460f0e2/

line-crypto.com + more

---

blacklists/domains.json

bitcointolk.org
Fake Bitcoin talk forum phishing for logins
https://urlscan.io/result/7b4db913-0bd3-4b85-8948-8a87f8367bfb
coinbase.xm-login2.com
Fake Coinbase phishing for logins
https://urlscan.io/result/ea5e11dd-0134-4b7e-a158-77e4fb605757/
etherdesk.co
https://urlscan.io/result/4d5a6595-217d-4a83-8b0b-b4a219c110e2
address: 0x015f17e2851eA392351b7f259e4CFd03dc443CeF

bitcointolk.org + more

---

blacklists/domains.json

musk.claims
https://urlscan.io/result/a9db5309-babb-4d98-9a7a-8d6d9796c61b/
musk.click
Trust trading scam site - linking users to spacex.gives (not up yet)
https://urlscan.io/result/a5410d0c-07d0-46b5-9575-68cc4423017f/
spacex.gives
Trust trading scam site (not up yet)
https://urlscan.io/result/313c8eb3-a411-401a-a6dc-cedd7c949465/

musk.claims + more

---

blacklists/domains.json

doublecoinio.jdevcloud.com
Coin doubling scam (and email and public address harvester)
https://urlscan.io/result/ac9e3c36-61aa-4dbc-92be-0a865636c685/
https://urlscan.io/result/847fc504-9e56-4f35-acf3-0814da0b6a4a/
https://urlscan.io/result/4d428125-a99c-4498-9eeb-163e6df33dff/
mediium.org
https://urlscan.io/result/104d81ee-3a14-41d4-a702-9f1b899956b8/
https://urlscan.io/result/7971b8d8-ab99-4431-b0a5-273997b36d45/
address: TX9oqhThyQdGXrDMacRXAvsWPoxQspQLFw
myetherwallet-be.space 
Fake MyEtherWallet phishing for keys with POST /app/keys.php
https://urlscan.io/result/be43a3a8-91f2-48ba-8ed4-090678989795/
https://urlscan.io/result/02ec175c-88be-42b4-870c-2336b6d5c18c/
----
spacex.gives …

doublecoinio.jdevcloud.com + more

---

blacklists/domains.json

ether-contest.com
https://urlscan.io/result/be7e8b6f-bd02-4210-bd9c-67be4aedcbf5/
https://urlscan.io/result/f9d5845d-729e-4544-a1b8-670740c90ec3/
address: 0x81E4B65b9330C5693d38430111D7Eb174615bDD6
dex-huobiglo.info
https://urlscan.io/result/1051fc75-87ac-42b1-9587-60fae3c88f96/
https://urlscan.io/result/f4a4a41c-9f8b-401a-8ac3-36ceebfc20ed/
address: 0x57aa0ca8ddc99096d150f0dd1e1bd50616d809c8
address: bc1qw9cz3095dxnt5hkfdyltueen9g7j5w5u6c0zq9
telegra.ph/Crypto-Bible-team-are-giving-away-500-ETH-12-22-2
https://urlscan.io/result/9aaa2953-bb03-4948-ad32-6082b8eec0c5/
address: 0x95115419b09e8cea70a9bdbca3fee8c5e118b228

ether-contest.com + dex-huobiglo.info

---

blacklists/domains.json

crypto-positive.club
https://urlscan.io/result/0641a867-2b8f-4eef-a97e-c40457b135a9/
address: 1CKK4yMGjcbzEG8hWSdtNSQcoV8PDiGzDk
trustwallet.com.erc-20-tokens-gift.com
Fake TrustWallet bonus site phishing for keys with POST /claim.php
https://urlscan.io/result/fc05aadd-3f9c-4469-ab85-97dee762ea89/
https://urlscan.io/result/9baf231c-53d5-4208-8346-ee295253bd14/
https://urlscan.io/result/5c40fb87-d8e2-4aec-81b3-1586041e7e0b/

crypto-positive.club + more

---

blacklists/domains.json

btc-promo.net
https://urlscan.io/result/174696f7-93ea-46c5-9b7e-8e4196ee8eb4/
https://urlscan.io/result/99723685-b931-43e9-896a-7bc7c141dd03/
https://urlscan.io/result/e7bc9d2c-c5d2-4240-8272-8a2c63e72b9c/
address: 1AHkrJ55mxbUBEe1bn5MQNzH1sP8zSuKqS 
address: 0x9145Cb518FD02877FE8efA077c3EAd95235fDA22
waves-x.com
Fake waves project linking to client-wavesx.com that is stealing seed phrases
https://urlscan.io/result/0731dcc7-b3dd-4826-9518-579e99e27f7a/
etcv-wallet.co
Fake Ethereum wallet phishing for keys with POST /send.php
https://urlscan.io/result/5bc06a22-0ca5-4680-83a5-d45ec091550e/

btc-promo.net + more

---

blacklists/domains.json

bttlaunchpad.com
https://urlscan.io/result/2ce24d5c-92b2-4ce8-96d9-93384e429416/
https://urlscan.io/result/04868730-60b5-43da-9f93-9ce5e62ad1e7/
https://urlscan.io/result/bbf1e3f7-b706-46d7-8a9f-c9558600e422/
address: 0x8324676C7cd3a99391d1D69ce3d8A7c2b51c1f59
address: 3BgCXqtL8uh54XfB6TSbRkrA7dryBdSjA6

bttlaunchpad.com

---

whitelists/domains.json

Got an email from the person who owns the domain, currently blocked by fuzzy match

Add crypto.men to whitelist

---

blacklists/domains.json

btcholiday.net 
Trust trading scam site	
https://urlscan.io/result/c28ab2fe-3a83-4f44-8d25-dd3563bf750a/
vitalik.cf 
https://urlscan.io/result/590b0d96-4789-417f-b6fb-5646e5300dc4/
address: 0x738a8589924B5C924997DDFB23238064eD238920 
ether-give.org
https://urlscan.io/result/2a0c5b92-bc53-4ced-b5cc-88be7d873cad/
address: 0xf9c87DCf56598cE676FDdA2FEbfDB3Eb45e5007E
idexx-market.pw 
Fake Idex phishing for secrets with POST /log.php
https://urlscan.io/result/e7bf7e80-a405-40cd-a069-f15fad4df68b/
https://urlscan.io/result/0ccf0064-8f54-41e4-aa69-4017af1ad38d/
bittrex-global-site.com
Fake Bittrex phishing for logins
https://urlscan.io/result/be02ee81-3452-4b19-b1aa-7a452085ff60/
https://urlscan.io/result/f0079ab5-40e0-4e95-a9b3-11330977c64f/ …

btcholiday.net  + more

---

blacklists/domains.json

muskbit.com
Trust trading scam site - reported address 1AyQwZYKU36yiFPPoqnC1Cn4LLHQ1DbTDX
https://urlscan.io/result/3c27f0ec-f2a3-4ce3-a5b6-4f63dc218f3c/
blockchain5th.com
https://urlscan.io/result/961f417e-1745-4d35-9953-0282aaf733ca/
https://urlscan.io/result/eeb91df7-adcd-44f2-a342-21b34e1c85e4/
address: 0xB3805B7A3098F9E8E4C0A4bFa212d2C8d7d072a6 (eth)
address: 0x201D2A68bfB83D4DED413A29bB3B7c5002d32772 (eth)

muskbit.com + blockchain5th.com

---

blacklists/domains.json

bittrexthankgiving.com
https://urlscan.io/result/b7d2d38d-8297-4ef6-8a5b-308447110c67/
address: 0xb68ed1aBd5A55A0c3a2d7c377f9761f85e865a34 (eth)
mychainlink.org
Fake Chainlink airdrop site phishing for secrets with POST /sign.php
https://urlscan.io/result/9971dc7a-0c5a-4043-9a9b-e37a92868785/
https://urlscan.io/result/95145228-fe14-407b-bcf5-a872e63da5e1/
https://urlscan.io/result/2d443150-9e50-47f3-ba3b-569b5ecd9c1f/
biggest-airdrop.top
https://urlscan.io/result/447dcac7-1935-440f-b5e3-9b3bfb78b4c0/
address: 1PeYrv6TVfXAYgTpP95ANf5k1Cn31xtFuD (btc)
dai2sai.exchange
Fake Dai2Sai platform phishing for funds
https://urlscan.io/result/5566e5ad-8c7c-498a-a718-ecacd5466bb7/
https://urlscan.io/result/7224cfed-7dc1-4b5f-811f-a34957d6e638
address: …

bittrexthankgiving.com + more

---

blacklists/domains.json

metmamask.com
Fake MetaMask site phishing for secrets with POST /save.php
https://urlscan.io/result/e70c34e8-cb58-4f34-961d-6de75eaab87e/
faobit.com
Fake exchange phishing for deposits
https://urlscan.io/result/6d9d5864-60bd-4b1d-ae80-387d8926f66b/
address: qrwpnrpq7s670s3mlurs0z4szhqwd0nq2szp2mtnn6 (bch)
address: MGVm9Hc58piyRmhyFjCgaHMiazWAcM5swF (ltc)
address: 0xd67e205A5b7A5d82B86afBC59f67f74a878D1E68 (eth)
address: 3ACfrcziWsekdTWv9ayAGLrMU2PdMsCJxo (btc)

metmamask.com + more

---

blacklists/domains.json

myfusionwallet.com is the legit one and belongs to the Fusion protocol.
See https://github.com/fsn-dev/awesome-fusion#wallets
myfusionwallet.net is malicious one impersonating as myfusionwallet.com
See #[3921](https://github.com/MetaMask/eth-phishing-detect/issues/3921)

Remove myfusionwallet.com from blacklist

---

blacklists/domains.json

stellar.org.sb is a phishing site conducting a staking scam to collect stellar secret keys

Add stellar.org.sb to blocklist domains

---

whitelists/domains.json

seal.finance
Undo incorrect blacklist (assuming autoblacklisted because hosting uniswap on uniswap.seal.finance) from https://github.com/phishfort/phishfort-lists/commit/e483f46171849b8389271f348a5cfb97059b5452
https://urlscan.io/result/3b1762b7-f5d9-4e04-bde1-eb26fd58b166/

seal.finance
